//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface CAESCrypt : NSObject
{
}

+ (id)AESECBDecryptWithKey:(id)arg1 Data:(id)arg2 Final:(_Bool)arg3;
+ (id)AESECBEncryptWithKey:(id)arg1 Data:(id)arg2 Final:(_Bool)arg3;
+ (id)AESDecryptWithKey:(id)arg1 Data:(id)arg2;
+ (id)AESEncryptWithKey:(id)arg1 Data:(id)arg2;
- (id)init;

@end

