//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@interface FMSenderLabel : UIButton
{
    scoped_refptr_5f42bb84 sender_;
    int _senderState;
}

@property(nonatomic) int senderState; // @synthesize senderState=_senderState;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)updateFont;
- (id)content;
- (struct CGSize)intrinsicContentSize;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)initView;
- (const scoped_refptr_5f42bb84 *)sender;
- (void)setSender:(const scoped_refptr_5f42bb84 *)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

