//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol ForumServiceProxyObserverDelegate <NSObject>

@optional
- (void)onColleagueListSyncFinish:(_Bool)arg1;
- (void)onUpdatePostInfo:(const vector_9c16e832 *)arg1;
- (void)onDeletePostInfo:(const vector_9c16e832 *)arg1;
- (void)onAddPostInfo:(const vector_9c16e832 *)arg1;
@end

