//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AFHTTPRequestSerializer.h"

@interface GYCGIRequestSerializer : AFHTTPRequestSerializer
{
}

- (id)doGzip:(const void *)arg1 length:(unsigned long long)arg2;
- (id)requestWithURLString:(id)arg1 data:(id)arg2 error:(id *)arg3;
- (id)requestWithURLString:(id)arg1 parameters:(id)arg2 multipartData:(id)arg3 error:(id *)arg4;
- (id)requestWithURLString:(id)arg1 json:(id)arg2 error:(id *)arg3;

@end

