//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

#import "UIScrollViewDelegate-Protocol.h"

@class ImgLoadingView, NSString, UIImageView, WWKMeidaItem;
@protocol ImgScrollViewDelegate;

@interface ImgScrollView : UIScrollView <UIScrollViewDelegate>
{
    struct CGRect scaleOriginRect;
    struct CGRect initRect;
    ImgLoadingView *loadingView;
    _Bool _isQRscaned;
    _Bool _isShowOrginal;
    _Bool _isDownloading;
    _Bool _isEditable;
    _Bool _hasLoadOrginalImage;
    id <ImgScrollViewDelegate> _i_delegate;
    WWKMeidaItem *_imageItem;
    UIImageView *_imgView;
    struct CGSize _imgSize;
}

@property(nonatomic) struct CGSize imgSize; // @synthesize imgSize=_imgSize;
@property(retain, nonatomic) UIImageView *imgView; // @synthesize imgView=_imgView;
@property(retain, nonatomic) WWKMeidaItem *imageItem; // @synthesize imageItem=_imageItem;
@property(nonatomic) _Bool hasLoadOrginalImage; // @synthesize hasLoadOrginalImage=_hasLoadOrginalImage;
@property(nonatomic) _Bool isEditable; // @synthesize isEditable=_isEditable;
@property(nonatomic) _Bool isDownloading; // @synthesize isDownloading=_isDownloading;
@property(nonatomic) _Bool isShowOrginal; // @synthesize isShowOrginal=_isShowOrginal;
@property __weak id <ImgScrollViewDelegate> i_delegate; // @synthesize i_delegate=_i_delegate;
- (void).cxx_destruct;
- (void)tryGenerateHiResThumbnail:(id)arg1 imageURL:(id)arg2;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)saveImage;
- (void)doubleClick:(id)arg1;
- (void)singleClick:(id)arg1;
- (void)p_setUpActionSheet:(id)arg1;
- (void)imageLongPress:(id)arg1;
- (void)scrollViewDidZoom:(id)arg1;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)setMaskLayer:(id)arg1;
- (void)resetImageRect2;
- (void)resetImageRect;
- (void)setImage:(id)arg1;
- (_Bool)isVisible;
- (struct CGRect)imageRect;
- (void)rechangeInitRdct;
- (void)setAnimationRect;
- (void)cancelDownLoadOrginalImage;
- (void)showOrginalImageWithUrl:(id)arg1 andProgressCallBack:(CDUnknownBlockType)arg2 andCompletion:(CDUnknownBlockType)arg3;
- (void)setPreViewContentWithFrame:(struct CGRect)arg1 andUrl:(id)arg2 andPlaceHolder:(id)arg3;
- (void)setInitRect:(struct CGRect)arg1;
- (void)setContentWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

