//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableView.h>

@class CADisplayLink, NSIndexPath, NSMutableArray, UILongPressGestureRecognizer, UIView;
@protocol JXMovableCellTableViewDataSource, JXMovableCellTableViewDelegate;

@interface JXMovableCellTableView : UITableView
{
    _Bool _canEdgeScroll;
    double _gestureMinimumPressDuration;
    CDUnknownBlockType _drawMovalbeCellBlock;
    double _edgeScrollRange;
    UILongPressGestureRecognizer *_gesture;
    NSIndexPath *_selectedIndexPath;
    UIView *_tempView;
    NSMutableArray *_tempDataSource;
    CADisplayLink *_edgeScrollTimer;
}

@property(retain, nonatomic) CADisplayLink *edgeScrollTimer; // @synthesize edgeScrollTimer=_edgeScrollTimer;
@property(retain, nonatomic) NSMutableArray *tempDataSource; // @synthesize tempDataSource=_tempDataSource;
@property(retain, nonatomic) UIView *tempView; // @synthesize tempView=_tempView;
@property(retain, nonatomic) NSIndexPath *selectedIndexPath; // @synthesize selectedIndexPath=_selectedIndexPath;
@property(retain, nonatomic) UILongPressGestureRecognizer *gesture; // @synthesize gesture=_gesture;
@property(nonatomic) double edgeScrollRange; // @synthesize edgeScrollRange=_edgeScrollRange;
@property(nonatomic) _Bool canEdgeScroll; // @synthesize canEdgeScroll=_canEdgeScroll;
@property(copy, nonatomic) CDUnknownBlockType drawMovalbeCellBlock; // @synthesize drawMovalbeCellBlock=_drawMovalbeCellBlock;
@property(nonatomic) double gestureMinimumPressDuration; // @synthesize gestureMinimumPressDuration=_gestureMinimumPressDuration;
- (void).cxx_destruct;
- (void)jx_stopEdgeScroll;
- (void)jx_processEdgeScroll;
- (void)jx_startEdgeScroll;
- (void)jx_updateDataSourceAndCellFromIndexPath:(id)arg1 toIndexPath:(id)arg2;
- (id)jx_snapshotViewWithInputView:(id)arg1;
- (void)jx_gestureEndedOrCancelled:(id)arg1;
- (void)jx_gestureChanged:(id)arg1;
- (void)jx_gestureBegan:(id)arg1;
- (void)jx_processGesture:(id)arg1;
- (void)jx_removeGesture;
- (void)jx_addGesture;
- (void)jx_initData;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2;
- (void)dealloc;

// Remaining properties
@property(nonatomic) __weak id <JXMovableCellTableViewDataSource> dataSource; // @dynamic dataSource;
@property(nonatomic) __weak id <JXMovableCellTableViewDelegate> delegate; // @dynamic delegate;

@end

