//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MJRefreshHeader.h"

@class NSMutableDictionary, UILabel;

@interface MJRefreshStateHeader : MJRefreshHeader
{
    UILabel *_lastUpdatedTimeLabel;
    UILabel *_stateLabel;
    CDUnknownBlockType _lastUpdatedTimeText;
    NSMutableDictionary *_stateTitles;
}

@property(retain, nonatomic) NSMutableDictionary *stateTitles; // @synthesize stateTitles=_stateTitles;
@property(copy, nonatomic) CDUnknownBlockType lastUpdatedTimeText; // @synthesize lastUpdatedTimeText=_lastUpdatedTimeText;
- (void).cxx_destruct;
- (void)setState:(int)arg1;
- (void)placeSubviews;
- (void)prepare;
- (void)setLastUpdatedTimeKey:(id)arg1;
- (void)setTitle:(id)arg1 forState:(int)arg2;
@property(readonly, nonatomic) __weak UILabel *lastUpdatedTimeLabel;
@property(readonly, nonatomic) __weak UILabel *stateLabel;

@end

