//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSString, UIColor, UIImage;

@interface MMWebViewPresetUI : MMObject
{
    UIColor *_navigationBarColor;
    UIColor *_navigationBarTitleColor;
    UIColor *_navigationLeftItemFontColor;
    unsigned long long _statusBarColor;
    UIColor *_backgroundColor;
    UIImage *_navigationLeftIcon;
    NSString *_navigationBarTitle;
}

@property(copy, nonatomic) NSString *navigationBarTitle; // @synthesize navigationBarTitle=_navigationBarTitle;
@property(retain, nonatomic) UIImage *navigationLeftIcon; // @synthesize navigationLeftIcon=_navigationLeftIcon;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) unsigned long long statusBarColor; // @synthesize statusBarColor=_statusBarColor;
@property(retain, nonatomic) UIColor *navigationLeftItemFontColor; // @synthesize navigationLeftItemFontColor=_navigationLeftItemFontColor;
@property(retain, nonatomic) UIColor *navigationBarTitleColor; // @synthesize navigationBarTitleColor=_navigationBarTitleColor;
@property(retain, nonatomic) UIColor *navigationBarColor; // @synthesize navigationBarColor=_navigationBarColor;
- (void).cxx_destruct;

@end

