//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface NSObject (MethodSwizzlingCategory)
+ (void)switchMethodForCodeZipper;
+ (_Bool)swizzleMethod:(SEL)arg1 withMethod:(SEL)arg2;
- (void)QQforwardInvocation:(id)arg1;
- (id)QQmethodSignatureForSelector:(SEL)arg1;
@end

