//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (Additions)
+ (id)generateGuid;
- (id)getTelPhoneNumber;
- (id)dropHead:(id)arg1;
- (_Bool)checkIsLegalMobile:(unsigned short *)arg1 bufLen:(int)arg2;
- (id)getTelPhoneNumberAreaStringWithHead:(_Bool)arg1;
- (id)getTelPhoneNumberAreaString:(_Bool *)arg1;
- (id)getTelPhoneNumberAreaString;
@property(readonly, nonatomic) NSString *md5Hash;
- (long long)versionStringCompare:(id)arg1;
- (id)stringByAddingQueryDictionary:(id)arg1;
- (id)queryDictionaryUsingEncoding:(unsigned long long)arg1;
- (_Bool)isEmptyOrWhitespace;
- (_Bool)isWhitespaceAndNewlines;
@end

