//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface OpenSSLECDHWrapper : NSObject
{
}

- (void)dealloc;
- (int)geneECDHShareKey:(char *)arg1 andSvrPubKey:(char *)arg2 andSvrPubKeyLen:(unsigned int)arg3 andCliPrivKey:(const char *)arg4 andCliPrivKeyLen:(int)arg5;

@end

