//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray;

@interface QMSBaseResult : NSObject
{
    NSArray *_propertiesToResolve;
}

@property(retain, nonatomic) NSArray *propertiesToResolve; // @synthesize propertiesToResolve=_propertiesToResolve;
- (void).cxx_destruct;
- (id)description;
- (void)fillProperiesWithDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

