//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class QMUIEmotionView, UITextField, UITextView;

@interface QMUIQQEmotionManager : NSObject
{
    UITextField *_boundTextField;
    UITextView *_boundTextView;
    QMUIEmotionView *_emotionView;
    struct _NSRange _selectedRangeForBoundTextInput;
}

+ (void)asyncLoadImages:(id)arg1;
+ (id)emotionsForQQ;
+ (id)imageForQQEmotionWithIdentifier:(id)arg1;
@property(readonly, nonatomic) QMUIEmotionView *emotionView; // @synthesize emotionView=_emotionView;
@property(nonatomic) struct _NSRange selectedRangeForBoundTextInput; // @synthesize selectedRangeForBoundTextInput=_selectedRangeForBoundTextInput;
@property(nonatomic) __weak UITextView *boundTextView; // @synthesize boundTextView=_boundTextView;
@property(nonatomic) __weak UITextField *boundTextField; // @synthesize boundTextField=_boundTextField;
- (void).cxx_destruct;
- (_Bool)shouldTakeOverControlDeleteKeyWithChangeTextInRange:(struct _NSRange)arg1 replacementText:(id)arg2;
- (_Bool)deleteEmotionDisplayNameAtCurrentSelectedRangeForce:(_Bool)arg1;
- (id)boundInputView;
- (id)init;

@end

