//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class QMUIZoomImageView;

@protocol QMUIZoomImageViewDelegate <NSObject>

@optional
- (_Bool)enabledZoomViewInZoomImageView:(QMUIZoomImageView *)arg1;
- (void)longPressInZoomingImageView:(QMUIZoomImageView *)arg1;
- (void)doubleTouchInZoomingImageView:(QMUIZoomImageView *)arg1 location:(struct CGPoint)arg2;
- (void)singleTouchInZoomingImageView:(QMUIZoomImageView *)arg1 location:(struct CGPoint)arg2;
@end

