//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface QQOpenApiUtility : NSObject
{
}

+ (id)urlStringWithQQUinsArray:(id)arg1;
+ (id)dictionaryWithReturnString:(id)arg1 andQQUins:(id)arg2;
+ (id)UTF8StringWithBase64String:(id)arg1;
+ (id)dataWithBase64EncodedString:(id)arg1;
+ (id)base64EncodedStringWithUTF8String:(id)arg1;
+ (id)base64EncodedStringWithData:(id)arg1;
+ (int)openURL:(id)arg1;
+ (_Bool)canOpenURL:(id)arg1;

@end

