//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "WloginTranCallbackProtocol-Protocol.h"

@class MemSig, NSMutableDictionary, NSString, QRCodeCmd, QRParams, WloginTranSdk;

@interface QRCodeSdk : NSObject <WloginTranCallbackProtocol>
{
    id qrCodeDelegate;
    unsigned long long ddwAccountUin;
    MemSig *accountTGTSig;
    WloginTranSdk *qrCodeTransportSdk;
    id wtloginSdkHelper;
    int iQRCodeState;
    QRCodeCmd *qrCodeCmd;
    unsigned short wQr13TlvNum;
    unsigned short awQr13TlvFieled[64];
    NSMutableDictionary *uploadTlvDataDic;
    unsigned short retryTimes;
    unsigned int retryParams_dwAppid;
    unsigned int retryParams_dwSubAppid;
    QRParams *retryParams_params;
}

- (unsigned long long)getScanUin;
- (void)tranFailed:(int)arg1 withMsg:(id)arg2;
- (void)tranSuccessWithData:(id)arg1;
- (id)getQueryTlvDataBy:(int)arg1;
- (int)queryQRconfirm:(unsigned int)arg1;
- (int)getQRPic:(unsigned int)arg1 andSubAppid:(unsigned int)arg2 andQRParams:(id)arg3;
- (_Bool)addConfirmUploadTlv:(int)arg1 andData:(id)arg2;
- (int)confirmQRCode:(id)arg1 withT:(int)arg2 andData:(id)arg3;
- (int)verifyQRCode:(id)arg1 forAccount:(id)arg2 andAppid:(unsigned int)arg3;
- (id)getVerifyTlvDataBy:(int)arg1;
- (unsigned int)getAppidByLoginQRCode:(id)arg1;
- (_Bool)isValiedLoginQRCode:(id)arg1;
- (id)parseQRCode:(id)arg1 withDomain:(id)arg2;
- (void)addVryQRReqTlv:(unsigned short)arg1;
- (void)clearVryQRReqTlv;
- (void)ResetQRCodeStatus;
- (void)dealloc;
- (id)initWithQRCodeSdk:(id)arg1 andDelegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

