//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class RqdLocalStrategy;

@interface RqdCrashModule : NSObject
{
    _Bool _userEnabled;
    RqdLocalStrategy *_localStrategy;
    _Bool _hasLocalDB;
    _Bool _hasSyncServer;
    _Bool _ATSEnabled;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
@property(nonatomic) _Bool ATSEnabled; // @synthesize ATSEnabled=_ATSEnabled;
@property(nonatomic) _Bool hasSyncServer; // @synthesize hasSyncServer=_hasSyncServer;
@property(nonatomic) _Bool hasLocalDB; // @synthesize hasLocalDB=_hasLocalDB;
@property(retain, nonatomic) RqdLocalStrategy *localStrategy; // @synthesize localStrategy=_localStrategy;
@property(nonatomic) _Bool userEnabled; // @synthesize userEnabled=_userEnabled;
- (id)targetUrl;
- (void)checkAndUploadUserInfo;
- (id)creatSummaryInfo:(int)arg1 withTime:(long long)arg2;
- (void)insertUserChangeSm;
- (void)insertDailySummaryInfo;
- (void)closeDailySummaryInfodTimer;
- (void)initDailySummaryInfoTimer;
- (_Bool)processStrategy:(id)arg1;
- (_Bool)fetchCrashStrategyFormDB;
- (void)appRQDEnterBack;
- (void)appRQDResumed;
- (void)appRQDStarted;
- (void)initCrashProperties;
- (void)appEnterBackground;
- (void)appResumed;
- (void)unregistObserver;
- (void)registObserver;
- (_Bool)expExist;
- (void)enableModule;
- (void)disableModule;
- (_Bool)checkAndEnable;
- (id)init;
- (id)autorelease;
- (oneway void)release;
- (unsigned long long)retainCount;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

