//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface RqdRegisterDataCollector : NSObject
{
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
-     // Error parsing type: v32@0:8I16^{__darwin_mcontext64={__darwin_arm_exception_state64=QII}{__darwin_arm_thread_state64=[29Q]QQQQII}{__darwin_arm_neon_state64=[32T]II}}20B28, name: collectAllRegisterInfos:context:needCheckFirstLineOcMsg:
- (id)symbolOfRegister:(void *)arg1;
- (id)autorelease;
- (oneway void)release;
- (unsigned long long)retainCount;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

