//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TCAPIRequest.h"

@class NSString;

@interface TCCheckPageFansDic : TCAPIRequest
{
    NSString *_paramPage_id;
}

+ (id)dictionary;
@property(retain, nonatomic) NSString *paramPage_id; // @synthesize paramPage_id=_paramPage_id;
- (void).cxx_destruct;

@end

