//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface TCOError : NSObject
{
    long long _code;
    NSString *_msg;
}

+ (id)getLastQQApiError;
+ (id)getLastOAuthError;
+ (void)setLastQQApiError:(int)arg1 msg:(id)arg2;
+ (void)setLastOAuthError:(int)arg1 msg:(id)arg2;
@property(retain, nonatomic) NSString *msg; // @synthesize msg=_msg;
@property(nonatomic) long long code; // @synthesize code=_code;
- (void).cxx_destruct;

@end

