//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DevLockTlv_base.h"

@class NSString;

@interface Tlv_0x4_MbMobileInfo : DevLockTlv_base
{
    NSString *sCountryCode;
    NSString *sPhoneNo;
    unsigned int dwMbPhoneStatus;
    unsigned short wAvailMsgCnt;
    unsigned short wTimeLimit;
}

@property unsigned short wTimeLimit; // @synthesize wTimeLimit;
@property unsigned short wAvailMsgCnt; // @synthesize wAvailMsgCnt;
@property unsigned int dwMbPhoneStatus; // @synthesize dwMbPhoneStatus;
@property(copy) NSString *sPhoneNo; // @synthesize sPhoneNo;
@property(copy) NSString *sCountryCode; // @synthesize sCountryCode;
- (void)dealloc;
- (int)decode:(char **)arg1 andBuffLen:(int *)arg2;

@end

