//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIApplication.h>

@interface UIApplication (monitor)
+ (void)load;
- (void)new_setStatusBarHidden:(_Bool)arg1;
- (void)new_setStatusBarHidden:(_Bool)arg1 withAnimation:(long long)arg2;
- (void)new_setStatusBarHidden:(_Bool)arg1 animated:(_Bool)arg2;
@end

