//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSDate, NSString, WWKMessageEmotion;

@interface UIButton (Wework)
@property(retain, nonatomic) NSDate *selectDate; // @dynamic selectDate;
@property(nonatomic) unsigned int correctCheckinTime; // @dynamic correctCheckinTime;
@property(nonatomic) unsigned int attendanceTimeLineID; // @dynamic attendanceTimeLineID;
@property(copy, nonatomic) WWKMessageEmotion *emotionMessage; // @dynamic emotionMessage;
@property(copy, nonatomic) NSString *emotionString; // @dynamic emotionString;
@property(copy, nonatomic) NSString *assetIdentifier; // @dynamic assetIdentifier;
@property(nonatomic) int checkinType; // @dynamic checkinType;
@property(nonatomic) unsigned int daymonthyear; // @dynamic daymonthyear;
@property(nonatomic) unsigned int groupid; // @dynamic groupid;
@property(nonatomic) unsigned int scheduleId; // @dynamic scheduleId;
@property(nonatomic) unsigned long long userID; // @dynamic userID;
@end

