//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

@interface UINavigationController (NavigationBarTransition)
+ (void)load;
- (void)handlePopViewControllerNavigationBarTransitionWithDisappearViewController:(id)arg1 appearViewController:(id)arg2;
- (id)NavigationBarTransition_popToRootViewControllerAnimated:(_Bool)arg1;
- (id)NavigationBarTransition_popToViewController:(id)arg1 animated:(_Bool)arg2;
- (id)NavigationBarTransition_popViewControllerAnimated:(_Bool)arg1;
- (void)setupNavigationBarAppearanceWithViewController:(id)arg1;
- (void)NavigationBarTransition_pushViewController:(id)arg1 animated:(_Bool)arg2;
@end

