//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

@interface UINavigationController (NavigationHelper)
- (void)popToCtrl:(Class)arg1;
- (void)pushToCtrl:(id)arg1 FromCtrl:(id)arg2;
- (void)pushToCtrl:(id)arg1 FromClass:(Class)arg2;
@end

