//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableView.h>

@interface UITableView (SimpleTableViewHeader)
- (double)notificationSettingFooterHeightWithText:(id)arg1;
- (double)notificationSettingHeaderHeightWithText:(id)arg1;
- (id)notificationSettingHeaderViewWithText:(id)arg1;
- (id)notificationSettingFooterViewWithText:(id)arg1 textColor:(id)arg2;
- (id)notificationSettingFooterViewWithText:(id)arg1;
- (id)headerViewWithImageURL:(id)arg1 andText:(id)arg2;
- (id)headerViewWithImageName:(id)arg1 andText:(id)arg2;
- (id)applyHeaderViewWithText:(id)arg1;
- (id)recentContactsHeaderViewWithText:(id)arg1;
- (id)commonHeaderViewWithText:(id)arg1 height:(double)arg2 fontSize:(double)arg3;
- (id)commonHeaderViewWithText:(id)arg1;
@end

