//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (Presentation)
+ (id)wwk_presentedControllers;
+ (id)p_presentedControllers;
- (double)wwk_preferredWindowLevel;
- (void)wwk_hide;
- (void)wwk_show;
- (_Bool)wwk_isPresent;
- (void)wwk_dismissAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)wwk_dismissAnimated:(_Bool)arg1;
- (void)wwk_presentAnimated:(_Bool)arg1 windowLevel:(double)arg2 statusbarHidden:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)wwk_presentAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)wwk_presentAnimated:(_Bool)arg1 statusbarHidden:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)wwk_presentAnimated:(_Bool)arg1;
@end

