//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MZFormSheetController;

@interface UIViewController (MZFormSheet)
- (void)mz_dismissFormSheetControllerAnimated:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)mz_presentFormSheetWithViewController:(id)arg1 animated:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)mz_presentFormSheetWithViewController:(id)arg1 animated:(_Bool)arg2 transitionStyle:(long long)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)mz_presentFormSheetController:(id)arg1 animated:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, nonatomic) MZFormSheetController *formSheetController; // @dynamic formSheetController;
@end

