//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "WCDBCoding-Protocol.h"

@class NSString;

@interface WALocalStorageMainInfo : NSObject <WCDBCoding>
{
    unsigned int lastModifyTime;
    NSString *appID;
    unsigned long long storageLength;
    long long m___rowID;
}

+ (const basic_string_a490aa4c *)getWCDBPrimaryColumnName;
+ (const struct WCDBIndexHelper *)getWCDBIndexArray;
+ (unsigned long long)getWCDBIndexArrayCount;
+ (const map_24f1cf24 *)getFileValueTagIndexMap;
+ (id)getFileValueTypeTable;
+ (const map_24f1cf24 *)getPackedValueTagIndexMap;
+ (id)getPackedValueTypeTable;
+ (const map_64c9abee *)getValueNameIndexMap;
+ (id)getValueTable;
+ (id)dummyObject;
@property(nonatomic) long long __rowID; // @synthesize __rowID=m___rowID;
@property(nonatomic) unsigned int lastModifyTime; // @synthesize lastModifyTime;
@property(nonatomic) unsigned long long storageLength; // @synthesize storageLength;
@property(retain, nonatomic) NSString *appID; // @synthesize appID;
- (void).cxx_destruct;
- (const map_24f1cf24 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const WCDBCondition_c6db074e *)db_lastModifyTime;
- (const WCDBCondition_7786cbb5 *)db_storageLength;
- (const WCDBCondition_22fabacd *)db_appID;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

