//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBCoding-Protocol.h"

@class NSArray, NSDictionary;

@protocol WCDBCoding <PBCoding>
+ (id)dummyObject;
+ (const map_64c9abee *)getValueNameIndexMap;
+ (NSArray *)getValueTable;
@property(nonatomic) long long __rowID;

@optional
+ (NSDictionary *)getWCDBTableHelperDictionary;
+ (const map_24f1cf24 *)getFileValueTagIndexMap;
+ (NSArray *)getFileValueTypeTable;
+ (const map_24f1cf24 *)getPackedValueTagIndexMap;
+ (NSArray *)getPackedValueTypeTable;
+ (const basic_string_a490aa4c *)getWCDBPrimaryColumnName;
+ (const struct WCDBIndexHelper *)getWCDBIndexArray;
+ (unsigned long long)getWCDBIndexArrayCount;
@end

