//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WCDBConfigCheckpoint : NSObject
{
    _Bool m_integrity;
    _Bool m_skipMainThread;
    _Bool m_keepIndexRecover;
    int m_failedLimit;
    int m_frame;
}

+ (void)initialize;
@property(nonatomic) _Bool m_keepIndexRecover; // @synthesize m_keepIndexRecover;
@property(nonatomic) int m_frame; // @synthesize m_frame;
@property(nonatomic) _Bool m_skipMainThread; // @synthesize m_skipMainThread;
@property(nonatomic) int m_failedLimit; // @synthesize m_failedLimit;
@property(nonatomic) _Bool m_integrity; // @synthesize m_integrity;
- (const map_24f1cf24 *)getValueTagIndexMap;
- (id)getValueTypeTable;

@end

