//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray, UIButton, UIImageView, UILabel, WWCardWallHeaderTagContainerView;

@interface WWCardWallHeaderSummaryView : UIView
{
    NSMutableArray *_posLabels;
    _Bool _hasMoreData;
    _Bool _isCardHolder;
    UILabel *_titleLabel;
    NSMutableArray *_posTitles;
    UILabel *_subTitleLabel2;
    UILabel *_subTitleLvcabel2;
    UIView *_line;
    UIButton *_vidlistButton;
    UIImageView *_vidlistArrowView;
    UIButton *_addContactButton;
    UIView *_separatorView;
    UIButton *_starView;
    UIView *_verticalLineView;
    WWCardWallHeaderTagContainerView *_containerView;
}

@property(nonatomic) _Bool isCardHolder; // @synthesize isCardHolder=_isCardHolder;
@property(retain, nonatomic) WWCardWallHeaderTagContainerView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIView *verticalLineView; // @synthesize verticalLineView=_verticalLineView;
@property(retain, nonatomic) UIButton *starView; // @synthesize starView=_starView;
@property(retain, nonatomic) UIView *separatorView; // @synthesize separatorView=_separatorView;
@property(retain, nonatomic) UIButton *addContactButton; // @synthesize addContactButton=_addContactButton;
@property(retain, nonatomic) UIImageView *vidlistArrowView; // @synthesize vidlistArrowView=_vidlistArrowView;
@property(retain, nonatomic) UIButton *vidlistButton; // @synthesize vidlistButton=_vidlistButton;
@property(retain, nonatomic) UIView *line; // @synthesize line=_line;
@property(retain, nonatomic) UILabel *subTitleLvcabel2; // @synthesize subTitleLvcabel2=_subTitleLvcabel2;
@property(retain, nonatomic) UILabel *subTitleLabel2; // @synthesize subTitleLabel2=_subTitleLabel2;
@property(retain, nonatomic) NSMutableArray *posTitles; // @synthesize posTitles=_posTitles;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) _Bool hasMoreData; // @synthesize hasMoreData=_hasMoreData;
- (void).cxx_destruct;
- (struct CGSize)layoutSubviewsWithWidth:(double)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setTagArr:(id)arg1;
- (void)initSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

