//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSMutableArray, UIImageView, WWKCardWallHeadTagButton;

@interface WWCardWallHeaderTagContainerView : UIControl
{
    NSMutableArray *_tagButtonArr;
    UIImageView *_tagIcon;
    NSMutableArray *_tagArr;
    WWKCardWallHeadTagButton *_addTagTitle;
}

@property(retain, nonatomic) WWKCardWallHeadTagButton *addTagTitle; // @synthesize addTagTitle=_addTagTitle;
@property(retain, nonatomic) NSMutableArray *tagArr; // @synthesize tagArr=_tagArr;
@property(retain, nonatomic) UIImageView *tagIcon; // @synthesize tagIcon=_tagIcon;
- (void).cxx_destruct;
- (struct CGSize)layoutSubviewsWithWidth:(double)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)initSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

