//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWCardWallCell.h"

@class UIButton, UILabel, UIView, WWCardWallTagBackgroundView, WWKAvatarImageView;

@interface WWCardWallCommentCell : WWCardWallCell
{
    _Bool _isLastCell;
    UILabel *_commentLabel;
    UILabel *_commentUserLabel;
    WWKAvatarImageView *_userAvatarImageView;
    UIButton *_avatarButton;
    UILabel *_commentTimeLabel;
    WWCardWallTagBackgroundView *_bgView;
    UIView *_bgView2;
    long long _colorNo;
}

@property(nonatomic, setter=setLastCell:) _Bool isLastCell; // @synthesize isLastCell=_isLastCell;
@property(nonatomic, setter=setColorNo:) long long colorNo; // @synthesize colorNo=_colorNo;
@property(retain, nonatomic) UIView *bgView2; // @synthesize bgView2=_bgView2;
@property(retain, nonatomic) WWCardWallTagBackgroundView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) UILabel *commentTimeLabel; // @synthesize commentTimeLabel=_commentTimeLabel;
@property(retain, nonatomic) UIButton *avatarButton; // @synthesize avatarButton=_avatarButton;
@property(retain, nonatomic) WWKAvatarImageView *userAvatarImageView; // @synthesize userAvatarImageView=_userAvatarImageView;
@property(retain, nonatomic) UILabel *commentUserLabel; // @synthesize commentUserLabel=_commentUserLabel;
@property(retain, nonatomic) UILabel *commentLabel; // @synthesize commentLabel=_commentLabel;
- (void).cxx_destruct;
- (void)avatarDidClick:(id)arg1;
- (struct CGSize)layoutSubviewsWithWidth:(double)arg1;
- (void)NeedsUpdataData;
- (void)updateData;
- (void)initSubViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

