//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWCardWallCell.h"

@class UIImageView, UILabel, UIView;

@interface WWCardWallSelectTagCell : WWCardWallCell
{
    _Bool _hasTag;
    UILabel *_titleLabel;
    UILabel *_defaultLabel;
    UILabel *_tagLabel;
    UIView *_tagView;
    UIImageView *_arrowImageView;
}

@property(nonatomic, setter=setHasTag:) _Bool hasTag; // @synthesize hasTag=_hasTag;
@property(retain, nonatomic) UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(retain, nonatomic) UIView *tagView; // @synthesize tagView=_tagView;
@property(retain, nonatomic) UILabel *tagLabel; // @synthesize tagLabel=_tagLabel;
@property(retain, nonatomic) UILabel *defaultLabel; // @synthesize defaultLabel=_defaultLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)initSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

