//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, WWKNinePatchImage;

@interface WWCardWallHeaderMagnifierView : UIView
{
    WWKNinePatchImage *_arrowUpFrame;
    WWKNinePatchImage *_arrowDownFrame;
    WWKNinePatchImage *_arrowUpMask;
    WWKNinePatchImage *_arrowDownMask;
    UIImageView *_cardImageView;
    UIImageView *_magnifierView;
    UIImageView *_magnifierFrameView;
    struct CGRect _magnifierRect;
}

@property(nonatomic) struct CGRect magnifierRect; // @synthesize magnifierRect=_magnifierRect;
@property(retain, nonatomic) UIImageView *magnifierFrameView; // @synthesize magnifierFrameView=_magnifierFrameView;
@property(retain, nonatomic) UIImageView *magnifierView; // @synthesize magnifierView=_magnifierView;
@property(retain, nonatomic) UIImageView *cardImageView; // @synthesize cardImageView=_cardImageView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)magnifierFrameImageWithSize:(struct CGSize)arg1 orientation:(long long)arg2;
- (id)magnifierMaskImageWithSize:(struct CGSize)arg1 orientation:(long long)arg2;
- (void)hideMagnifier;
- (void)showMagnifier;
- (void)showMagnifierForRect:(struct CGRect)arg1;
- (void)initSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

