//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UILabel, WWKAvatarImageView;

@interface WWCorpPayReceiptUserPayCell : UITableViewCell
{
    unsigned long long _cellUIType;
    UILabel *_nameLbl;
    UILabel *_payInfoLbl;
    UILabel *_payNotesLbl;
    WWKAvatarImageView *_avatarView;
    unsigned long long _vid;
}

+ (double)cellHeightForReceiptPerson:(const struct ReceiptPerson *)arg1;
@property(nonatomic) unsigned long long vid; // @synthesize vid=_vid;
@property(retain, nonatomic) WWKAvatarImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) UILabel *payNotesLbl; // @synthesize payNotesLbl=_payNotesLbl;
@property(retain, nonatomic) UILabel *payInfoLbl; // @synthesize payInfoLbl=_payInfoLbl;
@property(retain, nonatomic) UILabel *nameLbl; // @synthesize nameLbl=_nameLbl;
@property(nonatomic) unsigned long long cellUIType; // @synthesize cellUIType=_cellUIType;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (double)p_layoutCellInternal;
- (void)p_asyncUpdateAvatarAndName:(const struct ReceiptPerson *)arg1;
- (void)updateWithReceiptPerson:(const struct ReceiptPerson *)arg1;
- (id)p_invalidPersonWordingFromResultReason:(int)arg1;
- (id)p_createLbl;
- (void)p_init;
- (id)init;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

