//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSMutableArray;

@interface WWFavoritesItemChatView : UIView
{
    NSArray *_chatList;
    NSMutableArray *_userLabels;
    NSMutableArray *_messageLabels;
}

@property(retain, nonatomic) NSMutableArray *messageLabels; // @synthesize messageLabels=_messageLabels;
@property(retain, nonatomic) NSMutableArray *userLabels; // @synthesize userLabels=_userLabels;
@property(retain, nonatomic) NSArray *chatList; // @synthesize chatList=_chatList;
- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)renderFont;
- (void)initSubviews;
- (id)init;

@end

