//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWFavoritesItemBaseCellView.h"

@class UIImageView, UILabel;

@interface WWFavoritesItemFileCellView : WWFavoritesItemBaseCellView
{
    UIImageView *_fileIconImageView;
    UILabel *_fileNameLabel;
    UILabel *_fileSizeLabel;
}

+ (double)cellHeightForFavItem:(id)arg1;
@property(retain, nonatomic) UILabel *fileSizeLabel; // @synthesize fileSizeLabel=_fileSizeLabel;
@property(retain, nonatomic) UILabel *fileNameLabel; // @synthesize fileNameLabel=_fileNameLabel;
@property(retain, nonatomic) UIImageView *fileIconImageView; // @synthesize fileIconImageView=_fileIconImageView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)initContentData;
- (void)initContentView;

@end

