//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class HeaderTextView, UIScrollView;

@interface WWKAttendanceLocationCollectViewController : UIViewController
{
    CDUnknownBlockType _dismissBlock;
    UIScrollView *_scrollView;
    HeaderTextView *_headerView;
}

@property(retain, nonatomic) HeaderTextView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(copy, nonatomic) CDUnknownBlockType dismissBlock; // @synthesize dismissBlock=_dismissBlock;
- (void).cxx_destruct;
- (void)p_cancel:(id)arg1;
- (void)p_onClickSubmit:(id)arg1;
- (void)viewDidLoad;

@end

