//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKApplicationPageDataSource.h"

@interface WWKApplicationPageCollectionDataSource : WWKApplicationPageDataSource
{
}

- (void)fixItemsInSection:(id)arg1;
- (id)getCachedDataWithType:(long long)arg1;
- (void)loadDataWithType:(long long)arg1 withCallback:(CDUnknownBlockType)arg2;
- (long long)numberOfRowsPerLine;

@end

