//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UILabel;

@interface WWKAddInvoiceHeaderContainer : UIView
{
    UIView *_topSeperator;
    UIView *_bottomSeperator;
    UILabel *_titleLabel;
    UIButton *_corpButton;
    UIButton *_personalButton;
}

@property(retain, nonatomic) UIButton *personalButton; // @synthesize personalButton=_personalButton;
@property(retain, nonatomic) UIButton *corpButton; // @synthesize corpButton=_corpButton;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)layoutSubViewsWithWidth:(double)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)p_createBtnWithTitle:(id)arg1;
- (void)initSubViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

