//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "WWKManageNotifyPopDelegate-Protocol.h"

@class NSString, UIButton, UILabel, UIView, WWKAnalysisView;

@interface WWKAnalysisCell : UITableViewCell <WWKManageNotifyPopDelegate>
{
    UILabel *_titleLabel;
    UIButton *_inviteButton;
    WWKAnalysisView *_statusView;
    UIView *_separator;
    _Bool _isInviteState;
}

+ (double)estimatedCellHeightWithInviteState:(_Bool)arg1 showInviteButton:(_Bool)arg2;
- (void).cxx_destruct;
- (void)didClickInviteInPopController:(id)arg1;
- (void)didClickInviteButton;
- (void)layoutSubviews;
- (void)showInviteButton:(_Bool)arg1;
- (void)updateCellApperanceWithInviteState:(_Bool)arg1 corpMemberCount:(unsigned long long)arg2 unjoinedMemberCount:(unsigned long long)arg3;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

