//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKSimpleTableViewCell.h"

@class UILabel;

@interface WWKAttendanceRulesTableViewCell : WWKSimpleTableViewCell
{
    UILabel *_firstRowLabel;
    UILabel *_secondRowLabel;
    UILabel *_thirdRowLabel;
    UILabel *_ruleNameHintLabel;
    UILabel *_timeHintLabel;
    UILabel *_locationHintLabel;
}

@property(retain, nonatomic) UILabel *locationHintLabel; // @synthesize locationHintLabel=_locationHintLabel;
@property(retain, nonatomic) UILabel *timeHintLabel; // @synthesize timeHintLabel=_timeHintLabel;
@property(retain, nonatomic) UILabel *ruleNameHintLabel; // @synthesize ruleNameHintLabel=_ruleNameHintLabel;
@property(retain, nonatomic) UILabel *thirdRowLabel; // @synthesize thirdRowLabel=_thirdRowLabel;
@property(retain, nonatomic) UILabel *secondRowLabel; // @synthesize secondRowLabel=_secondRowLabel;
@property(retain, nonatomic) UILabel *firstRowLabel; // @synthesize firstRowLabel=_firstRowLabel;
- (void).cxx_destruct;
- (id)p_createContentLabel;
- (id)p_createHintLabel;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

