//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKConversationMessageBubbleView.h"

@class WWKMessageCardItem;

@interface WWKBaseCardItemView : WWKConversationMessageBubbleView
{
    WWKMessageCardItem *_cardItem;
    CDUnknownBlockType _viewDidTapBlock;
    CDUnknownBlockType _contextMenuForwarding;
    CDUnknownBlockType _contextMenuFavorites;
    CDUnknownBlockType _contextMenuDeleteMsg;
    CDUnknownBlockType _contextMenuMore;
}

@property(copy, nonatomic) CDUnknownBlockType contextMenuMore; // @synthesize contextMenuMore=_contextMenuMore;
@property(copy, nonatomic) CDUnknownBlockType contextMenuDeleteMsg; // @synthesize contextMenuDeleteMsg=_contextMenuDeleteMsg;
@property(copy, nonatomic) CDUnknownBlockType contextMenuFavorites; // @synthesize contextMenuFavorites=_contextMenuFavorites;
@property(copy, nonatomic) CDUnknownBlockType contextMenuForwarding; // @synthesize contextMenuForwarding=_contextMenuForwarding;
@property(copy, nonatomic) CDUnknownBlockType viewDidTapBlock; // @synthesize viewDidTapBlock=_viewDidTapBlock;
@property(retain, nonatomic) WWKMessageCardItem *cardItem; // @synthesize cardItem=_cardItem;
- (void).cxx_destruct;
- (void)contextMenuMore:(id)arg1;
- (void)contextMenuDeleteMsg:(id)arg1;
- (void)contextMenuFavorites:(id)arg1;
- (void)contextMenuForwarding:(id)arg1;
- (id)contextMenuItems;
- (void)viewDidTap:(id)arg1;
- (_Bool)needsArrow;
- (void)updateBubble:(_Bool)arg1;

@end

