//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, UIColor;

@interface WWKCorpEditItem : NSObject
{
    _Bool _disableEditFirstItem;
    _Bool _disableEditSecondItem;
    NSString *_title;
    NSString *_content;
    NSString *_placeHolder;
    NSString *_cardUrl;
    unsigned long long _cellType;
    SEL _action;
    id _target;
    NSString *_extra;
    UIColor *_backgroundColor;
    struct PhoneItem _phoneItem;
}

@property(nonatomic) struct PhoneItem phoneItem; // @synthesize phoneItem=_phoneItem;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(retain, nonatomic) NSString *extra; // @synthesize extra=_extra;
@property(nonatomic) _Bool disableEditSecondItem; // @synthesize disableEditSecondItem=_disableEditSecondItem;
@property(nonatomic) _Bool disableEditFirstItem; // @synthesize disableEditFirstItem=_disableEditFirstItem;
@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(nonatomic) SEL action; // @synthesize action=_action;
@property(nonatomic) unsigned long long cellType; // @synthesize cellType=_cellType;
@property(retain, nonatomic) NSString *cardUrl; // @synthesize cardUrl=_cardUrl;
@property(retain, nonatomic) NSString *placeHolder; // @synthesize placeHolder=_placeHolder;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (id).cxx_construct;
- (void).cxx_destruct;

@end

