//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKConversationMessageBubbleView.h"

@class UIButton, UILabel, UIView, WWKAvatarImageView, WWRedEnvPushTagView;

@interface WWKConversationHBRankListBubbleView : WWKConversationMessageBubbleView
{
    double _summaryLabelHeight;
    UILabel *_titleLabel;
    UILabel *_topPosLabel;
    UILabel *_topMoneyLabel;
    UILabel *_topMoneyUnitLabel;
    UIView *_seperator1;
    WWKAvatarImageView *_topAvatarView;
    UIView *_seperator2;
    UIButton *_readFullContentButton;
    WWRedEnvPushTagView *_tagView;
}

@property(retain, nonatomic) WWRedEnvPushTagView *tagView; // @synthesize tagView=_tagView;
@property(retain, nonatomic) UIButton *readFullContentButton; // @synthesize readFullContentButton=_readFullContentButton;
@property(retain, nonatomic) UIView *seperator2; // @synthesize seperator2=_seperator2;
@property(retain, nonatomic) WWKAvatarImageView *topAvatarView; // @synthesize topAvatarView=_topAvatarView;
@property(retain, nonatomic) UIView *seperator1; // @synthesize seperator1=_seperator1;
@property(retain, nonatomic) UILabel *topMoneyUnitLabel; // @synthesize topMoneyUnitLabel=_topMoneyUnitLabel;
@property(retain, nonatomic) UILabel *topMoneyLabel; // @synthesize topMoneyLabel=_topMoneyLabel;
@property(retain, nonatomic) UILabel *topPosLabel; // @synthesize topPosLabel=_topPosLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)viewDidTap:(id)arg1;
- (struct CGSize)layoutSubviewsWithWidth:(double)arg1;
- (void)updateBubble:(_Bool)arg1;
- (_Bool)needsArrow;
- (void)updateData;
- (void)initSubviews;

@end

