//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WWKCellTypeAndActionObject : NSObject
{
    Class _cellClass;
    Class _cellDataWrapper;
    CDUnknownBlockType _selectAction;
    CDUnknownBlockType _deleteAction;
    CDUnknownBlockType _setTopAction;
}

@property(copy, nonatomic) CDUnknownBlockType setTopAction; // @synthesize setTopAction=_setTopAction;
@property(copy, nonatomic) CDUnknownBlockType deleteAction; // @synthesize deleteAction=_deleteAction;
@property(copy, nonatomic) CDUnknownBlockType selectAction; // @synthesize selectAction=_selectAction;
@property(nonatomic) Class cellDataWrapper; // @synthesize cellDataWrapper=_cellDataWrapper;
@property(nonatomic) Class cellClass; // @synthesize cellClass=_cellClass;
- (void).cxx_destruct;

@end

