//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel;

@interface WWKCorpInfoCommonTableViewCell : UITableViewCell
{
    _Bool _isSupplimentalInfo;
    UILabel *_titleLabel;
    UILabel *_contentLabel;
    UIImageView *_supplimentalImageView;
}

+ (_Bool)requiresConstraintBasedLayout;
@property(retain, nonatomic) UIImageView *supplimentalImageView; // @synthesize supplimentalImageView=_supplimentalImageView;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) _Bool isSupplimentalInfo; // @synthesize isSupplimentalInfo=_isSupplimentalInfo;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)updateConstraints;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

