//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSFileCoordinator, NSString, NSURL;
@protocol WWKEPostBoxSecretary;

@interface WWKEPostBox : NSObject
{
    id <WWKEPostBoxSecretary> _secretary;
    CDUnknownBlockType _handler;
    NSFileCoordinator *_coordinator;
    NSURL *_inboxURL;
    NSString *_notificationName;
}

+ (id)postBoxWithIdentifier:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (id)postBoxWithIdentifier:(id)arg1 secretary:(id)arg2;
@property(retain, nonatomic) NSString *notificationName; // @synthesize notificationName=_notificationName;
@property(retain, nonatomic) NSURL *inboxURL; // @synthesize inboxURL=_inboxURL;
@property(retain, nonatomic) NSFileCoordinator *coordinator; // @synthesize coordinator=_coordinator;
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(nonatomic) __weak id <WWKEPostBoxSecretary> secretary; // @synthesize secretary=_secretary;
- (void).cxx_destruct;
- (id)inboxURLWithIdentifier:(id)arg1;
- (unsigned long long)dispatchReceivedCommand:(const struct Command *)arg1;
- (struct Command)preprocessCommand:(const struct Command *)arg1;
- (void)post:(const struct Command *)arg1 to:(id)arg2;
- (void)recv:(_Bool)arg1;
- (void)recv;
- (void)dealloc;
- (id)initWithIdentifier:(id)arg1 secretary:(id)arg2 handler:(CDUnknownBlockType)arg3;
- (id)initWithIdentifier:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (id)initWithIdentifier:(id)arg1 secretary:(id)arg2;

@end

