//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIScrollViewDelegate-Protocol.h"
#import "WWFavoritesProxyObserverDelegate-Protocol.h"
#import "WWKCustomEmotionPageViewDelegate-Protocol.h"
#import "WWKEmotionSinglePageViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UIButton, UIPageControl, UIScrollView, WWKEmotionCategoryButton;
@protocol WWKEmotionPanelDelegate;

@interface WWKEmotionPanel : UIView <WWKEmotionSinglePageViewDelegate, UIScrollViewDelegate, WWKCustomEmotionPageViewDelegate, WWFavoritesProxyObserverDelegate>
{
    UIPageControl *pageControl;
    _Bool _bSetup;
    NSMutableArray *pageViewCache_;
    UIButton *sendButton_;
    WWKEmotionCategoryButton *userAddEmotionButton_;
    WWKEmotionCategoryButton *QQEmotionButton_;
    NSMutableArray *presetEmotionButtonArray_;
    UIScrollView *bottomScrollView_;
    UIView *sendLeftSeperatorView_;
    UIView *bottomScrollViewTopSeperator_;
    struct map<long, bool, std::__1::less<long>, std::__1::allocator<std::__1::pair<const long, bool>>> allocMap_;
    struct WWFavoritesProxyObserver *_mFavProxyObserver;
    _Bool _hasToolBar;
    _Bool _sendButtonEnable;
    _Bool _hasAddition;
    id <WWKEmotionPanelDelegate> _delegate;
    UIScrollView *_scrollView;
    unsigned long long _presetEmotionPageCount;
    unsigned long long _customEmotionPageCount;
    unsigned long long _QQEmotionPageCount;
}

+ (double)emotionKeyboardHeightWithHasToolBar:(_Bool)arg1;
@property(nonatomic) unsigned long long QQEmotionPageCount; // @synthesize QQEmotionPageCount=_QQEmotionPageCount;
@property(nonatomic) unsigned long long customEmotionPageCount; // @synthesize customEmotionPageCount=_customEmotionPageCount;
@property(nonatomic) unsigned long long presetEmotionPageCount; // @synthesize presetEmotionPageCount=_presetEmotionPageCount;
@property(nonatomic) _Bool hasAddition; // @synthesize hasAddition=_hasAddition;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) _Bool sendButtonEnable; // @synthesize sendButtonEnable=_sendButtonEnable;
@property(nonatomic) __weak id <WWKEmotionPanelDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool hasToolBar; // @synthesize hasToolBar=_hasToolBar;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)orientChange:(id)arg1;
- (void)p_onClickedPresetEmotion:(id)arg1;
- (void)p_onClickUserAddEmotion:(id)arg1;
- (void)p_onClickQQEmotion:(id)arg1;
- (void)p_updatePageControll:(int)arg1;
- (void)p_sendPressed:(id)arg1;
- (void)customEmotionPageView:(id)arg1 didClickMessageEmotion:(id)arg2;
- (void)customEmotionPageViewdidClickAddFromAlbum:(id)arg1;
- (void)emotionView:(id)arg1 didSelectedEmotion:(id)arg2 isDelete:(_Bool)arg3;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)layoutSubviews;
- (void)OnCollectionEmotionChanged;
@property(nonatomic) _Bool sendButtonHidden;
- (void)setHidden:(_Bool)arg1;
- (void)p_setup;
- (void)dealloc;
- (long long)p_presetGroupCount;
- (long long)p_resetQQEmotionPageCount;
- (long long)p_resetPresetPageCount;
- (long long)p_resetCustomPageCount;
- (long long)p_totalPageCount;
- (void)p_initPageViewAtIndex:(long long)arg1;
- (void)setup;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

