//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSMapTable;

@interface WWKFont : NSObject
{
    NSArray *_managedViews;
    NSMapTable *_managedViewsFontMapping;
}

@property(retain, nonatomic) NSMapTable *managedViewsFontMapping; // @synthesize managedViewsFontMapping=_managedViewsFontMapping;
@property(retain, nonatomic) NSArray *managedViews; // @synthesize managedViews=_managedViews;
- (void).cxx_destruct;
- (id)italicSystemFontOfSize:(double)arg1;
- (id)boldSystemFontOfSize:(double)arg1;
- (id)systemFontOfSize:(double)arg1;
- (id)fontWithName:(id)arg1 size:(double)arg2;
- (double)adjustFontSize:(double)arg1 level:(long long)arg2;
- (double)adjustFontSize:(double)arg1;
- (void)dynamicFontDidChange:(id)arg1;
- (void)updateManagedViews;
- (void)updateManageView:(id)arg1;
- (void)addManagedView:(id)arg1;
- (void)awakeFromNib;
- (void)dealloc;

@end

