//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSURLProtocol.h>

@class ASIFormDataRequest;

@interface WWKGmailProxyUrlProtocol : NSURLProtocol
{
    _Bool _isUseProxy;
    ASIFormDataRequest *_req;
}

+ (id)canonicalRequestForRequest:(id)arg1;
+ (_Bool)canInitWithRequest:(id)arg1;
+ (id)shareInstance;
+ (void)load;
@property(retain, nonatomic) ASIFormDataRequest *req; // @synthesize req=_req;
@property(nonatomic) _Bool isUseProxy; // @synthesize isUseProxy=_isUseProxy;
- (void).cxx_destruct;
- (void)stopLoading;
- (void)startLoading;

@end

