//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIColor;

@interface WWKHighlightBorderButton : UIButton
{
    UIColor *_borderNormalColor;
    UIColor *_borderHighlightColor;
}

@property(retain, nonatomic) UIColor *borderHighlightColor; // @synthesize borderHighlightColor=_borderHighlightColor;
@property(retain, nonatomic) UIColor *borderNormalColor; // @synthesize borderNormalColor=_borderNormalColor;
- (void).cxx_destruct;
- (void)setHighlighted:(_Bool)arg1;

@end

