//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WWKJSApiHelper : NSObject
{
}

+ (void)transferQYHUserId:(vector_36fe4106)arg1 qyhDepartmentId:(vector_36fe4106)arg2 callback:(const Callback_84be18aa *)arg3;

@end

