//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIImageView, UILabel;

@interface WWKLoginConnectTipViewController : UIViewController
{
    int _deviceType;
    UIImageView *_deviceIcon;
    UILabel *_statusLabel;
}

@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(retain, nonatomic) UIImageView *deviceIcon; // @synthesize deviceIcon=_deviceIcon;
@property(nonatomic) int deviceType; // @synthesize deviceType=_deviceType;
- (void).cxx_destruct;
- (void)show;
- (void)viewDidLoad;

@end

