//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIImageView, UILabel;

@interface WWKMailAttachmentButton : UIButton
{
    UIImageView *_attachmentImageView;
    UILabel *_attachmentNumberLabel;
}

@property(retain, nonatomic) UILabel *attachmentNumberLabel; // @synthesize attachmentNumberLabel=_attachmentNumberLabel;
@property(retain, nonatomic) UIImageView *attachmentImageView; // @synthesize attachmentImageView=_attachmentImageView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)updateAppearence;
- (void)setSelected:(_Bool)arg1;
- (void)setAttachmentsNumber:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

