//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKSimpleTableViewCell.h"

@class UIButton, UIImageView, UILabel, WWKAvatarImageView;

@interface WWKMeInfoCell : WWKSimpleTableViewCell
{
    _Bool _suppInfo;
    UILabel *_nameLabel;
    UILabel *_jobLabel;
    UILabel *_subNameLabel;
    WWKAvatarImageView *_headImageView;
    UIImageView *_supplementIcon;
    UILabel *_unrealNameLabel;
    UIButton *_qrCodeImageView;
}

@property(retain, nonatomic) UIButton *qrCodeImageView; // @synthesize qrCodeImageView=_qrCodeImageView;
@property(retain, nonatomic) UILabel *unrealNameLabel; // @synthesize unrealNameLabel=_unrealNameLabel;
@property(retain, nonatomic) UIImageView *supplementIcon; // @synthesize supplementIcon=_supplementIcon;
@property(retain, nonatomic) WWKAvatarImageView *headImageView; // @synthesize headImageView=_headImageView;
@property(retain, nonatomic) UILabel *subNameLabel; // @synthesize subNameLabel=_subNameLabel;
@property(retain, nonatomic) UILabel *jobLabel; // @synthesize jobLabel=_jobLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) _Bool suppInfo; // @synthesize suppInfo=_suppInfo;
- (void).cxx_destruct;
- (void)onDidClickQrCodeButton;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutLabelWithAvatarSize:(double)arg1;
- (struct CGSize)layoutContentWithWidth:(double)arg1;
- (void)layoutSubviews;
- (void)setUser:(const scoped_refptr_e1f85e48 *)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

