//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;

@interface WWKMeAppCommentFooter : UIView
{
    CDUnknownBlockType _contactBlock;
    CDUnknownBlockType _appStoreBlock;
    double _contentHeight;
    UIButton *_contactButton;
    UIButton *_commentButton;
    UIView *_containerView;
}

@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIButton *commentButton; // @synthesize commentButton=_commentButton;
@property(retain, nonatomic) UIButton *contactButton; // @synthesize contactButton=_contactButton;
@property(nonatomic) double contentHeight; // @synthesize contentHeight=_contentHeight;
@property(copy, nonatomic) CDUnknownBlockType appStoreBlock; // @synthesize appStoreBlock=_appStoreBlock;
@property(copy, nonatomic) CDUnknownBlockType contactBlock; // @synthesize contactBlock=_contactBlock;
- (void).cxx_destruct;
- (void)p_didClickContact:(id)arg1;
- (void)p_didClickComment:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

