//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UIButton, UITableView, UIView, WWKManageBottomBar, WWKManageHeaderView;

@interface WWKManageContactsController : UIViewController <UIGestureRecognizerDelegate, UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
{
    vector_89e6321f _selectedUserList;
    vector_89e6321f _oriUserList;
    scoped_refptr_85c18dd7 _currentDepartment;
    WWKManageHeaderView *_headerView;
    WWKManageBottomBar *_bottomBar;
    UIButton *_closeButton;
    UIView *_popBgView;
    UIView *_dimmingView;
    double _translateY;
    UITableView *_tableView;
    NSMutableArray *_dataSource;
    scoped_refptr_e5ef77f6 _originalData;
}

@property(nonatomic) scoped_refptr_e5ef77f6 originalData; // @synthesize originalData=_originalData;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)updateBottomBarTitle;
- (__wrap_iter_e55d6076)iteratorWithUser:(const scoped_refptr_e1f85e48 *)arg1;
- (_Bool)isUserSelected:(const scoped_refptr_e1f85e48 *)arg1;
- (void)deSelectUser:(const scoped_refptr_e1f85e48 *)arg1;
- (void)selectUser:(const scoped_refptr_e1f85e48 *)arg1;
- (void)reverseSelectUser:(const scoped_refptr_e1f85e48 *)arg1;
- (void)didClickInviteButton;
- (void)deSelectAllUsers;
- (void)selectAllUsers;
- (void)cancelNavigationItemPressed;
- (void)didClickBackgroundView;
- (void)dismissWithAnimated;
- (_Bool)isSelectAllCellWithIndexPath:(id)arg1;
- (_Bool)isAllUserSelected;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)handlePanGesture:(id)arg1;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)show;
- (void)viewWillLayoutSubviews;
- (void)initSubViews;
- (void)uniqueUserToOriUserList:(const scoped_refptr_e1f85e48 *)arg1;
- (void)initDataSource;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithDepartmentsData:(const scoped_refptr_e5ef77f6 *)arg1 currentDepartment:(const scoped_refptr_85c18dd7 *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

