//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "WWKSearchCorpEditCellDelegate-Protocol.h"
#import "WWKSearchCorpMobileCellDelegate-Protocol.h"

@class NSMutableArray, NSString, UIActivityIndicatorView;

@interface WWKNewValidatePhoneController : UITableViewController <WWKSearchCorpEditCellDelegate, WWKSearchCorpMobileCellDelegate>
{
    UIActivityIndicatorView *_indicatorView;
    _Bool _beginLogin;
    _Bool _isMailAddr;
    NSMutableArray *_dataSource;
    _Bool _buttonEnable;
    _Bool hasReportPhone;
    _Bool _showCancel;
    long long _type;
}

@property(nonatomic) _Bool showCancel; // @synthesize showCancel=_showCancel;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)onKeybordDidShow;
- (void)p_endHandleNextWithDelay:(double)arg1;
- (void)p_beginHandleNext;
- (void)p_setButtonLoading:(_Bool)arg1;
- (void)p_updateButton;
- (void)p_updateErrorMsg:(id)arg1;
- (void)p_setButtonEnable:(_Bool)arg1;
- (void)p_pushToVerifyCodeController:(id)arg1 isMailAddr:(_Bool)arg2;
- (void)onTextFieldDidEndEdit:(id)arg1 cell:(id)arg2;
- (void)onTextFieldDidBeginEdit:(id)arg1 cell:(id)arg2;
- (void)onTextFieldDidChange:(id)arg1 cell:(id)arg2;
- (void)mobileCell:(id)arg1 textFieldEndEdit:(id)arg2;
- (void)mobileCell:(id)arg1 textFieldBeginEdit:(id)arg2;
- (void)mobileCellDataChange:(id)arg1 countryCode:(id)arg2 mobile:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)handleNext;
- (void)onTap:(id)arg1;
- (void)setupSubviews;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)dismiss;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

