//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKCommonSearchController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSString;

@interface WWKOrganizationSearchController : WWKCommonSearchController <UITableViewDelegate, UITableViewDataSource>
{
    vector_89e6321f search_user_list_;
    struct vector<std::__1::pair<scoped_refptr<model::Department>, std::__1::vector<std::__1::pair<int, int>, std::__1::allocator<std::__1::pair<int, int>>>>, std::__1::allocator<std::__1::pair<scoped_refptr<model::Department>, std::__1::vector<std::__1::pair<int, int>, std::__1::allocator<std::__1::pair<int, int>>>>>> search_department_vector_;
    unsigned long long _source;
}

@property(nonatomic) unsigned long long source; // @synthesize source=_source;
- (id).cxx_construct;
- (void).cxx_destruct;
- (_Bool)isSearchDepartmentSection:(long long)arg1;
- (_Bool)isSearchUserSection:(long long)arg1;
- (_Bool)isSearchNetworkSection:(long long)arg1;
- (long long)numberOfRowsInSection:(long long)arg1 inTableView:(id)arg2;
- (id)contentsSearchDisplayController;
- (_Bool)isSeparatorCell:(id)arg1;
- (_Bool)showNetworkSearchCell;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)needRefreshData;
- (void)clearData;
- (void)searchBar:(id)arg1 searchTextDidChange:(id)arg2;
- (id)initWithSearchBar:(id)arg1 contentsController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

