//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView, UILabel, WWKProgressIndicator;
@protocol WWKPreViewFileImageViewDelegate;

@interface WWKPreViewFileImageView : UIView
{
    UIImageView *_imagePlaceHolder;
    UILabel *_imageSizeLabel;
    UIView *_downLoadingView;
    WWKProgressIndicator *_progressIndicator;
    UIButton *_stopButton;
    UIButton *_startButton;
    id <WWKPreViewFileImageViewDelegate> _delegate;
}

@property(nonatomic) __weak id <WWKPreViewFileImageViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIButton *startButton; // @synthesize startButton=_startButton;
@property(retain, nonatomic) UIButton *stopButton; // @synthesize stopButton=_stopButton;
@property(retain, nonatomic) WWKProgressIndicator *progressIndicator; // @synthesize progressIndicator=_progressIndicator;
@property(retain, nonatomic) UIView *downLoadingView; // @synthesize downLoadingView=_downLoadingView;
@property(retain, nonatomic) UILabel *imageSizeLabel; // @synthesize imageSizeLabel=_imageSizeLabel;
@property(retain, nonatomic) UIImageView *imagePlaceHolder; // @synthesize imagePlaceHolder=_imagePlaceHolder;
- (void).cxx_destruct;
- (void)stopDownloadDidClick:(id)arg1;
- (void)layoutSubviews;
- (void)initSubviews;
- (id)init;

@end

