//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView, UILabel, WWKProgressIndicator;

@interface WWKPreViewDocView : UIView
{
    UIImageView *_iconView;
    UILabel *_fileNameLabel;
    UILabel *_sizeLabel;
    UILabel *_fileDesLabel;
    UIButton *_actionButton;
    UILabel *_hintLabel;
    UIView *_downloadingView;
    UILabel *_downloadStateLabel;
    WWKProgressIndicator *_progressIndicator;
    UIButton *_commentBtn;
    UIView *_previewCommandView;
    UIButton *_previewCommandButton;
    UILabel *_previewCommandLabel;
}

@property(nonatomic) __weak UILabel *previewCommandLabel; // @synthesize previewCommandLabel=_previewCommandLabel;
@property(nonatomic) __weak UIButton *previewCommandButton; // @synthesize previewCommandButton=_previewCommandButton;
@property(nonatomic) __weak UIView *previewCommandView; // @synthesize previewCommandView=_previewCommandView;
@property(nonatomic) __weak UIButton *commentBtn; // @synthesize commentBtn=_commentBtn;
@property(retain, nonatomic) WWKProgressIndicator *progressIndicator; // @synthesize progressIndicator=_progressIndicator;
@property(retain, nonatomic) UILabel *downloadStateLabel; // @synthesize downloadStateLabel=_downloadStateLabel;
@property(retain, nonatomic) UIView *downloadingView; // @synthesize downloadingView=_downloadingView;
@property(retain, nonatomic) UILabel *hintLabel; // @synthesize hintLabel=_hintLabel;
@property(retain, nonatomic) UIButton *actionButton; // @synthesize actionButton=_actionButton;
@property(retain, nonatomic) UILabel *fileDesLabel; // @synthesize fileDesLabel=_fileDesLabel;
@property(retain, nonatomic) UILabel *sizeLabel; // @synthesize sizeLabel=_sizeLabel;
@property(retain, nonatomic) UILabel *fileNameLabel; // @synthesize fileNameLabel=_fileNameLabel;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
- (void).cxx_destruct;
- (void)stopDownloadDidClick:(id)arg1;
- (void)actionButtonDidRelease:(id)arg1;
- (void)actionButtonDidPress:(id)arg1;

@end

