//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKBaseMessageCell.h"

@class UIButton, UIImageView, UILabel, UIView, WWKPcOnlineWrapper;

@interface WWKPcOnlineTipsView : WWKBaseMessageCell
{
    UIImageView *_pcIconView;
    UILabel *_titleLabel;
    UIImageView *_noDisturbView;
    UIView *_seperatorView;
    UIButton *_pcOnlineContainer;
    UILabel *_todoTitleLabel;
    UIView *_seperatorViewMid;
    UIImageView *_todoIconView;
    UIView *_redPointView;
    UIButton *_todoContainer;
    WWKPcOnlineWrapper *_dataWrapper;
}

- (void).cxx_destruct;
- (void)todoClick;
- (void)pcOnlineClick;
- (void)layoutSubviews;
- (struct CGSize)p_layoutSubViewsWithLimitWidth:(double)arg1;
- (double)p_getPcIconViewHeight;
- (double)p_getPcIconViewLeftMargin;
- (void)p_updateUI;
- (double)getHeightWithLimitWidth:(double)arg1;
- (void)setDataWrapper:(id)arg1;
- (void)initSubViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

