//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface WWKReadmailCalendarHeader : UIView
{
    UIImageView *_imageArrowView;
    UIImageView *_imageViewIcon;
    UILabel *_title;
    UILabel *_desc;
    UIView *_separateLine;
    struct Calendar _calendar;
}

@property(retain, nonatomic) UIView *separateLine; // @synthesize separateLine=_separateLine;
@property(retain, nonatomic) UILabel *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) UILabel *title; // @synthesize title=_title;
@property(retain, nonatomic) UIImageView *imageViewIcon; // @synthesize imageViewIcon=_imageViewIcon;
@property(retain, nonatomic) UIImageView *imageArrowView; // @synthesize imageArrowView=_imageArrowView;
@property(nonatomic) struct Calendar calendar; // @synthesize calendar=_calendar;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)awakeFromNib;

@end

