//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "FOXEventDateTimePickerDelegate-Protocol.h"
#import "RemindServiceProxyObserverDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WWKRemindDetailViewControllerDelegate-Protocol.h"
#import "WWKRemindEditCellDelegate-Protocol.h"
#import "wwkRemindDetailTableViewDelegate-Protocol.h"

@class MZFormSheetController, NSDate, NSString, WWKRemindDetailTableView;
@protocol WWKRemindDetailViewControllerDelegate;

@interface WWKRemindDetailViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, wwkRemindDetailTableViewDelegate, FOXEventDateTimePickerDelegate, WWKRemindEditCellDelegate, RemindServiceProxyObserverDelegate, WWKRemindDetailViewControllerDelegate>
{
    long long _mode;
    scoped_refptr_d8d52c3a _remind;
    scoped_refptr_c1fa851d _message;
    NSString *_from;
    NSDate *_selectDate;
    struct RemindServiceProxyObserver *_proxyRemindServiceObserver;
    MZFormSheetController *_formSheet;
    id <WWKRemindDetailViewControllerDelegate> _delegate;
    WWKRemindDetailTableView *_tableView;
}

@property(retain, nonatomic) WWKRemindDetailTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <WWKRemindDetailViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)updateRemindComplete:(const scoped_refptr_d8d52c3a *)arg1;
- (void)onNotifyUpdateRemind:(const list_a029dffc *)arg1;
- (void)onNotifyDeleteRemind:(const list_a029dffc *)arg1;
- (void)onNotifyAddRemind:(const list_a029dffc *)arg1;
- (void)didDateSelected:(id)arg1 dateTime:(id)arg2;
- (void)updateFrameWithHeight:(float)arg1;
- (void)updateFrameWithNumOfCells:(long long)arg1 andCtrl:(id)arg2;
- (void)textViewDidChange:(id)arg1;
- (void)p_hideHud:(id)arg1;
- (id)p_showHudWithMode:(long long)arg1 text:(id)arg2;
- (void)p_tableViewDidTap:(id)arg1;
- (void)p_rightEditBarItemClick;
- (void)p_leftEditCancelItemClick;
- (void)p_rightEditCompleteBarItemClick;
- (void)p_rightAddCompleteBarItemClick;
- (void)p_leftBarItemClick;
- (void)p_getFromString;
- (void)p_initNavigation;
- (void)wwkRemindDetailTableViewDidEndTouch;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)setEditCellFirstResponder;
- (void)setRemind:(const scoped_refptr_d8d52c3a *)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (id)initWithEditMode:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

