//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface WWKReadAnnouncementFooterView : UIView
{
    vector_0ac3ee2b _attachMents;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (struct CGSize)p_layoutSubViewsWithLimitWidth:(double)arg1;
- (double)getHeightWithLimitWidth:(double)arg1;
- (void)setAttachList:(const vector_0ac3ee2b *)arg1;
- (void)layoutSubviews;
- (void)updateSubViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

