//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKMessageMedia.h"

@class NSMutableArray, NSString;

@interface WWKSurveyCardItem : WWKMessageMedia
{
    unsigned int _itemId;
    NSString *_title;
    long long _mode;
    NSMutableArray *_buttons;
}

@property(retain, nonatomic) NSMutableArray *buttons; // @synthesize buttons=_buttons;
@property(nonatomic) long long mode; // @synthesize mode=_mode;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) unsigned int itemId; // @synthesize itemId=_itemId;
- (void).cxx_destruct;

@end

