//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WWKTodoDetailItem : NSObject
{
    unsigned long long _type;
    struct CGSize _cachedSize;
    struct Follower _follower;
}

@property(nonatomic) struct CGSize cachedSize; // @synthesize cachedSize=_cachedSize;
@property(nonatomic) struct Follower follower; // @synthesize follower=_follower;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithType:(unsigned long long)arg1;

@end

