//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextView.h>

@class NSAttributedString, UILabel, UIResponder, UIView;

@interface WWKTextView : UITextView
{
    UILabel *_attributedPlaceholderLabel;
    _Bool _isMannalScroll;
    _Bool _isResigning;
    _Bool _hidesCursor;
    UIResponder *_overrideNextResponder;
    UIView *_topAccessoryView;
}

@property(retain, nonatomic) UIView *topAccessoryView; // @synthesize topAccessoryView=_topAccessoryView;
@property(nonatomic) _Bool hidesCursor; // @synthesize hidesCursor=_hidesCursor;
@property(nonatomic) _Bool isResigning; // @synthesize isResigning=_isResigning;
@property(nonatomic) _Bool isMannalScroll; // @synthesize isMannalScroll=_isMannalScroll;
@property(nonatomic) __weak UIResponder *overrideNextResponder; // @synthesize overrideNextResponder=_overrideNextResponder;
- (void).cxx_destruct;
- (id)textStorage;
- (void)layoutSubviews;
- (void)textViewDidChange:(id)arg1;
- (void)updateAttributedPlaceholder;
@property(copy, nonatomic) NSAttributedString *attributedPlaceholderText;
- (void)setAttributedText:(id)arg1;
- (void)setText:(id)arg1;
- (void)setContentOffset:(struct CGPoint)arg1;
- (struct CGRect)caretRectForPosition:(id)arg1;
- (struct CGPoint)p_getCursorPosition;
- (double)getTextHeightWithLineCount:(unsigned long long)arg1;
- (double)getLineHeight;
- (double)p_getSingleLineHeight;
- (_Bool)p_pasteAttributeStringFromPasteBoard;
- (void)p_copyAttributeStringToPasteBoard:(struct _NSRange)arg1;
- (void)deleteBackward;
- (void)paste:(id)arg1;
- (void)cut:(id)arg1;
- (void)copy:(id)arg1;
- (unsigned long long)countingTextViewLines;
- (struct CGSize)getMeasureSizeWithSize:(struct CGSize)arg1;
- (_Bool)becomeFirstResponder;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (id)nextResponder;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 textContainer:(id)arg2;
- (id)textStorageIOS70;
- (void)replaceCharactersInRange:(struct _NSRange)arg1 withAttributedText:(id)arg2;
- (void)orig_replaceCharactersInRange:(struct _NSRange)arg1 withAttributedText:(id)arg2;

@end

