//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class QMUILabel, UIImageView, WWKMessageCloudDisk;

@interface WWKYunpanMessageCommentInfoView : UIView
{
    QMUILabel *_mInfoView;
    UIImageView *_mImgView;
    WWKMessageCloudDisk *_mCloudMsg;
}

@property(retain, nonatomic) WWKMessageCloudDisk *mCloudMsg; // @synthesize mCloudMsg=_mCloudMsg;
@property(retain, nonatomic) UIImageView *mImgView; // @synthesize mImgView=_mImgView;
@property(retain, nonatomic) QMUILabel *mInfoView; // @synthesize mInfoView=_mInfoView;
- (void).cxx_destruct;
- (void)updateWithMsg:(id)arg1;
- (void)layoutSubviews;
- (void)initSubViews;
- (id)init;

@end

