//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class CALayer, UILabel;

@interface WWMarketAppProviderHeaderCell : UITableViewCell
{
    CALayer *_topSepBarLayer;
    UILabel *_mainLbl;
}

@property(retain, nonatomic) UILabel *mainLbl; // @synthesize mainLbl=_mainLbl;
@property(retain, nonatomic) CALayer *topSepBarLayer; // @synthesize topSepBarLayer=_topSepBarLayer;
- (void).cxx_destruct;
- (double)p_layoutForHeightWithParentWidth:(double)arg1;
- (void)p_doInit;
- (double)cellHeightWithParentWidth:(double)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

