//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface WWMarketAppScoreView : UIView
{
    double _scoreValue;
    UILabel *_scoreLbl;
}

@property(retain, nonatomic) UILabel *scoreLbl; // @synthesize scoreLbl=_scoreLbl;
@property(nonatomic) double scoreValue; // @synthesize scoreValue=_scoreValue;
- (void).cxx_destruct;
- (struct CGSize)p_layout:(struct CGSize)arg1;
- (void)p_doInit;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

