//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKTableViewController.h"

@class NSArray, NSMutableDictionary, NSSet, UIView, WWKCommonEmptyView;

@interface WWMarketAllCommentListController : WWKTableViewController
{
    shared_ptr_4d8cf9e1 _rcmdAppPtr;
    shared_ptr_39f023b2 _usrCommentListPtr;
    _Bool _isMeasuringCellHeight;
    int _commentOffset;
    NSArray *_secArr;
    NSArray *_commentRowArr;
    NSSet *_showAllCmtIdSet;
    NSMutableDictionary *_commentIdCellHeightDic;
    UIView *_loadingBoardView;
    WWKCommonEmptyView *_loadingProgressView;
}

@property(retain, nonatomic) WWKCommonEmptyView *loadingProgressView; // @synthesize loadingProgressView=_loadingProgressView;
@property(retain, nonatomic) UIView *loadingBoardView; // @synthesize loadingBoardView=_loadingBoardView;
@property(nonatomic) int commentOffset; // @synthesize commentOffset=_commentOffset;
@property(retain, nonatomic) NSMutableDictionary *commentIdCellHeightDic; // @synthesize commentIdCellHeightDic=_commentIdCellHeightDic;
@property(nonatomic) _Bool isMeasuringCellHeight; // @synthesize isMeasuringCellHeight=_isMeasuringCellHeight;
@property(retain, nonatomic) NSSet *showAllCmtIdSet; // @synthesize showAllCmtIdSet=_showAllCmtIdSet;
@property(retain, nonatomic) NSArray *commentRowArr; // @synthesize commentRowArr=_commentRowArr;
@property(retain, nonatomic) NSArray *secArr; // @synthesize secArr=_secArr;
- (id).cxx_construct;
- (void).cxx_destruct;
- (unsigned long long)p_commentCellTypeWithRowNumber:(long long)arg1;
- (unsigned long long)p_secTypeWithSecNumber:(long long)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)p_commentIDAtIndexPath:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (void)onCell_viewSingleCommentWithCommentId:(long long)arg1;
- (void)setWidthUserCommentList:(shared_ptr_39f023b2)arg1 appInfo:(shared_ptr_4d8cf9e1)arg2;
- (void)p_buildTableDataSource;
- (void)p_refreshTable;
- (void)p_setupFooterRefresh:(_Bool)arg1;
- (void)p_fetchCommentList;
- (void)p_removeNoti;
- (void)noti_commentStateChanged;
- (void)noti_appStateChanged;
- (void)p_registNoti;
- (void)dealloc;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)btn_clickComment;
- (void)p_updateBarButtonItems;
- (void)p_updateLoadingType:(unsigned long long)arg1 withErrorMsg:(id)arg2;
- (void)p_doInitUI;
- (void)p_doInitLogic;
- (id)backButtonTitle;
- (id)init;

@end

