//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIActivityIndicatorView, UILabel, UIView;

@interface WWMyFileLoadMoreView : UIButton
{
    _Bool _isEnd;
    _Bool _isLoading;
    UILabel *_loadTextLabel;
    CDUnknownBlockType _refreshingBlock;
    UIView *_seperatorView;
    UIActivityIndicatorView *_activityIndicator;
    UIView *_contentView;
}

@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(retain, nonatomic) UIView *seperatorView; // @synthesize seperatorView=_seperatorView;
@property(copy, nonatomic) CDUnknownBlockType refreshingBlock; // @synthesize refreshingBlock=_refreshingBlock;
@property(retain, nonatomic) UILabel *loadTextLabel; // @synthesize loadTextLabel=_loadTextLabel;
- (void).cxx_destruct;
- (void)dismiss:(_Bool)arg1;
- (void)show;
- (void)endLoading;
- (void)showLoading:(id)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)updateFont;
- (void)clickHandler:(id)arg1;
- (void)layoutSubviews;
- (void)initComponents;
- (id)initWithBlock:(CDUnknownBlockType)arg1 height:(float)arg2;

@end

