//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class UIView, WWCMROCRMaskView;
@protocol WWOCRProcBaseDelegate;

@interface WWOCRProcBase : NSObject
{
    _Bool _pauseProcessing;
    id <WWOCRProcBaseDelegate> _processDelegate;
    WWCMROCRMaskView *_weakOCRMaskView;
    UIView *_weakCameraRenderView;
}

@property(nonatomic) __weak UIView *weakCameraRenderView; // @synthesize weakCameraRenderView=_weakCameraRenderView;
@property(nonatomic) __weak WWCMROCRMaskView *weakOCRMaskView; // @synthesize weakOCRMaskView=_weakOCRMaskView;
@property(nonatomic) _Bool pauseProcessing; // @synthesize pauseProcessing=_pauseProcessing;
@property(nonatomic) __weak id <WWOCRProcBaseDelegate> processDelegate; // @synthesize processDelegate=_processDelegate;
- (void).cxx_destruct;
- (void)genScanResultFromSampleBuffer:(struct opaqueCMSampleBuffer *)arg1 completed:(CDUnknownBlockType)arg2;
- (id)genScanResultFromSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (void)processCaptureOutPut:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;

@end

