//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSMutableDictionary, UILocalNotification;

@interface WWPvMergePushManager : NSObject
{
    _Bool _mRepeatPush;
    NSMutableDictionary *_mCachedInvite;
    NSMutableArray *_mCachedMisCall;
    UILocalNotification *_mRepeatPushNoti;
    long long _mRepeatPushTimes;
}

+ (id)shareInstance;
@property(nonatomic) long long mRepeatPushTimes; // @synthesize mRepeatPushTimes=_mRepeatPushTimes;
@property(nonatomic) _Bool mRepeatPush; // @synthesize mRepeatPush=_mRepeatPush;
@property(retain, nonatomic) UILocalNotification *mRepeatPushNoti; // @synthesize mRepeatPushNoti=_mRepeatPushNoti;
@property(retain, nonatomic) NSMutableArray *mCachedMisCall; // @synthesize mCachedMisCall=_mCachedMisCall;
@property(retain, nonatomic) NSMutableDictionary *mCachedInvite; // @synthesize mCachedInvite=_mCachedInvite;
- (void).cxx_destruct;
- (void)handleNotificationAction:(id)arg1 withUserInfo:(id)arg2;
- (void)stopReapeatLocalPush:(_Bool)arg1;
- (void)startDelayLocalPush:(id)arg1;
- (void)startReapeatLocalPush:(id)arg1;
- (void)reapeatLocalPush:(id)arg1;
- (void)afterUnLockPutLocalPush;
- (void)stopDetectLockScreen;
- (void)startDetectLockScreen;
- (_Bool)isAppisForeground;
- (void)clearInviteNotifications;
- (void)clearMissNotifications;
- (void)cancelInviteNotification:(id)arg1;
- (id)getInviteNotificationContent:(id)arg1 invitor:(unsigned long long)arg2 inviteType:(int)arg3;
- (_Bool)isPushNotificationOpen;
- (void)presentLocalMissCallNotification:(id)arg1 content:(id)arg2 converId:(long long)arg3 senderId:(long long)arg4 cancelInvite:(_Bool)arg5;
- (void)presentLocalInviteNotification:(id)arg1 invitor:(unsigned long long)arg2 inviteType:(int)arg3;
- (void)handlePushKitWithUserInfo:(id)arg1;
- (void)onCloseTalk;
- (void)onAppBecomeActive;
- (void)clearNotifications;
- (id)init;

@end

