//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface WWRedEnvTextContainer : UIView
{
    _Bool _highlight;
    UIView *_mChildView;
    double _mBorderWidth;
}

@property(nonatomic) double mBorderWidth; // @synthesize mBorderWidth=_mBorderWidth;
@property(retain, nonatomic) UIView *mChildView; // @synthesize mChildView=_mChildView;
@property(nonatomic) _Bool highlight; // @synthesize highlight=_highlight;
- (void).cxx_destruct;
- (void)resetBackgroundColor;
- (void)showHightState:(_Bool)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)showErrorState:(_Bool)arg1;
- (void)layoutSubviews;
- (void)initUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

