//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel, WWKAvatarImageView, WWRedEnvItilRankListMeCell, WWRedEnvTagView;

@interface WWRedEnvRankListHeader : UIView
{
    struct GetItilHongBaoRankingListItem _rankInfo;
    UIView *_backgroundView;
    WWKAvatarImageView *_avatarView;
    WWRedEnvTagView *_tagView;
    UILabel *_nameLabel;
    UILabel *_subTitleLabel;
    UILabel *_moneyNumLabel;
    UILabel *_moneyUnitLabel;
    WWRedEnvItilRankListMeCell *_myRankCell;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)layoutSubViewsWithWidth:(double)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (_Bool)shouldShowMeInfo;
- (struct ItilHongBaoRankItem)topInfo;
- (void)setRankInfoItem:(const struct GetItilHongBaoRankingListItem *)arg1;
- (void)initSubViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

