//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWRedEnvMakeRedEnvBaseViewController.h"

#import "WWRedEnvSwitchBarDelegate-Protocol.h"
#import "WWRedEnvelopesContainerSubViewDelegate-Protocol.h"
#import "WWRedEnvelopesMakeEnvelopesViewDelegate-Protocol.h"

@class NSString, WWRedEnvSwitchBar, WWRedEnvelopesMakeEnvelopesView;

@interface WWRedEnvMakeGroupRedEnvViewController : WWRedEnvMakeRedEnvBaseViewController <WWRedEnvelopesContainerSubViewDelegate, WWRedEnvelopesMakeEnvelopesViewDelegate, WWRedEnvSwitchBarDelegate>
{
    WWRedEnvSwitchBar *_mSwitchBar;
    WWRedEnvelopesMakeEnvelopesView *_mRandomRedEnvView;
    WWRedEnvelopesMakeEnvelopesView *_mIncentiveRedEnvView;
}

@property(retain, nonatomic) WWRedEnvelopesMakeEnvelopesView *mIncentiveRedEnvView; // @synthesize mIncentiveRedEnvView=_mIncentiveRedEnvView;
@property(retain, nonatomic) WWRedEnvelopesMakeEnvelopesView *mRandomRedEnvView; // @synthesize mRandomRedEnvView=_mRandomRedEnvView;
@property(retain, nonatomic) WWRedEnvSwitchBar *mSwitchBar; // @synthesize mSwitchBar=_mSwitchBar;
- (void).cxx_destruct;
- (void)wwRedEnvSwitchBar:(id)arg1 didSelectIndex:(unsigned long long)arg2;
- (void)wwRedEnvelopesMakeEnvelopesViewCloseSelf;
- (id)wwRedEnvelopesContainerSubViewParentController;
- (id)genMakeView:(int)arg1;
- (void)onShowMakeViewAtIndex:(long long)arg1 bIsViewDidLoad:(_Bool)arg2;
- (id)getCurrSelectMakeView;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithConv:(scoped_refptr_fd92d7bf)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

