//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWYunPanListCellConfig.h"

@class NSString;

@interface WWYunPanListFileCellConfig : WWYunPanListCellConfig
{
    _Bool _uploading;
    NSString *_creator;
    NSString *_time;
    double _size;
    double _currentSize;
    NSString *_suffix;
}

+ (id)initFileWithtitle:(id)arg1 suffix:(id)arg2 creator:(id)arg3 size:(double)arg4 cloudObject:(id)arg5 time:(id)arg6;
@property(retain, nonatomic) NSString *suffix; // @synthesize suffix=_suffix;
@property(nonatomic) double currentSize; // @synthesize currentSize=_currentSize;
@property(nonatomic) double size; // @synthesize size=_size;
@property(nonatomic) _Bool uploading; // @synthesize uploading=_uploading;
@property(retain, nonatomic) NSString *time; // @synthesize time=_time;
@property(retain, nonatomic) NSString *creator; // @synthesize creator=_creator;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long commandCount;

@end

