//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSString;

@interface WXCCallogDataItem : NSObject
{
    NSString *_showCallTime;
    unsigned int _roomID;
    unsigned int _cardLocalJumpType;
    unsigned long long _dataType;
    unsigned long long _storeid;
    unsigned long long _vid;
    NSString *_phoneNumber;
    unsigned long long _inviteVid;
    NSString *_inviteNumber;
    NSMutableArray *_multiMemberList;
    NSString *_groupID;
    unsigned long long _roomKey;
    unsigned long long _callType;
    long long _callTime;
    long long _callDuration;
    NSString *_cardTitleStr;
    NSString *_cardDetailStr;
    NSString *_cardUrlStr;
}

@property(nonatomic) unsigned int cardLocalJumpType; // @synthesize cardLocalJumpType=_cardLocalJumpType;
@property(copy, nonatomic) NSString *cardUrlStr; // @synthesize cardUrlStr=_cardUrlStr;
@property(copy, nonatomic) NSString *cardDetailStr; // @synthesize cardDetailStr=_cardDetailStr;
@property(copy, nonatomic) NSString *cardTitleStr; // @synthesize cardTitleStr=_cardTitleStr;
@property(nonatomic) long long callDuration; // @synthesize callDuration=_callDuration;
@property(nonatomic) long long callTime; // @synthesize callTime=_callTime;
@property(nonatomic) unsigned long long callType; // @synthesize callType=_callType;
@property(nonatomic) unsigned long long roomKey; // @synthesize roomKey=_roomKey;
@property(nonatomic) unsigned int roomID; // @synthesize roomID=_roomID;
@property(copy, nonatomic) NSString *groupID; // @synthesize groupID=_groupID;
@property(retain, nonatomic) NSMutableArray *multiMemberList; // @synthesize multiMemberList=_multiMemberList;
@property(copy, nonatomic) NSString *inviteNumber; // @synthesize inviteNumber=_inviteNumber;
@property(nonatomic) unsigned long long inviteVid; // @synthesize inviteVid=_inviteVid;
@property(copy, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(nonatomic) unsigned long long vid; // @synthesize vid=_vid;
@property(nonatomic) unsigned long long storeid; // @synthesize storeid=_storeid;
@property(nonatomic) unsigned long long dataType; // @synthesize dataType=_dataType;
- (void).cxx_destruct;
- (_Bool)isMultiPstnInCall;
- (id)getInvitePhoneNumber;
- (id)durationDescription;
- (id)dialTypeDescription;
- (id)showCallTime;

@end

