//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel, UIView;

@interface WXCCalllogTableViewCell : UITableViewCell
{
    UIImageView *_leftTopImageView;
    UILabel *_titleTailLabel;
    UILabel *_subTitleLabel;
    UIView *_separator;
    UIImageView *_multiIconView;
    _Bool _isMultiTalk;
    unsigned long long _storeid;
}

@property(nonatomic) unsigned long long storeid; // @synthesize storeid=_storeid;
@property(nonatomic) _Bool isMultiTalk; // @synthesize isMultiTalk=_isMultiTalk;
- (void).cxx_destruct;
- (id)getAttributedString:(id)arg1 withFlagType:(unsigned long long)arg2;
- (void)configLeftTopLabel:(id)arg1 withFlagType:(unsigned long long)arg2;
- (void)configLeftIconImageView:(unsigned long long)arg1;
- (void)configLeftTopTailLabel:(id)arg1 withFlagType:(unsigned long long)arg2;
- (void)configRightTopLable:(id)arg1;
- (void)configSecondRowText:(id)arg1;
- (void)configSepera;
- (void)configMultiIconView;
- (void)configAccessoryView:(unsigned long long)arg1;
- (void)configSubView;
- (void)doLayoutSubViews;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)addAccessoryViewTarget:(id)arg1 action:(SEL)arg2;
- (void)configWithTitleText:(id)arg1 topTailText:(id)arg2 detailText:(id)arg3 rightText:(id)arg4 iconType:(unsigned long long)arg5;
- (void)layoutSubviews;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

