//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MWXCMService.h"

#import "MWXCMService-Protocol.h"
#import "WXCNetWorkDelegate-Protocol.h"

@class NSMutableSet, NSString, WXCPbDSPicsInfo;

@interface WXCConfShareMgr : MWXCMService <WXCNetWorkDelegate, MWXCMService>
{
    NSString *_taskId;
    int _curScale;
    int _xPos;
    int _yPos;
    NSMutableSet *_endedConvertIDSet;
    int _sharingType;
    unsigned int _shareOwnerUuid;
    WXCPbDSPicsInfo *_sharedPicsInfo;
    NSString *_shareTopic;
    unsigned long long _docConvertId;
    unsigned long long _selfDocConvertId;
}

@property(nonatomic) unsigned long long selfDocConvertId; // @synthesize selfDocConvertId=_selfDocConvertId;
@property(nonatomic) unsigned long long docConvertId; // @synthesize docConvertId=_docConvertId;
@property(retain) NSString *shareTopic; // @synthesize shareTopic=_shareTopic;
@property(retain) WXCPbDSPicsInfo *sharedPicsInfo; // @synthesize sharedPicsInfo=_sharedPicsInfo;
@property(nonatomic) unsigned int shareOwnerUuid; // @synthesize shareOwnerUuid=_shareOwnerUuid;
@property(nonatomic) int sharingType; // @synthesize sharingType=_sharingType;
- (void).cxx_destruct;
- (id)genUnqiueId;
- (void)p_notifyShareErr:(int)arg1;
- (_Bool)p_checkIsCurrentTalkRoom:(id)arg1;
- (void)handleConferenceShareRecvConvertResultMsg:(id)arg1;
- (void)p_onReceivedNewMsgsNotify:(id)arg1;
- (void)onRespData:(id)arg1 taskId:(int)arg2 retCode:(int)arg3 retBuf:(id)arg4 backfillData:(id)arg5;
- (void)checkAndExitDocShare;
- (void)handleGroupMemberChangeInfo:(id)arg1;
- (void)handleDocShareResp:(id)arg1 retCode:(int)arg2 origReqData:(id)arg3;
- (void)resetEndedConvertIDSet;
- (void)resetDocShareInfo;
- (_Bool)checkIsScreenSharing:(unsigned int)arg1;
- (void)drawLine:(struct CGPoint)arg1 endPoint:(struct CGPoint)arg2 drawCompleted:(_Bool)arg3 page:(int)arg4;
- (void)moveToX:(int)arg1 yPos:(int)arg2 scale:(int)arg3 page:(int)arg4;
- (void)locatePage:(int)arg1;
- (void)endShare;
- (void)startShare:(id)arg1;
- (void)dealloc;
- (void)onServiceInit;
- (_Bool)checkIsInEndedConvertSet:(unsigned long long)arg1;
- (void)updateEndedConvertID:(unsigned long long)arg1;
- (void)handleOpShape_DrawLine:(id)arg1 pageIndex:(int)arg2 opUuid:(int)arg3;
- (void)handleOpShape:(id)arg1 opUuid:(int)arg2;
- (void)handleOpMove:(id)arg1;
- (void)notifyPageIndexChanged:(int)arg1;
- (void)handleOpPage:(id)arg1;
- (void)handleEndScreenShare:(id)arg1;
- (void)handleStartScreenShare:(id)arg1 fromUuid:(int)arg2;
- (void)handleEndDocShare:(id)arg1;
- (void)handleStartDocShare:(id)arg1 fromUuid:(int)arg2;
- (id)p_pbShareDocGroupInfo;
- (id)p_pbGroupIdInfo;
- (void)p_SendC2CMsgToGroup:(id)arg1 msgType:(int)arg2;
- (id)convertPicsInfo:(id)arg1;
- (void)handleShareOp:(id)arg1;
- (void)handleShareStateMsg:(id)arg1;
- (void)sendDrawLine:(struct CGPoint)arg1 endPoint:(struct CGPoint)arg2 drawCompleted:(_Bool)arg3 page:(int)arg4;
- (void)sendMoveToX:(int)arg1 yPos:(int)arg2 scale:(int)arg3 page:(int)arg4;
- (void)sendLocatePage:(int)arg1;
- (void)sendEndShare;
- (void)sendStartShare;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

