//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WXCFilePath : NSObject
{
}

+ (id)pathOfGlobalSubLocationDbWithOutHeader;
+ (id)pathOfGlobalSubLocationDb;
+ (id)pathOfGlobalLocationDbWithOutHeader;
+ (id)pathOfGlobalLocationDb;
+ (id)pathForContactsFile;
+ (id)pathForWWCameraOCRCache;
+ (id)pathForWWCameraMovie;
+ (id)pathForVCardRecognize;
+ (id)publicPstnPath;
+ (id)publicDbPath;
+ (_Bool)createDir:(id)arg1;
+ (id)tempPath;
+ (id)docPath;

@end

