//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPPBGeneratedMessage.h"

@class NSString;

@interface WXCPbPVMergeWWMember : WXPPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *areacode; // @dynamic areacode;
@property(nonatomic) unsigned long long convid; // @dynamic convid;
@property(nonatomic) unsigned int convtype; // @dynamic convtype;
@property(nonatomic) unsigned long long corpid; // @dynamic corpid;
@property(retain, nonatomic) NSString *corpname; // @dynamic corpname;
@property(retain, nonatomic) NSString *countrycode; // @dynamic countrycode;
@property(nonatomic) unsigned long long extensionNumber; // @dynamic extensionNumber;
@property(retain, nonatomic) NSString *headurl; // @dynamic headurl;
@property(retain, nonatomic) NSString *phonenum; // @dynamic phonenum;
@property(nonatomic) unsigned int pstnEnterTime; // @dynamic pstnEnterTime;
@property(nonatomic) int pvType; // @dynamic pvType;
@property(retain, nonatomic) NSString *username; // @dynamic username;
@property(nonatomic) unsigned long long vid; // @dynamic vid;

@end

