//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WXCServerTimeMgr : NSObject
{
    unsigned long long _serverTime;
    unsigned long long _clientTime;
    _Bool _bIsNeedRefresh;
    unsigned long long _upbackTime;
}

+ (unsigned long long)getTickCount;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
@property(nonatomic) _Bool bIsNeedRefresh; // @synthesize bIsNeedRefresh=_bIsNeedRefresh;
@property(nonatomic) unsigned long long upbackTime; // @synthesize upbackTime=_upbackTime;
- (void)setNeedRefresh;
- (long long)getTimeByMilli;
- (void)setServerTimeMillis:(unsigned long long)arg1 upsetTimeMs:(unsigned long long)arg2;
- (id)getServerOrClientTime;
- (unsigned long long)getServerTimeMillis;
- (id)init;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

