//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKCommonSearchController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WXCBottomMemberBarDelegate-Protocol.h"
#import "WXCSearchInstanceDelegate-Protocol.h"

@class NSArray, NSString, UITableView, WWFavoriteEmptyView, WWKSearchBar, WXCSearchInstance, WXCSysContactSelectViewModel, WXCSysContactViewController, WXCUnderClocker;

@interface WXCSysContactSearchLogicController : WWKCommonSearchController <WXCSearchInstanceDelegate, UITableViewDataSource, UITableViewDelegate, WXCBottomMemberBarDelegate>
{
    WXCSearchInstance *_searchInstance;
    NSArray *_searchResultArray;
    vector_89e6321f search_user_list_;
    UITableView *_weakResultTableView;
    WWKSearchBar *_weakSearchBar;
    WWFavoriteEmptyView *_emptyView;
    WXCUnderClocker *_under;
    _Bool _isForMultiSelect;
    WXCSysContactSelectViewModel *_weakSelectModel;
    WXCSysContactViewController *_weakHostController;
}

@property(nonatomic) __weak WXCSysContactViewController *weakHostController; // @synthesize weakHostController=_weakHostController;
@property(nonatomic) _Bool isForMultiSelect; // @synthesize isForMultiSelect=_isForMultiSelect;
@property(nonatomic) __weak WXCSysContactSelectViewModel *weakSelectModel; // @synthesize weakSelectModel=_weakSelectModel;
- (id).cxx_construct;
- (void).cxx_destruct;
- (scoped_refptr_e1f85e48)_convertToUserFromWXCContactAbstract;
- (void)memberBar:(id)arg1 didClickedMember:(id)arg2 atSequenceNum:(int)arg3;
- (void)_anySearchFinish;
- (void)_anySearchWithContactList:(id)arg1;
- (void)_anySearchWithUserList:(const vector_89e6321f *)arg1;
- (void)_searchDpartmentStruct:(id)arg1;
- (void)onSearchFinish:(id)arg1;
- (id)_titleForSectionHeader:(int)arg1;
- (scoped_refptr_e1f85e48)_WWUserAtIndexPath:(id)arg1;
- (id)_WXCContactAtIndexPath:(id)arg1;
- (long long)_totalRowAtSection:(int)arg1;
- (long long)_cellTypeAtIndexPath:(id)arg1;
- (id)_reuseStringAtIndexPath:(id)arg1;
- (void)_configCell:(id)arg1 SearchHintType:(long long)arg2;
- (void)_configCell:(id)arg1 WWUser:(scoped_refptr_e1f85e48)arg2;
- (void)_configCell:(id)arg1 ContactAbstract:(id)arg2;
- (void)_cascadeSelect:(id)arg1 atIndexPath:(id)arg2;
- (void)_didMultiSelectRowAtIndexPath:(id)arg1;
- (void)_didSingleSelectRowAtIndexPath:(id)arg1;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)clearData;
- (void)searchDisplayControllerDidEndSearch;
- (id)textShowedWhenNoSearchResult;
- (void)searchBar:(id)arg1 searchTextDidChange:(id)arg2;
- (void)setContactsToSearch:(id)arg1;
- (void)_setupSearchInstance;
- (void)_setupSearchDisplayController;
- (void)dealloc;
- (id)initWithSearchBar:(id)arg1 contentsController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

