//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, UILabel, UITextView;

@interface CustomViewController : UIViewController
{
    NSString *_password;
    UILabel *_name;
    UITextView *_changeLogInfo;
}

+ (void)classMethod;
@property(nonatomic) __weak UITextView *changeLogInfo; // @synthesize changeLogInfo=_changeLogInfo;
@property(nonatomic) __weak UILabel *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (void)testBlock:(CDUnknownBlockType)arg1;
- (void)showChangeLog:(id)arg1;
- (id)getMyName;
- (void)initViews;
- (void)viewDidLoad;

@end

