//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSDictionary;

@interface FMFlowLayoutView : UIView
{
    unsigned long long _flowLayoutOptions;
    NSDictionary *_flowLayoutAttributes;
    struct UIEdgeInsets _flowLayoutEdgeInsets;
}

@property(copy, nonatomic) NSDictionary *flowLayoutAttributes; // @synthesize flowLayoutAttributes=_flowLayoutAttributes;
@property(nonatomic) unsigned long long flowLayoutOptions; // @synthesize flowLayoutOptions=_flowLayoutOptions;
@property(nonatomic) struct UIEdgeInsets flowLayoutEdgeInsets; // @synthesize flowLayoutEdgeInsets=_flowLayoutEdgeInsets;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

