//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FMOCRAdjustView, UIImageView;

@interface FMOCRMagnifierView : UIView
{
    UIImageView *_viewToMagnify;
    FMOCRAdjustView *_adjustView;
    unsigned long long _lastPointIndex;
    struct CGPoint _touchPoint;
}

@property(nonatomic) unsigned long long lastPointIndex; // @synthesize lastPointIndex=_lastPointIndex;
@property(nonatomic) __weak FMOCRAdjustView *adjustView; // @synthesize adjustView=_adjustView;
@property(nonatomic, setter=setTouchPoint:) struct CGPoint touchPoint; // @synthesize touchPoint=_touchPoint;
@property(nonatomic) __weak UIImageView *viewToMagnify; // @synthesize viewToMagnify=_viewToMagnify;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (id)init;

@end

