//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSMutableArray;

@interface FMOCRToolBarView : UIView
{
    NSArray *_toolbarButtons;
    NSMutableArray *_separatorLayers;
}

@property(readonly, copy, nonatomic) NSMutableArray *separatorLayers; // @synthesize separatorLayers=_separatorLayers;
@property(retain, nonatomic) NSArray *toolbarButtons; // @synthesize toolbarButtons=_toolbarButtons;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

