//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class FSCalendar, FSCalendarCollectionView, FSCalendarHeaderLayout, NSString;

@interface FSCalendarHeaderView : UIView <UICollectionViewDataSource, UICollectionViewDelegate>
{
    _Bool _scrollEnabled;
    _Bool _needsAdjustingViewFrame;
    _Bool _needsAdjustingMonthPosition;
    FSCalendarCollectionView *_collectionView;
    FSCalendarHeaderLayout *_collectionViewLayout;
    FSCalendar *_calendar;
    double _scrollOffset;
    long long _scrollDirection;
}

@property(nonatomic) _Bool needsAdjustingMonthPosition; // @synthesize needsAdjustingMonthPosition=_needsAdjustingMonthPosition;
@property(nonatomic) _Bool needsAdjustingViewFrame; // @synthesize needsAdjustingViewFrame=_needsAdjustingViewFrame;
@property(nonatomic) _Bool scrollEnabled; // @synthesize scrollEnabled=_scrollEnabled;
@property(nonatomic) long long scrollDirection; // @synthesize scrollDirection=_scrollDirection;
@property(nonatomic) double scrollOffset; // @synthesize scrollOffset=_scrollOffset;
@property(nonatomic) __weak FSCalendar *calendar; // @synthesize calendar=_calendar;
@property(nonatomic) __weak FSCalendarHeaderLayout *collectionViewLayout; // @synthesize collectionViewLayout=_collectionViewLayout;
@property(nonatomic) __weak FSCalendarCollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (void)configureAppearance;
- (void)configureCell:(id)arg1 atIndexPath:(id)arg2;
- (void)reloadData;
- (void)scrollToOffset:(double)arg1 animated:(_Bool)arg2;
- (void)setScrollOffset:(double)arg1 animated:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)dealloc;
- (void)layoutSubviews;
- (void)initialize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

