//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FSCalendarDelegate-Protocol.h"

@class FSCalendar, FSCalendarAppearance, NSArray, NSDate, UIColor;

@protocol FSCalendarDelegateAppearance <FSCalendarDelegate>

@optional
- (unsigned long long)calendar:(FSCalendar *)arg1 appearance:(FSCalendarAppearance *)arg2 cellShapeForDate:(NSDate *)arg3;
- (NSArray *)calendar:(FSCalendar *)arg1 appearance:(FSCalendarAppearance *)arg2 eventColorsForDate:(NSDate *)arg3;
- (UIColor *)calendar:(FSCalendar *)arg1 appearance:(FSCalendarAppearance *)arg2 eventColorForDate:(NSDate *)arg3;
- (UIColor *)calendar:(FSCalendar *)arg1 appearance:(FSCalendarAppearance *)arg2 selectionColorForDate:(NSDate *)arg3;
- (UIColor *)calendar:(FSCalendar *)arg1 appearance:(FSCalendarAppearance *)arg2 fillColorForDate:(NSDate *)arg3;
- (double)calendar:(FSCalendar *)arg1 appearance:(FSCalendarAppearance *)arg2 borderRadiusForDate:(NSDate *)arg3;
- (struct CGPoint)calendar:(FSCalendar *)arg1 appearance:(FSCalendarAppearance *)arg2 eventOffsetForDate:(NSDate *)arg3;
- (struct CGPoint)calendar:(FSCalendar *)arg1 appearance:(FSCalendarAppearance *)arg2 imageOffsetForDate:(NSDate *)arg3;
- (struct CGPoint)calendar:(FSCalendar *)arg1 appearance:(FSCalendarAppearance *)arg2 subtitleOffsetForDate:(NSDate *)arg3;
- (struct CGPoint)calendar:(FSCalendar *)arg1 appearance:(FSCalendarAppearance *)arg2 titleOffsetForDate:(NSDate *)arg3;
- (UIColor *)calendar:(FSCalendar *)arg1 appearance:(FSCalendarAppearance *)arg2 borderSelectionColorForDate:(NSDate *)arg3;
- (UIColor *)calendar:(FSCalendar *)arg1 appearance:(FSCalendarAppearance *)arg2 borderDefaultColorForDate:(NSDate *)arg3;
- (NSArray *)calendar:(FSCalendar *)arg1 appearance:(FSCalendarAppearance *)arg2 eventSelectionColorsForDate:(NSDate *)arg3;
- (NSArray *)calendar:(FSCalendar *)arg1 appearance:(FSCalendarAppearance *)arg2 eventDefaultColorsForDate:(NSDate *)arg3;
- (UIColor *)calendar:(FSCalendar *)arg1 appearance:(FSCalendarAppearance *)arg2 subtitleSelectionColorForDate:(NSDate *)arg3;
- (UIColor *)calendar:(FSCalendar *)arg1 appearance:(FSCalendarAppearance *)arg2 subtitleDefaultColorForDate:(NSDate *)arg3;
- (UIColor *)calendar:(FSCalendar *)arg1 appearance:(FSCalendarAppearance *)arg2 titleSelectionColorForDate:(NSDate *)arg3;
- (UIColor *)calendar:(FSCalendar *)arg1 appearance:(FSCalendarAppearance *)arg2 titleDefaultColorForDate:(NSDate *)arg3;
- (UIColor *)calendar:(FSCalendar *)arg1 appearance:(FSCalendarAppearance *)arg2 fillSelectionColorForDate:(NSDate *)arg3;
- (UIColor *)calendar:(FSCalendar *)arg1 appearance:(FSCalendarAppearance *)arg2 fillDefaultColorForDate:(NSDate *)arg3;
@end

