//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "IReporter-Protocol.h"

@class GYLogReportAdapter, GYOssLogCGIHelper, NSString;

@interface GYOssLogManager : NSObject <IReporter>
{
    GYOssLogCGIHelper *_oCGIHelper;
    NSString *_sid;
    GYLogReportAdapter *_reportAdapter;
    unsigned long long _appId;
    unsigned long long _authType;
    unsigned long long _platform;
    unsigned long long _vid;
    NSString *_appVersion;
    NSString *_os;
    unsigned long long _corpId;
    NSString *_imei;
    NSString *_deviceType;
    NSString *_deviceId;
    unsigned long long _channelId;
    NSString *_nickname;
}

+ (_Bool)createDirectoryAtPath:(id)arg1 error:(id *)arg2;
+ (id)sharedInstance;
@property(copy, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(nonatomic) unsigned long long channelId; // @synthesize channelId=_channelId;
@property(copy, nonatomic) NSString *deviceId; // @synthesize deviceId=_deviceId;
@property(copy, nonatomic) NSString *deviceType; // @synthesize deviceType=_deviceType;
@property(copy, nonatomic) NSString *imei; // @synthesize imei=_imei;
@property(nonatomic) unsigned long long corpId; // @synthesize corpId=_corpId;
@property(copy, nonatomic) NSString *os; // @synthesize os=_os;
@property(copy, nonatomic) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property(nonatomic) unsigned long long vid; // @synthesize vid=_vid;
@property(copy, nonatomic) NSString *sid; // @synthesize sid=_sid;
@property(nonatomic) unsigned long long platform; // @synthesize platform=_platform;
@property(nonatomic) unsigned long long authType; // @synthesize authType=_authType;
@property(nonatomic) unsigned long long appId; // @synthesize appId=_appId;
- (void).cxx_destruct;
- (long long)reportLosslessLog:(id)arg1 withFinishBlock:(CDUnknownBlockType)arg2;
- (id)compressLog:(id)arg1;
- (id)encryptLog:(id)arg1;
- (long long)report:(id)arg1 withFinishBlock:(CDUnknownBlockType)arg2;
- (void)uploadLosslessLogsWithSid:(id)arg1;
- (void)uploadLogWithSid:(id)arg1;
- (_Bool)initOssLogOptions;
- (id)init;
- (void)immediatelyLogKVWithPlatform:(unsigned long long)arg1 logID:(unsigned int)arg2 itemName:(id)arg3 value:(double)arg4 type:(id)arg5 resource:(id)arg6 httpStatus:(unsigned long long)arg7 errorCode:(unsigned long long)arg8 errorMsg:(id)arg9 info:(id)arg10;
- (void)immediatelyLogKV:(unsigned long long)arg1 logID:(unsigned int)arg2 itemName:(id)arg3 value:(double)arg4 type:(id)arg5 resource:(id)arg6 httpStatus:(unsigned long long)arg7 errorCode:(unsigned long long)arg8 errorMsg:(id)arg9 info:(id)arg10;
- (void)offlineLogKV:(unsigned int)arg1 itemName:(id)arg2 value:(double)arg3 type:(id)arg4 resource:(id)arg5 httpStatus:(unsigned long long)arg6 errorCode:(unsigned long long)arg7 errorMsg:(id)arg8 info:(id)arg9;
- (void)offlineLogKV:(unsigned int)arg1 itemName:(id)arg2 value:(double)arg3 string:(id)arg4;
- (void)logValue:(id)arg1;
- (void)offlineLogKVCardItemName:(id)arg1 cardId:(unsigned int)arg2 linkId:(unsigned int)arg3;
- (void)offlineLogKV:(unsigned int)arg1 itemName:(id)arg2 id:(unsigned long long)arg3 string:(id)arg4;
- (void)offlineLogKV:(unsigned int)arg1 itemName:(id)arg2 id:(unsigned long long)arg3 value:(double)arg4;
- (void)offlineLogKV:(unsigned int)arg1 itemName:(id)arg2 strvalue:(id)arg3;
- (void)offlineLogKV:(unsigned int)arg1 itemName:(id)arg2 value:(double)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

