//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GYCallback.h"

@interface GYUICallback : GYCallback
{
}

+ (id)callbackWithSuccess:(CDUnknownBlockType)arg1 withError:(CDUnknownBlockType)arg2;
- (void)handleComplete:(id)arg1;
- (void)handleError:(id)arg1;
- (void)handleSendData:(unsigned long long)arg1 totalWritten:(long long)arg2 totalExpectToWrite:(long long)arg3;
- (void)handleProgress:(unsigned long long)arg1 totalBytesRead:(long long)arg2 totalExpectToRead:(long long)arg3;
- (void)handleSuccess:(id)arg1;
- (void)handleBeforeSend:(id)arg1;

@end

