//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "JWeixinCallWrapperDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString, UIWebView, WKWebView, WWKWXWebViewController;

@interface JWeixinOpenAPILogicImpl : NSObject <JWeixinCallWrapperDelegate>
{
    NSMutableArray *arrValidateJWeixinURL;
    unsigned long long validateURLFailCount;
    UIWebView *_webView;
    WKWebView *_wkView;
    WWKWXWebViewController *_WXWebViewController;
    NSMutableArray *_jWeixinCallWrapperQueue;
    NSMutableDictionary *_nativeCodeHandlerRoute;
    unsigned long long _thisAppID;
}

+ (_Bool)checkJWeixinAPI:(id)arg1;
@property(nonatomic) unsigned long long thisAppID; // @synthesize thisAppID=_thisAppID;
@property(retain, nonatomic) NSMutableDictionary *nativeCodeHandlerRoute; // @synthesize nativeCodeHandlerRoute=_nativeCodeHandlerRoute;
@property(retain, nonatomic) NSMutableArray *jWeixinCallWrapperQueue; // @synthesize jWeixinCallWrapperQueue=_jWeixinCallWrapperQueue;
@property(nonatomic) __weak WWKWXWebViewController *WXWebViewController; // @synthesize WXWebViewController=_WXWebViewController;
@property(nonatomic) __weak WKWebView *wkView; // @synthesize wkView=_wkView;
@property(nonatomic) __weak UIWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;
- (id)onNativeCodeCallFinished:(id)arg1 withResult:(id)arg2;
- (void)sendEventToJSBridgeWKAsync:(id)arg1 params:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)sendEventToJSBridge:(id)arg1 params:(id)arg2;
- (id)getAuthorizedWebMonitorEvents:(id)arg1 withCurEvent:(id)arg2;
- (void)setValidateJWeixinURL:(id)arg1;
- (long long)checkJWeixinURLValidation:(id)arg1;
- (_Bool)checkJWeixinBlackListHost:(id)arg1;
- (id)callJSFromNativeCodeToJWeixinJSBridgeWKSync:(id)arg1 withMsgType:(id)arg2 withMsgID:(id)arg3;
- (void)callJSFromNativeCodeToJWeixinJSBridgeWKAsync:(id)arg1 withMsgType:(id)arg2 withMsgID:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)callJSFromNativeCodeToJWeixinJSBridgeWKAsync:(id)arg1 withMsgType:(id)arg2 withMsgID:(id)arg3;
- (id)callJSFromNativeCodeToJWeixinJSBridge:(id)arg1 withMsgType:(id)arg2 withMsgID:(id)arg3;
- (id)createJWeixinCallWapperWithFN:(id)arg1 withParams:(id)arg2 withCallbackID:(id)arg3;
- (void)interceptHistoryBackWKAsync:(CDUnknownBlockType)arg1;
- (_Bool)interceptHistoryBack;
- (_Bool)canHandleJsCallInNativeCode:(id)arg1;
- (void)nativeCodeCall:(id)arg1 withParams:(id)arg2 withCallbackID:(id)arg3;
- (id)sendMessageToJSBridge:(id)arg1;
- (_Bool)isJSBridgeLoaded;
- (void)injectJSBridge;
- (_Bool)interceptJWeixinCall:(id)arg1;
- (_Bool)check3rdAPIListOfJSBridge:(id)arg1;
- (void)dispatchJSAPICall:(id)arg1;
- (void)changeKernel:(id)arg1;
- (id)fetchLatestInjectJSSDKInterfaceLayerJS;
- (void)tryInjectJsBridgeWKAsync;
- (void)tryInjectJsBridge;
- (void)dealloc;
- (id)initWithWVC:(id)arg1 withAppID:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

