//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray;

@interface M80ImageFingerprint : NSObject
{
    NSArray *_lines;
}

+ (id)fingerprint:(id)arg1;
@property(retain, nonatomic) NSArray *lines; // @synthesize lines=_lines;
- (void).cxx_destruct;
- (void)cal:(id)arg1;

@end

