//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MWXCMService.h"

#import "MWXCMService-Protocol.h"

@class NSMutableDictionary, NSString;

@interface MWXCMLazyExtensionAgent : MWXCMService <MWXCMService>
{
    NSMutableDictionary *m_dicExtensions;
}

- (void).cxx_destruct;
- (void)ensureLazyListenerInitedForExtension:(id)arg1 withSelector:(SEL)arg2;
- (void)registerLazyListener:(Class)arg1 onExtension:(id)arg2;
- (void)addListener:(Class)arg1 toDic:(id)arg2 forMethods:(struct objc_method_description *)arg3 methodCount:(unsigned int)arg4;
- (void)dealloc;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

