//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDate.h>

@interface NSDate (ShortName)
+ (id)spaceFeedCommentName:(id)arg1;
+ (id)postTimeNameWithTimeUInt:(long long)arg1;
+ (id)eatFoodShortNameWithTimeUInt:(long long)arg1;
+ (id)cardShortNameWithTimeUInt:(long long)arg1;
+ (id)redenvDetailNameByTime:(id)arg1;
+ (id)workLogDetailWithTimeUInt:(long long)arg1;
+ (id)workLogListCellWithTimeUInt:(long long)arg1;
+ (id)workLogListTitleWithTimeUInt:(long long)arg1;
+ (id)workLogImageNamePrefixWithTimeUInt:(long long)arg1;
+ (id)flowerRedenvShortNameWithTimeUInt:(long long)arg1;
+ (id)redenvShortNameWithTimeUInt:(long long)arg1;
+ (id)applyShortNameWithDate5:(long long)arg1;
+ (id)applyShortNameWithDate4:(long long)arg1;
+ (id)applyShortNameWithDate:(long long)arg1;
+ (id)applyShortNameWithDate2:(long long)arg1;
+ (id)applyShortNameWithDate3:(long long)arg1;
+ (id)announceShortNameWithTimeUInt:(long long)arg1;
+ (id)collectionShortNameWithDate:(id)arg1;
+ (_Bool)is24HourTimeSet;
+ (id)FormatterChatShowStringByTime:(id)arg1;
+ (id)forwardMessageTimeWithDate:(id)arg1;
+ (id)forwardMessageTitleTimeWithDate:(id)arg1;
+ (id)shortNameWithTimeUInt:(long long)arg1;
- (_Bool)isDateThisWeek:(id)arg1;
- (id)dateByAddingDays:(long long)arg1;
- (id)shortName;
- (id)fullName;
@end

