//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface NSObject (XADSimpleUnarchiverDelegate)
- (void)simpleUnarchiver:(id)arg1 estimatedExtractionProgressForEntryWithDictionary:(id)arg2 fileProgress:(double)arg3 totalProgress:(double)arg4;
- (void)simpleUnarchiver:(id)arg1 extractionProgressForEntryWithDictionary:(id)arg2 fileProgress:(long long)arg3 of:(long long)arg4 totalProgress:(long long)arg5 of:(long long)arg6;
- (_Bool)extractionShouldStopForSimpleUnarchiver:(id)arg1;
- (id)simpleUnarchiver:(id)arg1 deferredReplacementPathForOriginalPath:(id)arg2 suggestedPath:(id)arg3;
- (id)simpleUnarchiver:(id)arg1 replacementPathForEntryWithDictionary:(id)arg2 originalPath:(id)arg3 suggestedPath:(id)arg4;
- (void)simpleUnarchiver:(id)arg1 didExtractEntryWithDictionary:(id)arg2 to:(id)arg3 error:(int)arg4;
- (void)simpleUnarchiver:(id)arg1 willExtractEntryWithDictionary:(id)arg2 to:(id)arg3;
- (_Bool)simpleUnarchiver:(id)arg1 shouldExtractEntryWithDictionary:(id)arg2 to:(id)arg3;
- (id)simpleUnarchiver:(id)arg1 encodingNameForXADString:(id)arg2;
- (void)simpleUnarchiverNeedsPassword:(id)arg1;
@end

