//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (XADRegex)
- (id)escapedPattern;
- (id)componentsSeparatedByPattern:(id)arg1 options:(int)arg2;
- (id)componentsSeparatedByPattern:(id)arg1;
- (id)allSubstringsCapturedByPattern:(id)arg1 options:(int)arg2;
- (id)allSubstringsCapturedByPattern:(id)arg1;
- (id)allSubstringsMatchedByPattern:(id)arg1 options:(int)arg2;
- (id)allSubstringsMatchedByPattern:(id)arg1;
- (id)substringsCapturedByPattern:(id)arg1 options:(int)arg2;
- (id)substringsCapturedByPattern:(id)arg1;
- (id)substringMatchedByPattern:(id)arg1 options:(int)arg2;
- (id)substringMatchedByPattern:(id)arg1;
- (_Bool)matchedByPattern:(id)arg1 options:(int)arg2;
- (_Bool)matchedByPattern:(id)arg1;
@end

