//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSURLConnectionDataDelegate-Protocol.h"
#import "NSURLConnectionDelegate-Protocol.h"

@class NSError, NSMutableData, NSString, NSURLConnection, NSURLRequest, NSURLResponse, QMSHTTPResponseSerializer;

@interface QMSHTTPRequestOperation : NSObject <NSURLConnectionDelegate, NSURLConnectionDataDelegate>
{
    NSURLRequest *_request;
    NSURLResponse *_response;
    NSError *_error;
    id _reponseObject;
    QMSHTTPResponseSerializer *_responseSerializer;
    NSURLConnection *_connection;
    NSMutableData *_responseData;
    CDUnknownBlockType _completionHandler;
}

@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(retain, nonatomic) NSMutableData *responseData; // @synthesize responseData=_responseData;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) QMSHTTPResponseSerializer *responseSerializer; // @synthesize responseSerializer=_responseSerializer;
@property(retain, nonatomic) id reponseObject; // @synthesize reponseObject=_reponseObject;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSURLResponse *response; // @synthesize response=_response;
@property(retain, nonatomic) NSURLRequest *request; // @synthesize request=_request;
- (void).cxx_destruct;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)finish;
- (void)cancel;
- (void)start;
- (id)initWithRequest:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

