//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "QMUIToastAnimatorDelegate-Protocol.h"

@class NSString, QMUIToastView;

@interface QMUIToastAnimator : NSObject <QMUIToastAnimatorDelegate>
{
    _Bool _isShowing;
    _Bool _isAnimating;
    QMUIToastView *_toastView;
    long long _animationType;
}

@property(nonatomic) long long animationType; // @synthesize animationType=_animationType;
@property(readonly, nonatomic) __weak QMUIToastView *toastView; // @synthesize toastView=_toastView;
- (void).cxx_destruct;
- (_Bool)isAnimating;
- (_Bool)isShowing;
- (void)hideWithCompletion:(CDUnknownBlockType)arg1;
- (void)showWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithToastView:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

