//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "QMUIZoomImageViewDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class NSString, QMUICollectionViewPagingLayout, UICollectionView, UIColor;
@protocol QMUIImagePreviewViewDelegate;

@interface QMUIImagePreviewView : UIView <QMUIZoomImageViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
{
    _Bool _isChangingCollectionViewBounds;
    unsigned long long _currentImageIndex;
    id <QMUIImagePreviewViewDelegate> _delegate;
    UICollectionView *_collectionView;
    QMUICollectionViewPagingLayout *_collectionViewLayout;
    UIColor *_loadingColor;
    double _previousIndexWhenScrolling;
}

@property(nonatomic) double previousIndexWhenScrolling; // @synthesize previousIndexWhenScrolling=_previousIndexWhenScrolling;
@property(nonatomic) _Bool isChangingCollectionViewBounds; // @synthesize isChangingCollectionViewBounds=_isChangingCollectionViewBounds;
@property(retain, nonatomic) UIColor *loadingColor; // @synthesize loadingColor=_loadingColor;
@property(readonly, nonatomic) QMUICollectionViewPagingLayout *collectionViewLayout; // @synthesize collectionViewLayout=_collectionViewLayout;
@property(readonly, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) __weak id <QMUIImagePreviewViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long currentImageIndex; // @synthesize currentImageIndex=_currentImageIndex;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)setCurrentImageIndex:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;
- (void)didInitializedWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)enabledZoomViewInZoomImageView:(id)arg1;
- (void)longPressInZoomingImageView:(id)arg1;
- (void)doubleTouchInZoomingImageView:(id)arg1 location:(struct CGPoint)arg2;
- (void)singleTouchInZoomingImageView:(id)arg1 location:(struct CGPoint)arg2;
- (void)checkIfDelegateMissing;
- (id)zoomImageViewAtIndex:(unsigned long long)arg1;
- (unsigned long long)indexForZoomImageView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

