//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableView.h>

@protocol QMUITableViewDataSource, QMUITableViewDelegate;

@interface QMUITableView : UITableView
{
}

- (_Bool)touchesShouldCancelInContentView:(id)arg1;
- (void)setTableFooterView:(id)arg1;
- (void)dealloc;
- (void)didInitialized;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2;

// Remaining properties
@property(nonatomic) __weak id <QMUITableViewDataSource> dataSource; // @dynamic dataSource;
@property(nonatomic) __weak id <QMUITableViewDelegate> delegate; // @dynamic delegate;

@end

