//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSString, UIActivityIndicatorView, UIFont, UIImageView, UILabel, UIView;
@protocol QMUINavigationTitleViewDelegate;

@interface QMUINavigationTitleView : UIControl
{
    _Bool _active;
    _Bool _autoUpdateTitleColor;
    _Bool _needsLoadingView;
    _Bool _loadingViewHidden;
    _Bool _needsLoadingPlaceholderSpace;
    _Bool _needsAccessoryPlaceholderSpace;
    _Bool _accessoryViewAnimating;
    id <QMUINavigationTitleViewDelegate> _delegate;
    long long _style;
    UILabel *_titleLabel;
    NSString *_title;
    UILabel *_subtitleLabel;
    NSString *_subtitle;
    UIFont *_horizontalTitleFont;
    UIFont *_horizontalSubtitleFont;
    UIFont *_verticalTitleFont;
    UIFont *_verticalSubtitleFont;
    UIActivityIndicatorView *_loadingView;
    double _loadingViewMarginRight;
    UIView *_accessoryView;
    long long _accessoryType;
    UIImageView *_accessoryTypeView;
    struct CGSize _loadingViewSize;
    struct CGPoint _accessoryViewOffset;
    struct CGSize _titleLabelSize;
    struct CGSize _subtitleLabelSize;
    struct UIEdgeInsets _titleEdgeInsets;
    struct UIEdgeInsets _subtitleEdgeInsets;
}

+ (void)setDefaultAppearance;
+ (void)initialize;
@property(retain, nonatomic) UIImageView *accessoryTypeView; // @synthesize accessoryTypeView=_accessoryTypeView;
@property(nonatomic) struct CGSize subtitleLabelSize; // @synthesize subtitleLabelSize=_subtitleLabelSize;
@property(nonatomic) struct CGSize titleLabelSize; // @synthesize titleLabelSize=_titleLabelSize;
@property(nonatomic) _Bool accessoryViewAnimating; // @synthesize accessoryViewAnimating=_accessoryViewAnimating;
@property(nonatomic) _Bool needsAccessoryPlaceholderSpace; // @synthesize needsAccessoryPlaceholderSpace=_needsAccessoryPlaceholderSpace;
@property(nonatomic) struct CGPoint accessoryViewOffset; // @synthesize accessoryViewOffset=_accessoryViewOffset;
@property(nonatomic) long long accessoryType; // @synthesize accessoryType=_accessoryType;
@property(retain, nonatomic) UIView *accessoryView; // @synthesize accessoryView=_accessoryView;
@property(nonatomic) double loadingViewMarginRight; // @synthesize loadingViewMarginRight=_loadingViewMarginRight;
@property(nonatomic) struct CGSize loadingViewSize; // @synthesize loadingViewSize=_loadingViewSize;
@property(nonatomic) _Bool needsLoadingPlaceholderSpace; // @synthesize needsLoadingPlaceholderSpace=_needsLoadingPlaceholderSpace;
@property(nonatomic) _Bool loadingViewHidden; // @synthesize loadingViewHidden=_loadingViewHidden;
@property(nonatomic) _Bool needsLoadingView; // @synthesize needsLoadingView=_needsLoadingView;
@property(readonly, nonatomic) UIActivityIndicatorView *loadingView; // @synthesize loadingView=_loadingView;
@property(nonatomic) struct UIEdgeInsets subtitleEdgeInsets; // @synthesize subtitleEdgeInsets=_subtitleEdgeInsets;
@property(nonatomic) struct UIEdgeInsets titleEdgeInsets; // @synthesize titleEdgeInsets=_titleEdgeInsets;
@property(retain, nonatomic) UIFont *verticalSubtitleFont; // @synthesize verticalSubtitleFont=_verticalSubtitleFont;
@property(retain, nonatomic) UIFont *verticalTitleFont; // @synthesize verticalTitleFont=_verticalTitleFont;
@property(retain, nonatomic) UIFont *horizontalSubtitleFont; // @synthesize horizontalSubtitleFont=_horizontalSubtitleFont;
@property(retain, nonatomic) UIFont *horizontalTitleFont; // @synthesize horizontalTitleFont=_horizontalTitleFont;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(nonatomic) _Bool autoUpdateTitleColor; // @synthesize autoUpdateTitleColor=_autoUpdateTitleColor;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
@property(nonatomic) long long style; // @synthesize style=_style;
@property(nonatomic) __weak id <QMUINavigationTitleViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)handleTouchTitleViewEvent;
- (void)setHighlighted:(_Bool)arg1;
- (void)tintColorDidChange;
- (void)setContentHorizontalAlignment:(long long)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (struct CGSize)contentSize;
- (struct UIEdgeInsets)subtitleEdgeInsetsIfShowingSubtitleLabel;
- (struct UIEdgeInsets)titleEdgeInsetsIfShowingTitleLabel;
- (struct CGSize)accessorySpacingSizeIfNeedesPlaceholder;
- (struct CGSize)accessorySpacingSize;
- (struct CGSize)loadingViewSpacingSizeIfNeedsPlaceholder;
- (struct CGSize)loadingViewSpacingSize;
- (void)updateSubtitleLabelSize;
- (void)updateTitleLabelSize;
- (void)refreshLayout;
- (id)description;
- (id)initWithStyle:(long long)arg1 frame:(struct CGRect)arg2;
- (id)initWithStyle:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

