//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"

@class QQApiObject;

@interface QQApiMessage : NSObject <NSCoding>
{
    unsigned long long _type;
    QQApiObject *_object;
}

+ (id)messageWithObject:(id)arg1 andType:(unsigned long long)arg2;
+ (id)messageWithObject:(id)arg1;
@property(retain, nonatomic) QQApiObject *object; // @synthesize object=_object;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)initWithObject:(id)arg1 andType:(unsigned long long)arg2;
- (_Bool)isAssociatedWithTask;
- (void)setAssociatedTask:(id)arg1;

@end

