//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSString;

@interface RqdCrashHandler : NSObject
{
    NSString *attachLog;
    NSArray *excludeShortNames;
    _Bool enableLastCloseRecord;
    NSArray *includeShortNames;
    _Bool _crashAccidentHappen;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
@property(nonatomic, getter=isCrashAccidentHappen) _Bool crashAccidentHappen; // @synthesize crashAccidentHappen=_crashAccidentHappen;
@property(retain, nonatomic) NSArray *includeShortNames; // @synthesize includeShortNames;
@property(retain, nonatomic) NSArray *excludeShortNames; // @synthesize excludeShortNames;
@property(nonatomic) _Bool enableLastCloseRecord; // @synthesize enableLastCloseRecord;
@property(retain, nonatomic) NSString *attachLog; // @synthesize attachLog;
- (_Bool)persistCrashToFile:(id *)arg1;
- (id)generateExpUploadObj:(id)arg1;
- (id)saveCrashData:(id)arg1;
- (_Bool)crashHapped;
- (_Bool)crashHapped:(id)arg1;
- (id)getCurrExpObj;
- (long long)getLastCrashTime;
- (void)persistLastCrashTime:(long long)arg1;
- (_Bool)hasLastCrashNeedReport;
- (void)persistLastCrashNeedReport:(_Bool)arg1;
- (_Bool)isLastCloseByCrash;
- (void)installHandler;
- (void)uninstallHandler;
- (_Bool)userMachHandler;
- (void)setUserMachHandler:(_Bool)arg1;
- (_Bool)isExpMergeUpload;
- (void)setExpMergeStrategy:(_Bool)arg1;
- (void)setExpMergeUpload:(_Bool)arg1;
- (void)registCrashListerner:(id)arg1;
- (id)init;
- (id)autorelease;
- (oneway void)release;
- (unsigned long long)retainCount;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

