//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface RSAPublicKeyWrapper : NSObject
{
}

+ (id)_filePathWithDirName:(id)arg1 andFileName:(id)arg2;
- (id)__encrypt:(id)arg1 encryptString:(id)arg2;
- (_Bool)writePublickeyToFile:(id)arg1 pubKey:(id)arg2;
- (id)encryptWithDefaultPubKey:(id)arg1;
- (id)encryptWithPubKey:(id)arg1 encryptString:(id)arg2;
- (void)dealloc;

@end

