//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface TCOpenSDKErrorUtil : NSObject
{
}

+ (id)apiResponseFromErrorCode:(int)arg1;
+ (id)apiResponse:(id)arg1;
+ (void)apiResponseConvert:(id)arg1;
+ (long long)filterURLErrorCode:(long long)arg1;
+ (id)openSDKErrorMsgForErrorCode:(int)arg1;
+ (id)openSDKErrorFromOSError:(id)arg1;
+ (id)openSDKErrorWithCommonServerCode:(int)arg1 extraInfo:(id)arg2;
+ (id)openSDKErrorWithCode:(int)arg1 extraInfo:(id)arg2;

@end

