//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSKeyedUnarchiverDelegate-Protocol.h"

@class NSString;

@interface TencentMessageParse : NSObject <NSKeyedUnarchiverDelegate>
{
}

+ (id)getReqFromUrl:(id)arg1;
+ (id)getRespFromUrl:(id)arg1;
+ (id)parseTencentMessage:(id)arg1;
- (Class)unarchiver:(id)arg1 cannotDecodeObjectOfClassName:(id)arg2 originalClasses:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

