//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DevLockTlv_base.h"

@class NSData, NSString;

@interface Tlv_0x2_AppInfo : DevLockTlv_base
{
    unsigned int dwAppId;
    unsigned int dwSubAppId;
    NSData *sLoginKey;
    NSData *sGUID;
    NSString *sAppName;
    NSString *sSdkVersion;
    NSString *sPlatform;
    NSString *sOsVersion;
}

@property(copy) NSString *sOsVersion; // @synthesize sOsVersion;
@property(copy) NSString *sPlatform; // @synthesize sPlatform;
@property(copy) NSString *sSdkVersion; // @synthesize sSdkVersion;
@property(copy) NSString *sAppName; // @synthesize sAppName;
@property(copy) NSData *sGUID; // @synthesize sGUID;
@property(copy) NSData *sLoginKey; // @synthesize sLoginKey;
@property unsigned int dwSubAppId; // @synthesize dwSubAppId;
@property unsigned int dwAppId; // @synthesize dwAppId;
- (void)dealloc;
- (int)encode:(id)arg1;

@end

