//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WebviewResourceManager : NSObject
{
    unsigned long long vid;
}

+ (id)manager;
- (_Bool)downloadFile:(struct NSString *)arg1 fileType:(id)arg2 appId:(id)arg3 completion:(CDUnknownBlockType)arg4 progress:(CDUnknownBlockType)arg5;
- (_Bool)uploadFile:(struct NSString *)arg1 completion:(CDUnknownBlockType)arg2 progress:(CDUnknownBlockType)arg3;
- (_Bool)downloadVideo:(struct NSString *)arg1 appId:(id)arg2 completion:(CDUnknownBlockType)arg3 progress:(CDUnknownBlockType)arg4;
- (_Bool)uploadVideo:(struct NSString *)arg1 completion:(CDUnknownBlockType)arg2 progress:(CDUnknownBlockType)arg3;
- (void)addLocalVideo:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)downloadVoice:(struct NSString *)arg1 appId:(id)arg2 completion:(CDUnknownBlockType)arg3 progress:(CDUnknownBlockType)arg4;
- (_Bool)downloadVoice:(struct NSString *)arg1 appId:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)uploadVoice:(struct NSString *)arg1 completion:(CDUnknownBlockType)arg2 progress:(CDUnknownBlockType)arg3;
- (_Bool)uploadVoice:(struct NSString *)arg1 completion:(CDUnknownBlockType)arg2;
- (void)addRecordResource:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)downloadImage:(struct NSString *)arg1 appId:(id)arg2 completion:(CDUnknownBlockType)arg3 progress:(CDUnknownBlockType)arg4;
- (_Bool)downloadImage:(struct NSString *)arg1 appId:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)uploadLocalImage:(struct NSString *)arg1 completion:(CDUnknownBlockType)arg2 progress:(CDUnknownBlockType)arg3;
- (_Bool)uploadLocalImage:(struct NSString *)arg1 completion:(CDUnknownBlockType)arg2;
- (void)addLocalImagesWithOriginalSize:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)addLocalImages:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)addLocalImages:(id)arg1 originalSize:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (id)getLocalPathByResourceId:(struct NSString *)arg1;
- (_Bool)setResItem:(id)arg1 byLocalId:(struct NSString *)arg2;
- (_Bool)setResItem:(id)arg1;
- (id)getResItemByServerId:(struct NSString *)arg1;
- (id)getResItemByLocalId:(struct NSString *)arg1;
- (struct NSString *)generateLocalResourceId;
- (id)getUserWebResourceRootDir;
- (id)init;

@end

