//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSData, NSString;

@interface WEWCloudDiskHelperAppMsg : NSObject
{
    NSString *_topobjectid;
    NSString *_objectid;
    NSData *_wording;
}

@property(retain, nonatomic) NSData *wording; // @synthesize wording=_wording;
@property(copy, nonatomic) NSString *objectid; // @synthesize objectid=_objectid;
@property(copy, nonatomic) NSString *topobjectid; // @synthesize topobjectid=_topobjectid;
- (void).cxx_destruct;

@end

