//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface WloginWording : NSObject
{
    NSMutableDictionary *_dict;
}

+ (id)singleton;
@property(retain, nonatomic) NSMutableDictionary *dict; // @synthesize dict=_dict;
- (id)_langDesc;
- (void)_initDict;
- (id)wording:(id)arg1;
- (void)dealloc;
- (id)init;

@end

