//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWCardWallCell.h"

@class NSMutableArray, UIButton, UILabel;

@interface WWCardWallRecommendCommentCell : WWCardWallCell
{
    NSMutableArray *buttonArr;
    UILabel *_recommentLabel;
    UIButton *_confirmButton;
}

@property(retain, nonatomic) UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) UILabel *recommentLabel; // @synthesize recommentLabel=_recommentLabel;
- (void).cxx_destruct;
- (void)addTagDidClick:(id)arg1;
- (void)confirmRecommend:(id)arg1;
- (void)choose:(id)arg1;
- (struct CGSize)layoutSubviewsWithWidth:(double)arg1;
- (void)updateConfirmButtonState;
- (void)setDefaultTagList:(const vector_36fe4106 *)arg1;
- (void)initSubViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

