//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@interface WWCMROCRScanLoadingViewLayer : CALayer
{
    double _progress;
}

+ (_Bool)needsDisplayForKey:(id)arg1;
@property(nonatomic) double progress; // @synthesize progress=_progress;
- (void)drawInContext:(struct CGContext *)arg1;

@end

