//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WWCMROCRHelpler : NSObject
{
}

+ (id)p_vcardInfoFromVCardDic:(id)arg1;
+ (void)reconizeCardWithCardImageHanWang:(id)arg1 completed:(CDUnknownBlockType)arg2;
+ (void)reconizeCardWithCardImageWithSaomiaoWang:(id)arg1 completed:(CDUnknownBlockType)arg2;
+ (id)p_vcardImgProcessFromSrcImg:(id)arg1;

@end

