//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSData, NSMutableArray, NSMutableDictionary, WWFavoriteId;

@interface WWFavoritesItem : NSObject
{
    struct unique_ptr<collection::protocol::pb::WWCollectionItem, std::__1::default_delete<collection::protocol::pb::WWCollectionItem>> _srcItem;
    unsigned int _localid;
    unsigned int _messageType;
    unsigned long long _senderID;
    unsigned long long _convID;
    unsigned long long _favTime;
    NSMutableArray *_dataList;
    unsigned long long _favType;
    NSData *_originalData;
    unsigned long long _svrStoreId;
    NSMutableDictionary *_mSearchUserIdToNameDic;
    NSMutableDictionary *_mSearchUserIdToEngNameDic;
    NSMutableDictionary *_mSearchConvIdToNameDic;
    NSMutableDictionary *_mOldMailIdToFavmapDic;
    NSMutableDictionary *_mOldDownUrlToFavmapDic;
}

@property(retain, nonatomic) NSMutableDictionary *mOldDownUrlToFavmapDic; // @synthesize mOldDownUrlToFavmapDic=_mOldDownUrlToFavmapDic;
@property(retain, nonatomic) NSMutableDictionary *mOldMailIdToFavmapDic; // @synthesize mOldMailIdToFavmapDic=_mOldMailIdToFavmapDic;
@property(retain, nonatomic) NSMutableDictionary *mSearchConvIdToNameDic; // @synthesize mSearchConvIdToNameDic=_mSearchConvIdToNameDic;
@property(retain, nonatomic) NSMutableDictionary *mSearchUserIdToEngNameDic; // @synthesize mSearchUserIdToEngNameDic=_mSearchUserIdToEngNameDic;
@property(retain, nonatomic) NSMutableDictionary *mSearchUserIdToNameDic; // @synthesize mSearchUserIdToNameDic=_mSearchUserIdToNameDic;
@property(nonatomic) unsigned long long svrStoreId; // @synthesize svrStoreId=_svrStoreId;
@property(nonatomic) unsigned int messageType; // @synthesize messageType=_messageType;
@property(retain, nonatomic) NSData *originalData; // @synthesize originalData=_originalData;
@property(nonatomic) unsigned long long favType; // @synthesize favType=_favType;
@property(retain, nonatomic) NSMutableArray *dataList; // @synthesize dataList=_dataList;
@property(nonatomic) unsigned long long favTime; // @synthesize favTime=_favTime;
@property(nonatomic) unsigned long long convID; // @synthesize convID=_convID;
@property(nonatomic) unsigned long long senderID; // @synthesize senderID=_senderID;
@property(nonatomic) unsigned int localid; // @synthesize localid=_localid;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)getFavmapAeskeyFromOldMailId:(id)arg1;
- (int)getFavmapContentTypeFromOldDownUrl:(id)arg1;
- (int)getFavmapContentTypeFromOldMailId:(id)arg1;
- (id)getNewDownUrlFromOldDownUrl:(id)arg1;
- (id)getNewMailIdFromOldMailId:(id)arg1;
- (struct WWCollectionItem)collectionItem;
- (_Bool)hasDownloadFavData;
- (struct WWFavMap *)getFavmapFromOldDownUrl:(id)arg1;
- (struct WWFavMap *)getFavmapFromOldMailId:(id)arg1;
- (void)setDownloadFavmapData:(const struct WWFavMapList *)arg1 oriMsgType:(int)arg2;
- (void)setSearchData:(const struct WWCollectionExtraSearchData *)arg1;
- (void)setCacheConvName:(id)arg1 convID:(unsigned long long)arg2;
- (id)getCacheConvNameByConvId:(unsigned long long)arg1;
- (id)getCacheUserEngNameByUserId:(unsigned long long)arg1;
- (id)getCacheUserNameByUserId:(unsigned long long)arg1;
@property(readonly, nonatomic) WWFavoriteId *favId;
- (id)castClassItemData:(id)arg1 itemDataClass:(Class)arg2;
- (id)getFirstFavoritesItemData;
- (id)initWithCollectionItem:(struct WWCollectionItem)arg1;

@end

