//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCopying-Protocol.h"

@interface WWFavoriteId : NSObject <NSCopying>
{
    unsigned int _favoriteLocalId;
    unsigned int _selfLocalId;
    unsigned long long _msgId;
}

@property(nonatomic) unsigned int selfLocalId; // @synthesize selfLocalId=_selfLocalId;
@property(nonatomic) unsigned int favoriteLocalId; // @synthesize favoriteLocalId=_favoriteLocalId;
@property(nonatomic) unsigned long long msgId; // @synthesize msgId=_msgId;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

