//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWFavoritesDetailBaseCellView.h"

#import "ABNewPersonViewControllerDelegate-Protocol.h"
#import "ABPeoplePickerNavigationControllerDelegate-Protocol.h"
#import "WWKInteractiveLabelDelegate-Protocol.h"

@class NSString, UINavigationController, WWKInteractiveLabel;

@interface WWFavoritesDetailTxtCellView : WWFavoritesDetailBaseCellView <WWKInteractiveLabelDelegate, ABPeoplePickerNavigationControllerDelegate, ABNewPersonViewControllerDelegate>
{
    WWKInteractiveLabel *_txtContentLabel;
    NSString *_phoneToAddAddressBook;
    UINavigationController *_weakNav;
}

@property(nonatomic) __weak UINavigationController *weakNav; // @synthesize weakNav=_weakNav;
@property(retain, nonatomic) NSString *phoneToAddAddressBook; // @synthesize phoneToAddAddressBook=_phoneToAddAddressBook;
@property(retain, nonatomic) WWKInteractiveLabel *txtContentLabel; // @synthesize txtContentLabel=_txtContentLabel;
- (void).cxx_destruct;
- (void)copyItemClicked:(id)arg1;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)longTap:(id)arg1;
- (void)_handleAddContactWithPersonID:(int)arg1;
- (void)_createNewPersonWithPhoneStr:(id)arg1;
- (_Bool)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2 property:(int)arg3 identifier:(int)arg4;
- (_Bool)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2;
- (void)peoplePickerNavigationController:(id)arg1 didSelectPerson:(void *)arg2;
- (void)peoplePickerNavigationControllerDidCancel:(id)arg1;
- (void)newPersonViewController:(id)arg1 didCompleteWithNewPerson:(void *)arg2;
- (void)_addToExsitWithPhoneStr:(id)arg1;
- (void)_handleTelClick:(id)arg1;
- (void)didClickMailAddress:(id)arg1;
- (void)interactiveLabel:(id)arg1 didTouchContext:(id)arg2 boundingRects:(id)arg3;
- (void)layoutSubviews;
- (void)initContentView;
- (void)initContentData;
- (double)getFavDetailCellHeight;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

