//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSAttributedString, NSString, UIButton, UIColor;

@interface WWKAlertAction : NSObject
{
    _Bool _enabled;
    _Bool _checked;
    _Bool _hasDivider;
    _Bool _callsHandlerImmediately;
    _Bool _preventsAutoDismissal;
    _Bool _disablesDismissalAnimation;
    NSString *_title;
    NSString *_subTitle;
    long long _style;
    UIButton *_button;
    UIColor *_titleColor;
    NSAttributedString *_attriTitle;
    CDUnknownBlockType _handler;
    struct UIEdgeInsets _attriContentEdgeInsets;
}

+ (id)builder;
+ (id)actionWithAttributedTitle:(id)arg1 checked:(_Bool)arg2 handler:(CDUnknownBlockType)arg3;
+ (id)actionWithAttributedTitle:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (id)actionWithTitle:(id)arg1 style:(long long)arg2 checked:(_Bool)arg3 handler:(CDUnknownBlockType)arg4;
+ (id)actionWithTitle:(id)arg1 subTitle:(id)arg2 style:(long long)arg3 handler:(CDUnknownBlockType)arg4;
+ (id)actionWithTitle:(id)arg1 style:(long long)arg2 handler:(CDUnknownBlockType)arg3;
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(copy, nonatomic) NSAttributedString *attriTitle; // @synthesize attriTitle=_attriTitle;
@property(copy, nonatomic) UIColor *titleColor; // @synthesize titleColor=_titleColor;
@property(nonatomic) struct UIEdgeInsets attriContentEdgeInsets; // @synthesize attriContentEdgeInsets=_attriContentEdgeInsets;
@property(nonatomic) _Bool disablesDismissalAnimation; // @synthesize disablesDismissalAnimation=_disablesDismissalAnimation;
@property(nonatomic) _Bool preventsAutoDismissal; // @synthesize preventsAutoDismissal=_preventsAutoDismissal;
@property(nonatomic) _Bool callsHandlerImmediately; // @synthesize callsHandlerImmediately=_callsHandlerImmediately;
@property(nonatomic) _Bool hasDivider; // @synthesize hasDivider=_hasDivider;
@property(nonatomic, getter=isChecked) _Bool checked; // @synthesize checked=_checked;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) __weak UIButton *button; // @synthesize button=_button;
@property(nonatomic) long long style; // @synthesize style=_style;
@property(copy, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)performAction;

@end

