//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "NotificationProxyObserverDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "VcardServiceProxyObserverDelegate-Protocol.h"
#import "WWKFindMoreAppsControllerDelegate-Protocol.h"
#import "WWKWorkLogViewControllerDelegate-Protocol.h"
#import "WWKWorkLogWebViewControllerDelegate-Protocol.h"

@class NSMutableArray, NSString, UICollectionView, UITableView, UIView, WWFavoriteEmptyView, WWKApplicationPageDataSource;

@interface WWKApplicationPageController : UIViewController <UITableViewDataSource, UITableViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, NotificationProxyObserverDelegate, VcardServiceProxyObserverDelegate, WWKFindMoreAppsControllerDelegate, WWKWorkLogViewControllerDelegate, WWKWorkLogWebViewControllerDelegate>
{
    WWKApplicationPageDataSource *_dataManage;
    struct unique_ptr<NotificationProxyObserver, std::__1::default_delete<NotificationProxyObserver>> push_notification_observer;
    struct VcardServiceProxyObserver *_vcardServiceProxyObserver;
    _Bool _showFolderApp;
    _Bool _isEditMode;
    _Bool _collectionMode;
    CDUnknownBlockType _showOrHideAppBlock;
    NSMutableArray *_appSections;
    UITableView *_tableView;
    UIView *_topBackgroundView;
    UIView *_bottomBackgroundView;
    UICollectionView *_collectionView;
    WWFavoriteEmptyView *_emptyView;
}

@property(retain, nonatomic) WWFavoriteEmptyView *emptyView; // @synthesize emptyView=_emptyView;
@property(nonatomic) _Bool collectionMode; // @synthesize collectionMode=_collectionMode;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) UIView *bottomBackgroundView; // @synthesize bottomBackgroundView=_bottomBackgroundView;
@property(retain, nonatomic) UIView *topBackgroundView; // @synthesize topBackgroundView=_topBackgroundView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSMutableArray *appSections; // @synthesize appSections=_appSections;
@property(nonatomic) _Bool isEditMode; // @synthesize isEditMode=_isEditMode;
@property(copy, nonatomic) CDUnknownBlockType showOrHideAppBlock; // @synthesize showOrHideAppBlock=_showOrHideAppBlock;
@property(nonatomic) _Bool showFolderApp; // @synthesize showFolderApp=_showFolderApp;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onReloadData;
- (void)vieController:(id)arg1 didPublishWorklog:(const struct JournalEntry *)arg2;
- (void)onWorkLogWebViewController:(id)arg1 didPublishWorkLogTemplate:(const struct JournalEntry *)arg2;
- (void)WorkLogViewController:(id)arg1 didPublishPost:(const struct JournalEntry *)arg2;
- (void)OnVCardUnReadCountChanged:(unsigned int)arg1 withOldCount:(unsigned int)arg2;
- (void)OnVCardTotalCountChanged:(unsigned int)arg1 withOldCount:(unsigned int)arg2;
- (_Bool)findHasShowAddThirdAppEntry;
- (SEL)getActionWithIndexPath:(id)arg1;
- (_Bool)shouldShowEditMode;
- (void)updateCardWallCell;
- (id)getIndexPath:(id)arg1 withAppId:(unsigned long long)arg2;
- (void)uploadHideAppIds;
- (void)uploadHideAppIdsByTotalApps:(id)arg1;
- (id)getAppItem:(id)arg1 withIndexPath:(id)arg2;
- (void)changeDataWithAnimate:(_Bool)arg1;
- (id)footerTextWithSection:(long long)arg1;
- (void)navigation:(id)arg1 pushToViewController:(id)arg2;
- (void)exposeRedPointReport;
- (void)checkParentCellRedPoint;
- (id)redPointKeysWithItem:(id)arg1;
- (long long)getAppSectionItemPosition:(id)arg1 withType:(long long)arg2;
- (id)getNormalStyleTableViewCellForIndexPath:(id)arg1;
- (void)notifyAppShowState:(const list_8b50c42f *)arg1;
- (void)updateUI;
- (void)onNotification:(int)arg1 source:(const struct NotificationSource *)arg2 details:(const struct NotificationDetails *)arg3;
- (void)onItemDidLongPressed:(id)arg1;
- (void)onApplicationItemDidAddInEditMode:(id)arg1;
- (void)onApplicationItemDidRemoveInEditMode:(id)arg1;
- (void)onRemoveWithIndexPath:(id)arg1;
- (void)onEditCell:(id)arg1;
- (void)onEnterAppMarket;
- (void)onEnterEditMode;
- (void)onFinish;
- (void)onAppInfoChange:(id)arg1;
- (void)onDynamicFontSizeDidChange;
- (void)onDidPushMoreAppController:(id)arg1;
- (void)onDidPushManageCorpController:(id)arg1;
- (void)onDidPushAddThirdAppController:(id)arg1;
- (void)onDidPushVirtualMoreAppController:(id)arg1;
- (void)onDidPushSystemController:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForFooterInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 trailingSwipeActionsConfigurationForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 editActionsForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)initNotifications;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)viewWillLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)updateNavigationItems;
- (void)reloadData;
- (void)createDataManager;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

