//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WWKAttendationFilterViewDelegate-Protocol.h"
#import "WWKSelectContactsViewControllerDelegate-Protocol.h"

@class CALayer, NSDate, NSMutableArray, NSString, QMUILabel, UITableView, UIView, WWKAttendancePullDownButton, WWKAttendationFilterView, WWKCommonEmptyView;

@interface WWKAttendanceListTableViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, WWKSelectContactsViewControllerDelegate, WWKAttendationFilterViewDelegate>
{
    _Bool isSample;
    _Bool isEmpty;
    _Bool hasFetchData;
    _Bool hasShowFilterPrivalige;
    vector_a024b487 selectedDepartList;
    vector_e0f2bd7e selectedStatusList;
    vector_e0f2bd7e selectedNumList;
    _Bool isLoadingFirstPage;
    long long nowRequestID;
    long long requestIDGenerator;
    int _listType;
    int _entryFilterStatus;
    NSDate *_selectedDate;
    CDUnknownBlockType _goSettingBlock;
    UITableView *_tableView;
    UIView *_headView;
    WWKAttendancePullDownButton *_filterButton;
    WWKAttendancePullDownButton *_departButton;
    CALayer *_dividerLayer;
    CALayer *_bottomLayer;
    WWKAttendationFilterView *_filterView;
    NSMutableArray *_data;
    WWKCommonEmptyView *_listEmptyView;
    WWKCommonEmptyView *_filterEmptyView;
    QMUILabel *_bottomLabel;
}

@property(retain, nonatomic) QMUILabel *bottomLabel; // @synthesize bottomLabel=_bottomLabel;
@property(retain, nonatomic) WWKCommonEmptyView *filterEmptyView; // @synthesize filterEmptyView=_filterEmptyView;
@property(retain, nonatomic) WWKCommonEmptyView *listEmptyView; // @synthesize listEmptyView=_listEmptyView;
@property(retain, nonatomic) NSMutableArray *data; // @synthesize data=_data;
@property(retain, nonatomic) WWKAttendationFilterView *filterView; // @synthesize filterView=_filterView;
@property(retain, nonatomic) CALayer *bottomLayer; // @synthesize bottomLayer=_bottomLayer;
@property(retain, nonatomic) CALayer *dividerLayer; // @synthesize dividerLayer=_dividerLayer;
@property(retain, nonatomic) WWKAttendancePullDownButton *departButton; // @synthesize departButton=_departButton;
@property(retain, nonatomic) WWKAttendancePullDownButton *filterButton; // @synthesize filterButton=_filterButton;
@property(retain, nonatomic) UIView *headView; // @synthesize headView=_headView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) int entryFilterStatus; // @synthesize entryFilterStatus=_entryFilterStatus;
@property(copy, nonatomic) CDUnknownBlockType goSettingBlock; // @synthesize goSettingBlock=_goSettingBlock;
@property(retain, nonatomic) NSDate *selectedDate; // @synthesize selectedDate=_selectedDate;
@property(nonatomic) int listType; // @synthesize listType=_listType;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)didClickCancelButtonInSelectContactsViewController:(id)arg1;
- (_Bool)canSelectDepartmentInSelectContactsViewController:(id)arg1;
- (long long)numberOfMaxSelectedContacts:(id)arg1;
- (void)selectContactsViewController:(id)arg1 didConfirmToSelectContacts:(vector_89e6321f)arg2;
- (void)selectContactsViewController:(id)arg1 didConfirmToSelectContacts:(vector_89e6321f)arg2 andDepartments:(vector_a024b487)arg3;
- (void)cancelSelect;
- (void)didSelectType:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)p_onSelectedDepartmentListChanged:(vector_a024b487)arg1;
- (void)p_ShowGuideToSetting:(id)arg1;
- (void)p_ShowWarningWithTitle:(id)arg1;
- (id)p_getStatus:(struct DayData)arg1;
- (void)p_GetListData:(_Bool)arg1;
- (void)p_UpdateFilterButtonStatus;
- (void)p_ShowFilterView:(_Bool)arg1;
- (void)p_OnClickFilterButton:(id)arg1;
- (void)p_ShowDepartmentSelectView;
- (void)p_OnClickDepartSelectButton:(id)arg1;
- (id)p_CreatePullDownButtonWithTitle:(id)arg1;
- (void)p_ShowLoadingView:(_Bool)arg1;
- (_Bool)p_IsToday;
- (void)p_updateEmptyView:(long long)arg1;
- (_Bool)p_HasFilterCondition;
- (void)p_InitEntryFilters;
- (void)scrollViewDidScroll:(id)arg1;
- (void)p_ReLayoutBottomLabel;
- (id)p_CreateBottomLabel;
- (void)p_UpdateAutoRefreshFooter:(_Bool)arg1;
- (void)p_layoutSubviews;
- (void)p_initUI;
- (void)p_setData:(id)arg1;
- (id)p_getSampleData;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithType:(int)arg1 isSample:(_Bool)arg2 isEmpty:(_Bool)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

