//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WWKApplicationPageHelper : NSObject
{
}

+ (void)openWxAppPayBillWithNavigationController:(id)arg1;
+ (_Bool)hasEntryPrivilageToAppPayBill;
+ (_Bool)isCorpOpenedPayBill;
+ (_Bool)compareAppSections:(id)arg1 withOther:(id)arg2;
+ (long long)numberOfRowsPerLine;
+ (_Bool)shouldShowAddThirdApp;
+ (_Bool)shouldShowManageCorp;
+ (void)navigation:(id)arg1 pushToViewController:(id)arg2;
+ (void)push:(id)arg1 withAppItem:(id)arg2 hideBottomBar:(_Bool)arg3;
+ (_Bool)openApiItemshouldShow:(const struct WSNewCorpAppDetail *)arg1;
+ (long long)getOpenApiOrderWithID:(unsigned long long)arg1;
+ (long long)getDefaultAppOrderWithID:(unsigned long long)arg1;
+ (id)getAppSectionsWithOpenApiApps:(id)arg1;
+ (void)sortApps:(id)arg1;
+ (struct WSNewCorpAppDetail)convertToSortCorpAppDetail:(id)arg1;

@end

