//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSAttributedString, NSMutableArray, NSString, UIColor, WWKAlertAction, WWKAlertViewController;

@interface WWKAlertController : NSObject
{
    _Bool _shouldDismissOnBackgroundViewTap;
    NSArray *_actions;
    NSString *_title;
    NSString *_message;
    NSArray *_customViews;
    long long _preferredStyle;
    long long _titleTextAlignment;
    long long _messageTextAlignment;
    long long _cancelMode;
    UIColor *_backgroundDimmingColor;
    UIColor *_actionTitleColor;
    double _preferredContentWidth;
    NSAttributedString *_attriTitle;
    NSMutableArray *_didDismissHandlers;
    WWKAlertViewController *_alertViewController;
    WWKAlertViewController *_alertViewControllerRef;
}

+ (id)alertControllers;
+ (id)_alertControllers;
+ (id)alertControllerWithAttributedTitle:(id)arg1 message:(id)arg2 preferredStyle:(long long)arg3;
+ (id)alertControllerWithTitle:(id)arg1 message:(id)arg2 preferredStyle:(long long)arg3;
+ (id)deleteAnnounceAlertControllerwithOKHandle:(CDUnknownBlockType)arg1 cancelHandle:(CDUnknownBlockType)arg2;
+ (id)guideToBindWxToFindPartner:(CDUnknownBlockType)arg1;
+ (id)weixinAppNotFoundAlertController;
+ (id)unsupportedQQQrcodeAlertController;
+ (id)unsupportedWeAppCodeAlertController;
+ (id)unsupportedWeixinQrcodeAlertController;
+ (id)networkPermissionAlertControllerWithCancelHandle:(CDUnknownBlockType)arg1;
+ (id)contactSearchNoPerssionWithOkHandle:(CDUnknownBlockType)arg1;
+ (id)alertControllerTipSureWithMessage:(id)arg1 withBtnText:(id)arg2 withOKHandle:(CDUnknownBlockType)arg3;
+ (id)alertControllerTipSureWithMessage:(id)arg1 withOKHandle:(CDUnknownBlockType)arg2;
+ (id)alertControllerTipSureWithMessage:(id)arg1;
+ (id)alertControllerTipSureWithTitle:(id)arg1;
+ (id)pvTalkMembersOverLoadedAlertControler:(long long)arg1 limitCnt:(long long)arg2;
+ (id)convMembersOverLoadedAlertController:(_Bool)arg1;
+ (id)insufficentStorageAlertController:(id)arg1;
+ (id)cameraPermissionAlertControllerWithTitle:(id)arg1;
+ (id)cameraPermissionAlertController;
+ (id)assetPermissionAlertController;
+ (id)contactPermissionAlertController;
+ (id)recordPermissionAlertControllerWithTitle:(id)arg1;
+ (id)recordPermissionAlertController;
+ (id)locationPermissionAlertControllerWithOkHandle:(CDUnknownBlockType)arg1 cancelHandle:(CDUnknownBlockType)arg2;
+ (id)locationPermissionAlertController;
@property(retain, nonatomic) WWKAlertViewController *alertViewControllerRef; // @synthesize alertViewControllerRef=_alertViewControllerRef;
@property(nonatomic) __weak WWKAlertViewController *alertViewController; // @synthesize alertViewController=_alertViewController;
@property(retain, nonatomic) NSMutableArray *didDismissHandlers; // @synthesize didDismissHandlers=_didDismissHandlers;
@property(copy, nonatomic) NSAttributedString *attriTitle; // @synthesize attriTitle=_attriTitle;
@property(nonatomic) double preferredContentWidth; // @synthesize preferredContentWidth=_preferredContentWidth;
@property(copy, nonatomic) UIColor *actionTitleColor; // @synthesize actionTitleColor=_actionTitleColor;
@property(copy, nonatomic) UIColor *backgroundDimmingColor; // @synthesize backgroundDimmingColor=_backgroundDimmingColor;
@property(nonatomic) long long cancelMode; // @synthesize cancelMode=_cancelMode;
@property(nonatomic) _Bool shouldDismissOnBackgroundViewTap; // @synthesize shouldDismissOnBackgroundViewTap=_shouldDismissOnBackgroundViewTap;
@property(nonatomic) long long messageTextAlignment; // @synthesize messageTextAlignment=_messageTextAlignment;
@property(nonatomic) long long titleTextAlignment; // @synthesize titleTextAlignment=_titleTextAlignment;
@property(nonatomic) long long preferredStyle; // @synthesize preferredStyle=_preferredStyle;
@property(retain, nonatomic) NSArray *customViews; // @synthesize customViews=_customViews;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSArray *actions; // @synthesize actions=_actions;
- (void).cxx_destruct;
- (void)presentViewController:(id)arg1;
- (void)updateAnimated:(_Bool)arg1;
- (void)layoutAnimated:(_Bool)arg1;
- (void)dismissAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dismissAnimated:(_Bool)arg1;
- (void)showAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)showAnimated:(_Bool)arg1;
- (void)buildAlertViewController;
@property(readonly, nonatomic) struct CGSize preferredContentSize;
- (void)addDidDismissHandler:(CDUnknownBlockType)arg1;
- (id)addRawCustomView:(id)arg1;
- (id)addQMUITextField;
- (id)addQMUITextViewWithInsets:(struct UIEdgeInsets)arg1;
- (id)addQMUITextView;
- (id)addTextFieldWithInsets:(struct UIEdgeInsets)arg1;
- (id)addTextField;
- (id)addCustomView:(id)arg1 insets:(struct UIEdgeInsets)arg2;
- (id)addCustomViewWithDefaultInsets:(id)arg1;
- (id)addCustomView:(id)arg1;
- (void)addSettingCancelActionPair;
- (id)addCancelAction;
- (void)addActionsFromArray:(id)arg1;
- (id)addAction:(id)arg1;
@property(readonly, nonatomic) WWKAlertAction *cancelAction;
- (void)dealloc;
- (id)initWithAttributedTitle:(id)arg1 message:(id)arg2 preferredStyle:(long long)arg3;
- (id)initWithTitle:(id)arg1 message:(id)arg2 preferredStyle:(long long)arg3;
- (id)init;

@end

