//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class WWKAddInvoiceHeaderContainer;
@protocol WWKAddInvoiceHeaderDelegate;

@interface WWKAddInvoiceHeader : UIView
{
    WWKAddInvoiceHeaderContainer *_containerView;
    id <WWKAddInvoiceHeaderDelegate> _delegate;
}

@property(nonatomic) __weak id <WWKAddInvoiceHeaderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)segmentChange:(id)arg1;
- (void)layoutSubviews;
- (struct CGSize)layoutSubViewsWithWidth:(double)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)initSubViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

