//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSArray;

@interface WWKAppCollectionSytleTableViewCell : UITableViewCell
{
    NSArray *_items;
    NSArray *_collectionCells;
}

@property(retain, nonatomic) NSArray *collectionCells; // @synthesize collectionCells=_collectionCells;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

