//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIScrollViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, UIPageControl, UIScrollView;
@protocol WWKAttachPanelDelegate;

@interface WWKAttachPanel : UIView <UIScrollViewDelegate>
{
    NSMutableArray *_itemArr;
    id <WWKAttachPanelDelegate> _delegate;
    UIScrollView *_scrollView;
    NSArray *_typeArr;
    UIPageControl *_pageCtrl;
}

@property(retain, nonatomic) UIPageControl *pageCtrl; // @synthesize pageCtrl=_pageCtrl;
@property(retain, nonatomic) NSArray *typeArr; // @synthesize typeArr=_typeArr;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak id <WWKAttachPanelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (double)p_rightOrLeftMargin;
- (void)layoutSubviews;
- (void)itemClicked:(id)arg1;
- (void)setReceiptToHighlight;
- (void)setAlertToHighlight;
- (void)resetAlertToNormal;
- (void)resetReceiptToNormal;
- (void)p_checkActiveAndNew;
- (void)p_updateItems;
- (void)p_onPageControlValueChanged:(id)arg1;
- (void)p_commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

