//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKUIWebViewController.h"

@class NSSet;
@protocol WWKApprovalUIWebViewControllerDelegate;

@interface WWKApprovalUIWebViewController : WWKUIWebViewController
{
    _Bool _fromInitOpenApi;
    _Bool _withRightBtnForList;
    int _cacheData;
    NSSet *_blacklistMenuItems;
    id <WWKApprovalUIWebViewControllerDelegate> _delegate;
}

+ (id)GetApprovalListEntranceUrl;
@property(nonatomic) int cacheData; // @synthesize cacheData=_cacheData;
@property(nonatomic) _Bool withRightBtnForList; // @synthesize withRightBtnForList=_withRightBtnForList;
@property(nonatomic) __weak id <WWKApprovalUIWebViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool fromInitOpenApi; // @synthesize fromInitOpenApi=_fromInitOpenApi;
@property(copy, nonatomic) NSSet *blacklistMenuItems; // @synthesize blacklistMenuItems=_blacklistMenuItems;
- (void).cxx_destruct;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)onWebviewJSLoadFinishedNotify:(id)arg1 withTemplateName:(id)arg2 withErrorCode:(int)arg3;
- (void)handleSessionKey:(id)arg1;
- (id)handleUserInfo:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidLoad;
- (void)onNavigationRightBtnClick;
- (id)initForOpenAPI;
- (void)loadRequest:(id)arg1;
- (id)initWithURLForApproval:(id)arg1;
- (id)initWithURL:(id)arg1 withRightBtnForList:(_Bool)arg2 rightBtnIconName:(id)arg3 delegate:(id)arg4 cacheData:(int)arg5;

@end

