//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "NotificationProxyObserverDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSString, NSTimerProxy, UITableView, WWKAttendanceWiFiInfoBottomOperationView, WWKAttendanceWiFiInfoTableHeader;
@protocol WWKAttendanceWiFiInfoTableViewControllerDelegate;

@interface WWKAttendanceWiFiInfoTableViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, NotificationProxyObserverDelegate>
{
    vector_4a9bf3c6 history_info_list_;
    struct unique_ptr<ww_attendance::WifiInfo, std::__1::default_delete<ww_attendance::WifiInfo>> current_wifi_;
    vector_4a9bf3c6 select_wifi_info_list_;
    struct unique_ptr<NotificationProxyObserver, std::__1::default_delete<NotificationProxyObserver>> _notification_observer;
    id <WWKAttendanceWiFiInfoTableViewControllerDelegate> _delegate;
    long long _type;
    UITableView *_tableView;
    WWKAttendanceWiFiInfoBottomOperationView *_bottomOperationView;
    WWKAttendanceWiFiInfoTableHeader *_headerView;
    NSTimerProxy *_updateWifiTimer;
}

@property(retain, nonatomic) NSTimerProxy *updateWifiTimer; // @synthesize updateWifiTimer=_updateWifiTimer;
@property(retain, nonatomic) WWKAttendanceWiFiInfoTableHeader *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) WWKAttendanceWiFiInfoBottomOperationView *bottomOperationView; // @synthesize bottomOperationView=_bottomOperationView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) __weak id <WWKAttendanceWiFiInfoTableViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onNotification:(int)arg1 source:(const struct NotificationSource *)arg2 details:(const struct NotificationDetails *)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)p_OnWifiUpdate:(id)arg1;
- (void)p_submitWifiToServer;
- (void)p_onSubmitDidClicked:(id)arg1;
- (void)p_ClearHistoryDidClick:(id)arg1;
- (void)p_cancel:(id)arg1;
- (void)p_updateBottomView;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

