//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKAppSectionItem.h"

@class NSString;

@interface WWKAdminAppSectionItem : WWKAppSectionItem
{
    unsigned int _groupOrder;
    unsigned int _groupId;
    NSString *_title;
}

+ (id)createNormalSection;
- (void).cxx_destruct;
- (unsigned int)groupId;
- (void)setGroupId:(unsigned int)arg1;
- (void)setGroupOrder:(unsigned int)arg1;
- (unsigned int)groupOrder;
- (id)title;
- (void)setTitle:(id)arg1;
- (id)deepCopy;

@end

