//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "AppMessageProxyObserverDelegate-Protocol.h"

@class NSLayoutConstraint, NSString, UIButton, UIScrollView, UIView, WWKAppMessageInfoView;

@interface WWKBaseAppMessageDetailViewController : UIViewController <AppMessageProxyObserverDelegate>
{
    struct unique_ptr<AppMessageSmartProxyObserver, std::__1::default_delete<AppMessageSmartProxyObserver>> smart_msg_observer_;
    scoped_refptr_d3a1e30c _appMessage;
    WWKAppMessageInfoView *_msgInfoView;
    UIView *_contentView;
    NSLayoutConstraint *_contenViewHeightConstaint;
    UIScrollView *_scrollView;
    NSLayoutConstraint *_actionButtonHeightConstraint;
    UIView *_retriveStateView;
    UIView *_overlayView;
    UIButton *_actionButton;
    NSLayoutConstraint *_contentBottomMarginConstraint;
    NSLayoutConstraint *_contentTopMarginConstraint;
    NSLayoutConstraint *_msgInfoViewHeightConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *msgInfoViewHeightConstraint; // @synthesize msgInfoViewHeightConstraint=_msgInfoViewHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *contentTopMarginConstraint; // @synthesize contentTopMarginConstraint=_contentTopMarginConstraint;
@property(nonatomic) __weak NSLayoutConstraint *contentBottomMarginConstraint; // @synthesize contentBottomMarginConstraint=_contentBottomMarginConstraint;
@property(nonatomic) __weak UIButton *actionButton; // @synthesize actionButton=_actionButton;
@property(nonatomic) __weak UIView *overlayView; // @synthesize overlayView=_overlayView;
@property(nonatomic) __weak UIView *retriveStateView; // @synthesize retriveStateView=_retriveStateView;
@property(nonatomic) __weak NSLayoutConstraint *actionButtonHeightConstraint; // @synthesize actionButtonHeightConstraint=_actionButtonHeightConstraint;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak NSLayoutConstraint *contenViewHeightConstaint; // @synthesize contenViewHeightConstaint=_contenViewHeightConstaint;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak WWKAppMessageInfoView *msgInfoView; // @synthesize msgInfoView=_msgInfoView;
@property(nonatomic) scoped_refptr_d3a1e30c appMessage; // @synthesize appMessage=_appMessage;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onClickButton:(id)arg1;
- (void)OnAppMessageUpdate:(const scoped_refptr_d3a1e30c *)arg1;
- (void)viewWillLayoutSubviews;
- (double)setupContentView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (double)contentTopMargin;
- (double)contentBottomMargin;
- (void)viewDidLoad;
- (id)initWithAppMessage:(scoped_refptr_d3a1e30c)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

