//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSString, UIImage;

@interface WWKCleanStorageConversation : NSObject
{
    unsigned long long _fileSize;
    scoped_refptr_fd92d7bf _conversation;
    NSMutableArray *_items;
    NSString *_name;
    UIImage *_avatar;
}

@property(retain, nonatomic) UIImage *avatar; // @synthesize avatar=_avatar;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(nonatomic) scoped_refptr_fd92d7bf conversation; // @synthesize conversation=_conversation;
@property(nonatomic) unsigned long long fileSize; // @synthesize fileSize=_fileSize;
- (id).cxx_construct;
- (void).cxx_destruct;
- (_Bool)purgeRemovedItems;
- (id)initWithName:(id)arg1 avatar:(id)arg2;
- (id)initWithConversation:(scoped_refptr_fd92d7bf)arg1;

@end

