//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIActivityIndicatorView, UIButton, UILabel, WWKCorpEditItem;

@interface WWKCreateCorpButtonCell : UITableViewCell
{
    UIButton *_nextButton;
    UILabel *_errorLabel;
    UILabel *_tipsLabel;
    WWKCorpEditItem *_item;
    UIActivityIndicatorView *_indicatorView;
    _Bool _beginLoading;
    double _margin;
    UIButton *_feedbackButton;
}

- (void).cxx_destruct;
- (void)feedback;
- (void)onButtonClicked;
- (void)setButtonLoading:(_Bool)arg1;
- (void)setButtonEnable:(_Bool)arg1;
- (void)resetItem:(id)arg1;
- (void)setItem:(id)arg1;
- (void)setTips:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (struct CGSize)layoutContentWithWidth:(double)arg1;
- (void)layoutSubviews;
- (void)initSubViews;
- (void)setMargin:(double)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

