//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKSimpleTableViewCell.h"

@class UIImageView;

@interface WWKCheckTableViewCell : WWKSimpleTableViewCell
{
    UIImageView *_checkImageView;
    double _rightMargin;
    _Bool _checked;
}

@property(nonatomic, getter=isChecked) _Bool checked; // @synthesize checked=_checked;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setCheckRightMargin:(double)arg1;
- (void)setCellDisable:(_Bool)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

