//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKCommonTableViewController.h"

#import "ConversationProxyObserverDelegate-Protocol.h"
#import "WWKAddMemberCellDelegate-Protocol.h"
#import "WWKConversationSearchControllerDelegate-Protocol.h"
#import "WWKEditTextDelegate-Protocol.h"
#import "WWKSelectAppointedContactsControllerDelegate-Protocol.h"
#import "WWKSelectContactsViewControllerDelegate-Protocol.h"
#import "WXCSysContactSelectViewControllerDelegate-Protocol.h"

@class NSMutableArray, NSString;

@interface WWKConversationInfoController : WWKCommonTableViewController <WWKEditTextDelegate, WWKSelectContactsViewControllerDelegate, WWKSelectAppointedContactsControllerDelegate, WWKConversationSearchControllerDelegate, ConversationProxyObserverDelegate, WXCSysContactSelectViewControllerDelegate, WWKAddMemberCellDelegate>
{
    scoped_refptr_fd92d7bf _conversation;
    _Bool _needUpdateUI;
    struct ConversationProxyObserver *_conversationProxyObserver;
    vector_4ea3d2e4 _sortedMemberList;
    NSMutableArray *_convInfoCellTypes;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)parseRichMessage:(struct RichMessage)arg1;
- (_Bool)canCloseTheConversation;
- (_Bool)canDismissTheConversation;
- (id)cellTitleForCellType:(unsigned long long)arg1;
- (id)indexPathWithCellType:(unsigned long long)arg1;
- (id)cellWithCellType:(unsigned long long)arg1;
- (id)mutableCopyWithCellTypes:(id)arg1;
- (void)removeCellType:(unsigned long long)arg1;
- (void)replaceCellType:(unsigned long long)arg1 withCellType:(unsigned long long)arg2;
- (unsigned long long)cellTypeWithIndexPath:(id)arg1;
- (void)onClickQrRoomButton;
- (void)reloadData;
- (void)scheduleRefreshShiledRemainTime;
- (void)OnPropertyChanged:(scoped_refptr_fd92d7bf)arg1;
- (void)OnRemoveMembers:(const vector_4ea3d2e4 *)arg1 inConversation:(scoped_refptr_fd92d7bf)arg2;
- (void)onAddMembers:(const vector_4ea3d2e4 *)arg1 inConversation:(scoped_refptr_fd92d7bf)arg2;
- (id)titleForNumberExceedMaxForSelectAppointedContactsController:(id)arg1;
- (int)numOfMaxSelectedContactsForSelectAppointedContactsController:(id)arg1;
- (void)_didSelectContactsForMultiPstn:(vector_89e6321f)arg1 selectController:(id)arg2;
- (void)_didSelectContactsForSendMail:(vector_89e6321f)arg1 selectController:(id)arg2;
- (void)selectAppointedContactsController:(id)arg1 didConfirmToSelectContacts:(vector_89e6321f)arg2;
- (void)selectContactsViewController:(id)arg1 didConfirmToSelectContacts:(vector_89e6321f)arg2;
- (void)addMemberCell:(id)arg1 didClickButtonWithType:(unsigned long long)arg2;
- (int)numOfMaxSelectedContactsForSysContactSelectContactsController:(id)arg1;
- (void)sysContactSelectContactsController:(id)arg1 didConfirmToSelectContacts:(vector_89e6321f)arg2;
- (void)editTextController:(id)arg1 didClickSaveItemWithText:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)setConversation:(scoped_refptr_fd92d7bf)arg1;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

