//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSMutableArray;

@interface WWKEmotionManageCell : UITableViewCell
{
    NSMutableArray *_viewArray;
}

@property(retain, nonatomic) NSMutableArray *viewArray; // @synthesize viewArray=_viewArray;
- (void).cxx_destruct;
- (void)setEmoticonArray:(id)arg1 andWidth:(double)arg2 andDelegate:(id)arg3;

@end

