//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UITableView, UIView;

@interface WWKIndustryTypeController : UIViewController <UITableViewDelegate, UITableViewDataSource>
{
    NSMutableArray *_leftDataSource;
    NSMutableArray *_rightDataSource;
    struct IndustryInfo _orginalSelectedIndustryInfo;
    _Bool _callbackByRightBarItem;
    CDUnknownBlockType _callback;
    NSString *_rightBarItemTitle;
    UITableView *_leftTableView;
    UITableView *_rightTableView;
    UIView *_seperatorView;
}

@property(retain, nonatomic) UIView *seperatorView; // @synthesize seperatorView=_seperatorView;
@property(retain, nonatomic) UITableView *rightTableView; // @synthesize rightTableView=_rightTableView;
@property(retain, nonatomic) UITableView *leftTableView; // @synthesize leftTableView=_leftTableView;
@property(nonatomic) _Bool callbackByRightBarItem; // @synthesize callbackByRightBarItem=_callbackByRightBarItem;
@property(retain, nonatomic) NSString *rightBarItemTitle; // @synthesize rightBarItemTitle=_rightBarItemTitle;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)rightBarItemClick;
- (id)firstSelectedModel;
- (void)p_updateRightBarItemEnable;
- (void)p_resetDataSourceCheck:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewWillLayoutSubviews;
- (id)createTableView;
- (void)initRightTableView;
- (void)initLeftTableView;
- (void)viewDidLoad;
- (id)initWithIndustryInfoList:(const vector_6b0af354 *)arg1 selected:(const struct IndustryInfo *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

