//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKMeInfoTableViewController.h"

@interface WWKInternalCustomerInfoViewController : WWKMeInfoTableViewController
{
    long long _currentEditType;
}

- (void)didModifyAvatarInPreviewAvatarController:(id)arg1;
- (void)controller:(id)arg1 onItemSelected:(long long)arg2;
- (unsigned long long)editTypeWithCellType:(long long)arg1;
- (void)editTextController:(id)arg1 didClickSaveItemWithText:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)initDataAndRefresh:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;
- (id)initWithUser:(scoped_refptr_e1f85e48)arg1;

@end

