//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKBaseAppMessageDetailViewController.h"

@class WWKImageAppMessageDetailView;

@interface WWKImageAppMessageDetailViewController : WWKBaseAppMessageDetailViewController
{
    WWKImageAppMessageDetailView *_imageContentView;
}

@property(retain, nonatomic) WWKImageAppMessageDetailView *imageContentView; // @synthesize imageContentView=_imageContentView;
- (void).cxx_destruct;
- (double)setupContentView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

