//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKMessageMedia.h"

@class NSMutableArray, NSString;

@interface WWKMesssageSurveyCard : WWKMessageMedia
{
    NSString *_cardId;
    NSString *_title;
    unsigned long long _businessId;
    long long _cardStatus;
    NSString *_from;
    NSMutableArray *_items;
}

+ (_Bool)supportsMergeForwarding;
+ (_Bool)supportsForwarding;
@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(copy, nonatomic) NSString *from; // @synthesize from=_from;
@property(nonatomic) long long cardStatus; // @synthesize cardStatus=_cardStatus;
@property(nonatomic) unsigned long long businessId; // @synthesize businessId=_businessId;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *cardId; // @synthesize cardId=_cardId;
- (void).cxx_destruct;

@end

