//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;
@protocol WWKModifyArchBottomBarDelegate;

@interface WWKModifyArchBottomBar : UIView
{
    unsigned long long _childUsersCount;
    unsigned long long _childDepartmentsCount;
    id <WWKModifyArchBottomBarDelegate> _delegate;
    UIView *_topSeparator;
    UIButton *_addMemberButton;
    UIButton *_addDepartmentButton;
    UIButton *_moreButton;
}

@property(retain, nonatomic) UIButton *moreButton; // @synthesize moreButton=_moreButton;
@property(retain, nonatomic) UIButton *addDepartmentButton; // @synthesize addDepartmentButton=_addDepartmentButton;
@property(retain, nonatomic) UIButton *addMemberButton; // @synthesize addMemberButton=_addMemberButton;
@property(retain, nonatomic) UIView *topSeparator; // @synthesize topSeparator=_topSeparator;
@property(nonatomic) __weak id <WWKModifyArchBottomBarDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)updateBottomBarWithChildUserCount:(unsigned long long)arg1 childDepartmentsCount:(unsigned long long)arg2;
- (void)moreButtonClicked;
- (void)addDepartmentButtonClicked;
- (void)addMemberButtonClicked;
- (id)buildCommonStyleButtonWithSelector:(SEL)arg1;
- (id)buildCommonStyleButtonWithSelector:(SEL)arg1 title:(id)arg2;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;

@end

