//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UILabel, UISwitch;

@interface WWKManageHeaderView : UIView
{
    UILabel *_titleLabel;
    UILabel *_detailTitleLabel;
    UIView *_separator;
    _Bool _showNotify;
    NSString *_title;
    NSString *_subTitle;
    UISwitch *_notifySwitch;
}

@property(retain, nonatomic) UISwitch *notifySwitch; // @synthesize notifySwitch=_notifySwitch;
@property(nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) _Bool showNotify; // @synthesize showNotify=_showNotify;
- (void).cxx_destruct;
- (void)adjustLabelWidth:(double)arg1;
- (struct CGSize)layoutSubviewsInWidth:(double)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

