//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKSimpleTableViewCell.h"

@class NSString, UILabel;

@interface WWKNewUserInfoCell : WWKSimpleTableViewCell
{
    NSString *_copyContent;
    _Bool _contextMenuShow;
    _Bool _hiddenSubContent;
    unsigned long long _user_id;
    _Bool _largePadding;
    UILabel *_cellTypeLabel;
    UILabel *_cellContentLabel;
}

@property(retain, nonatomic) UILabel *cellContentLabel; // @synthesize cellContentLabel=_cellContentLabel;
@property(retain, nonatomic) UILabel *cellTypeLabel; // @synthesize cellTypeLabel=_cellTypeLabel;
@property(nonatomic) _Bool largePadding; // @synthesize largePadding=_largePadding;
- (void).cxx_destruct;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (_Bool)canBecomeFirstResponder;
- (void)cellLongPress:(id)arg1;
- (void)menuControllerWillHide:(id)arg1;
- (void)contextMenuCopy:(id)arg1;
- (id)contextMenuItems;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (struct CGSize)layoutContentWithWidth:(double)arg1;
- (void)layoutSubviews;
- (void)setCellContent:(id)arg1 andSubContent:(id)arg2 subContentHidden:(_Bool)arg3 andUserId:(unsigned long long)arg4;
- (void)setContentString:(id)arg1;
- (void)setSubContentLabelColor:(id)arg1;
- (void)setContentLabelColor:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

