//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIImageView;

@interface WWKNoInvoiceViewController : UIViewController
{
    UIImageView *_noInvoice;
}

@property(nonatomic) __weak UIImageView *noInvoice; // @synthesize noInvoice=_noInvoice;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

