//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKBaseMessageCell.h"

@class UIButton, UIImageView, UILabel, UIView, WWKPromoteWrapper;

@interface WWKPromoteTipsView : WWKBaseMessageCell
{
    UIImageView *_tipsIcon;
    UILabel *_titleLabel;
    UIView *_seperatorView;
    UIButton *_closeButtonView;
    WWKPromoteWrapper *_dataWrapper;
}

- (void).cxx_destruct;
- (struct CGSize)p_layoutSubViewsWithLimitWidth:(double)arg1;
- (void)layoutSubviews;
- (double)getHeightWithLimitWidth:(double)arg1;
- (void)onDidTap;
- (void)p_onCloseDidTap:(id)arg1;
- (void)p_updateUI;
- (void)setDataWrapper:(id)arg1;
- (void)initSubViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

