//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIImage, UIImageView;

@interface WWKPreviewQrCodeViewController : UIViewController
{
    UIImageView *_previewImageView;
    UIImage *_image;
    struct CGRect _initFrame;
}

@property(nonatomic) struct CGRect initFrame; // @synthesize initFrame=_initFrame;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(nonatomic) __weak UIImageView *previewImageView; // @synthesize previewImageView=_previewImageView;
- (void).cxx_destruct;
- (void)onClose:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidLoad;
- (void)show;
- (id)initWithImage:(id)arg1 initFrame:(struct CGRect)arg2;

@end

