//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableView.h>

@protocol wwkRemindDetailTableViewDelegate;

@interface WWKRemindDetailTableView : UITableView
{
    id <wwkRemindDetailTableViewDelegate> _touchDelegate;
}

@property(nonatomic) __weak id <wwkRemindDetailTableViewDelegate> touchDelegate; // @synthesize touchDelegate=_touchDelegate;
- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;

@end

