//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKReadmailHighlightButton.h"

@class UIImageView, UILabel;

@interface WWKReadmailContactButton : WWKReadmailHighlightButton
{
    UIImageView *_contactIcon;
    UILabel *_nameLabel;
    UILabel *_addrLabel;
    struct MailAddress _mailAddress;
}

@property(nonatomic) struct MailAddress mailAddress; // @synthesize mailAddress=_mailAddress;
@property(retain, nonatomic) UILabel *addrLabel; // @synthesize addrLabel=_addrLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *contactIcon; // @synthesize contactIcon=_contactIcon;
- (id).cxx_construct;
- (void).cxx_destruct;

@end

