//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class WWKSelectTagModel;

@interface WWKSelectContactsModel : NSObject
{
    unsigned long long _type;
    scoped_refptr_e1f85e48 _user;
    scoped_refptr_85c18dd7 _department;
    WWKSelectTagModel *_tag;
    unsigned long long _userId;
    scoped_refptr_fd92d7bf _conversation;
}

+ (id)contactWithConversation:(scoped_refptr_fd92d7bf)arg1;
+ (id)contactWithUserId:(unsigned long long)arg1;
+ (id)contactWithDepartment:(scoped_refptr_85c18dd7)arg1;
+ (id)contactWithUser:(scoped_refptr_e1f85e48)arg1;
@property(nonatomic) scoped_refptr_fd92d7bf conversation; // @synthesize conversation=_conversation;
@property(nonatomic) unsigned long long userId; // @synthesize userId=_userId;
@property(retain, nonatomic) WWKSelectTagModel *tag; // @synthesize tag=_tag;
@property(nonatomic) scoped_refptr_85c18dd7 department; // @synthesize department=_department;
@property(nonatomic) scoped_refptr_e1f85e48 user; // @synthesize user=_user;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (id).cxx_construct;
- (void).cxx_destruct;

@end

