//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WWKSMSHelper : NSObject
{
}

+ (_Bool)messageIsFromMe:(id)arg1;
+ (id)displayNameWithVid:(unsigned long long)arg1 phoneNum:(id)arg2;
+ (id)messageTitleWithMessage:(id)arg1;

@end

