//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSArray;

@interface WWKStateChangeButton : UIButton
{
    int _curState;
    NSArray *_stateImage;
    NSArray *_stateNum;
}

@property(retain, nonatomic) NSArray *stateNum; // @synthesize stateNum=_stateNum;
@property(retain, nonatomic) NSArray *stateImage; // @synthesize stateImage=_stateImage;
- (void).cxx_destruct;
- (void)toState:(unsigned long long)arg1;
- (void)updateImage;
- (void)toNextState;
- (unsigned long long)getCurStateNum;
- (id)initWithStateImages:(id)arg1 withStateNumbes:(id)arg2;

@end

