//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class WWKAvatarImageView;

@interface WWKSelectedHeadButton : UIControl
{
    scoped_refptr_e1f85e48 _user;
    WWKAvatarImageView *_avatarImageView;
    scoped_refptr_fd92d7bf _conversation;
    unsigned long long _contactType;
}

@property(nonatomic) unsigned long long contactType; // @synthesize contactType=_contactType;
@property(nonatomic) scoped_refptr_fd92d7bf conversation; // @synthesize conversation=_conversation;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setCanDelete:(_Bool)arg1;
- (void)setAssociatedUser:(scoped_refptr_e1f85e48)arg1;
- (scoped_refptr_e1f85e48)associatedUser;
- (id)initWithFrame:(struct CGRect)arg1;

@end

