//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKSimpleTableViewCell.h"

@class UIImageView, UILabel;

@interface WWKUserInfoCommonCell : WWKSimpleTableViewCell
{
    _Bool _suppInfo;
    _Bool _subTitleCilckable;
    UILabel *_cellTypeLabel;
    UILabel *_cellContentLabel;
    UIImageView *_suppInfoIcon;
}

@property(retain, nonatomic) UIImageView *suppInfoIcon; // @synthesize suppInfoIcon=_suppInfoIcon;
@property(retain, nonatomic) UILabel *cellContentLabel; // @synthesize cellContentLabel=_cellContentLabel;
@property(retain, nonatomic) UILabel *cellTypeLabel; // @synthesize cellTypeLabel=_cellTypeLabel;
@property(nonatomic) _Bool subTitleCilckable; // @synthesize subTitleCilckable=_subTitleCilckable;
@property(nonatomic) _Bool suppInfo; // @synthesize suppInfo=_suppInfo;
- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (struct CGSize)layoutContentWithWidth:(double)arg1;
- (void)layoutSubviews;
- (void)setSuppIconImage:(id)arg1;
- (void)setTitle:(id)arg1 andSubTitle:(id)arg2;
- (void)OnsubTitleClick;
- (void)initSubView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

