//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSTimerProxy, UIImageView, UILabel;
@protocol WWKVoiceHintViewDelegate;

@interface WWKVoiceHintView : UIView
{
    UIImageView *_mainVoiceImageView;
    unsigned long long _currentVolumn;
    UIImageView *_progressImageView;
    UILabel *_normalHintLabel;
    UILabel *_cancelHintLabel;
    UIImageView *_cancelImageView;
    UIImageView *_timeShortImageView;
    UILabel *_timeShortLabel;
    UILabel *_countDownNumberLabel;
    UIImageView *_turnUpVolumnImageView;
    UILabel *_turnUpVolumnLabel;
    int _countDownNumber;
    NSTimerProxy *_countDownTimer;
    int _showCount;
    _Bool _isShowTimeShortWarning;
    id <WWKVoiceHintViewDelegate> _delegate;
}

@property(nonatomic) __weak id <WWKVoiceHintViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isShowTimeShortWarning; // @synthesize isShowTimeShortWarning=_isShowTimeShortWarning;
- (void).cxx_destruct;
- (void)hideAfterDelay:(double)arg1;
- (void)resetCountDown;
- (void)showTurnUpVolumn;
- (void)p_onUpdateCountDown;
- (void)showOutSide;
- (void)showCountDown;
- (void)showTimeShortWarning;
- (void)showInProgress;
- (unsigned long long)currentVolumnDegress;
- (void)changeVolumnWithDegress:(unsigned long long)arg1;
- (void)setHidden:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

