//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface WWKVoteDetailItem : NSObject
{
    vector_7dcb3552 _userList;
    _Bool _isSelfVoted;
    int _itemId;
    NSString *_mainTitle;
    long long _voteCount;
    double _percentage;
}

@property(nonatomic) int itemId; // @synthesize itemId=_itemId;
@property(nonatomic) double percentage; // @synthesize percentage=_percentage;
@property(nonatomic) long long voteCount; // @synthesize voteCount=_voteCount;
@property(nonatomic) _Bool isSelfVoted; // @synthesize isSelfVoted=_isSelfVoted;
@property(copy, nonatomic) NSString *mainTitle; // @synthesize mainTitle=_mainTitle;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)addUser:(unsigned long long)arg1;
- (vector_7dcb3552)getUserList;
- (id)init;

@end

