//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKSimpleTableViewCell.h"

#import "QMUITextFieldDelegate-Protocol.h"

@class NSString, QMUITextField;

@interface WWKVoteTitleTableViewCell : WWKSimpleTableViewCell <QMUITextFieldDelegate>
{
    QMUITextField *_textField;
}

@property(retain, nonatomic) QMUITextField *textField; // @synthesize textField=_textField;
- (void).cxx_destruct;
- (void)onTextChanged:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)beginEdit;
- (void)setTitlePlaceHolder:(id)arg1;
- (struct CGSize)layoutElements:(struct CGSize)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)p_initSubView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

