//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKVoteCommonThemeViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSObject, NSString, UITableView, WWKCommonEmptyView;

@interface WWKVoteHistoryListController : WWKVoteCommonThemeViewController <UITableViewDelegate, UITableViewDataSource>
{
    long long _convId;
    NSObject *_reuseGuard;
    _Bool _hasFetchAllRecord;
    UITableView *_tableView;
    NSMutableArray *_detailArray;
    WWKCommonEmptyView *_emptyView;
}

@property(retain, nonatomic) WWKCommonEmptyView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) NSMutableArray *detailArray; // @synthesize detailArray=_detailArray;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (void)p_updateUI;
- (void)p_showLoading:(_Bool)arg1;
- (void)p_fetchData:(_Bool)arg1;
- (void)p_setupFooterRefresh;
- (void)setupTableViewFooter;
- (void)p_setupHeaderRefresh;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithConvId:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

