//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "WWCMRVideoPreviewViewDelegate-Protocol.h"
#import "WWKVideoRecorderBottomViewDelegate-Protocol.h"

@class NSString, NSTimer, UIImageView, UIView, WWCMRVideoPreviewView, WWCamera, WWKVideoRecorderBottomView, WWKVideoRecorderTopView;
@protocol WWKVideoReocrdViewControllerDeleate;

@interface WWKVideoReocrdViewController : UIViewController <WWKVideoRecorderBottomViewDelegate, WWCMRVideoPreviewViewDelegate>
{
    int _videoRecToalSec;
    id <WWKVideoReocrdViewControllerDeleate> _cameraDelegate;
    UIView *_cameraView;
    WWCamera *_cameraInstance;
    UIImageView *_cameraFocusView;
    WWCMRVideoPreviewView *_videoPreviewView;
    WWKVideoRecorderTopView *_topBarView;
    WWKVideoRecorderBottomView *_bottomBarView;
    NSTimer *_videoRecTimer;
    long long _maxRecSec;
}

@property(nonatomic) long long maxRecSec; // @synthesize maxRecSec=_maxRecSec;
@property(nonatomic) int videoRecToalSec; // @synthesize videoRecToalSec=_videoRecToalSec;
@property(retain, nonatomic) NSTimer *videoRecTimer; // @synthesize videoRecTimer=_videoRecTimer;
@property(retain, nonatomic) WWKVideoRecorderBottomView *bottomBarView; // @synthesize bottomBarView=_bottomBarView;
@property(retain, nonatomic) WWKVideoRecorderTopView *topBarView; // @synthesize topBarView=_topBarView;
@property(retain, nonatomic) WWCMRVideoPreviewView *videoPreviewView; // @synthesize videoPreviewView=_videoPreviewView;
@property(retain, nonatomic) UIImageView *cameraFocusView; // @synthesize cameraFocusView=_cameraFocusView;
@property(retain, nonatomic) WWCamera *cameraInstance; // @synthesize cameraInstance=_cameraInstance;
@property(retain, nonatomic) UIView *cameraView; // @synthesize cameraView=_cameraView;
@property(nonatomic) __weak id <WWKVideoReocrdViewControllerDeleate> cameraDelegate; // @synthesize cameraDelegate=_cameraDelegate;
- (void).cxx_destruct;
- (void)p_stopVideoRecTimer;
- (void)p_updateTimerLabel;
- (void)p_showTimesUpAlert;
- (void)p_onVideoRecTimer:(id)arg1;
- (void)p_startVideoRecTimer;
- (void)p_cleanJob;
- (void)p_setupCameraSession;
- (void)p_changeToVideoMode;
- (void)p_doInitUI;
- (void)noti_enterBackGround;
- (void)noti_enterForeGround;
- (void)p_removeNoti;
- (void)p_addNoti;
- (void)p_doInitLogic;
- (void)didClickToggleCameraBtnForBottomBarView:(id)arg1;
- (void)onCancelBtnClickForCameraBottomBar:(id)arg1;
- (void)p_onCaptureBtnRecordVideo;
- (void)onCaptureBtnClickForCameraBottomBar:(id)arg1;
- (void)onUseVideoForVideoPreview:(id)arg1;
- (void)doCleanJob;
- (void)didReceiveMemoryWarning;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

