//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIButton, UIImageView, UILabel, UIScrollView;

@interface WWKWSShareView : UIView
{
    UIView *_whiteView;
    UILabel *_titleLabel;
    UIImageView *_imgView;
    UILabel *_statusLabel;
    UILabel *_timeLabel;
    UILabel *_weworkLabel;
    UIScrollView *_scrollView;
    UIButton *_shareTowxButton;
    NSString *_url;
    NSString *_time;
    NSString *_status;
    _Bool _fakeShare;
    UIView *_shareContentView;
}

@property(retain, nonatomic) UIView *shareContentView; // @synthesize shareContentView=_shareContentView;
@property(nonatomic) _Bool fakeShare; // @synthesize fakeShare=_fakeShare;
- (void).cxx_destruct;
- (double)maxScrollViewHeight;
- (struct CGSize)layoutSubViewWithWidth:(double)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)setImageUrl:(id)arg1 andStatusString:(id)arg2 andTimeString:(id)arg3;
- (id)imageWithView:(id)arg1;
- (void)onShareTowx;
- (void)initSubView;
- (_Bool)plusLayout;
- (id)initWithFrame:(struct CGRect)arg1;

@end

