//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WWKWorkLogDataHelper : NSObject
{
}

+ (_Bool)isAdminEggOpen;
+ (void)adminEggSetOpen:(_Bool)arg1;
+ (void)cleanGuideBannerAndAlsoSetMemory:(_Bool)arg1;
+ (_Bool)shouldShowGuideBanner;
+ (void)DoTestRemoveComment;
+ (void)DoTestGetCommentList;
+ (void)DoTestAddComment;
+ (void)DoTestJournalStreamList;
+ (void)DoTestJournalModify:(_Bool)arg1;
+ (void)DoTestJournalReporter;
+ (void)DoTestJournalSummary;
+ (void)DoTestJournalDetail;
+ (void)DoTestSubitJournal;
+ (id)getWorklogCreatUrlWithClientInfo:(id)arg1;
+ (id)getWorklogDetailUrlWithClientInfo:(id)arg1;
+ (id)getEditWorklogTemplateUrl:(id)arg1 withJournalId:(unsigned long long)arg2;
+ (vector_2182b2f4)getVaildApp:(const struct CommAppListRsp *)arg1;
+ (_Bool)isCommentBySelf:(unsigned long long)arg1;
+ (id)filterAndDropMoreNewLine:(id)arg1;
+ (id)decodeHtmlText:(id)arg1;
+ (id)getJournalTemplateEntryContent:(const struct JournalEntry *)arg1;
+ (id)getTextFromContentString:(basic_string_a490aa4c)arg1;
+ (id)getTextContentFromJournalEntry:(struct JournalEntry *)arg1;
+ (id)getRichTextContentFromJournalEntry:(struct JournalEntry *)arg1;
+ (id)replaceSpanStyleFontSizeWithFontTag:(id)arg1;
+ (id)replaceHtmlStyleFontWithTag:(id)arg1;
+ (struct JournalEntryContent)makeJournalEntryTextContent:(id)arg1 withRichContent:(id)arg2;
+ (id)worklogDetailContentWith:(const struct JournalEntry *)arg1;
+ (void)createWorklogShareMsgWithJournalEntry:(struct JournalEntry)arg1 withTemplateName:(id)arg2 completed:(CDUnknownBlockType)arg3;
+ (id)getReportNameText:(const scoped_refptr_8a36260b *)arg1 isAllName:(_Bool)arg2 maxShowCount:(int)arg3;
+ (id)getTitleForLogType:(int)arg1;
+ (struct JournalEntry)getWorklogEntryFromLinkMsg:(const struct LinkMessage *)arg1;
+ (void)onTapWorklogCreatNotifyMsg:(id)arg1 fromBubbleView:(id)arg2;
+ (void)onTapWorklogNotifyMsg:(id)arg1 fromBubbleView:(id)arg2;
+ (void)onTapWorklogAppMsg:(id)arg1 fromBubbleView:(id)arg2;
+ (_Bool)isWorklogCreatNotifyMsgLink:(id)arg1;
+ (_Bool)isWorklogNotifyMsgLink:(id)arg1;
+ (_Bool)isWorklogAppMsgLink:(id)arg1;
+ (_Bool)isWorklogRealNotifyNeedSplite:(struct Message *)arg1;
+ (id)getNewWorklogShowTextFromMessage:(struct Message *)arg1 forRow:(int)arg2;
+ (_Bool)isUseNewWorklogNotifyCard:(struct Message *)arg1;
+ (_Bool)isWorklogTemplate:(long long)arg1;
+ (_Bool)isWorklogTemplateCreatNotifyMsg:(struct Message *)arg1;
+ (_Bool)isSupportedWorkLogShareMsg:(const struct LinkMessage *)arg1;
+ (_Bool)isWorklogNotifyMsg:(struct Message *)arg1;
+ (_Bool)isWorklogAppMsg:(struct Message *)arg1;
+ (_Bool)isWorklogShareMsg:(struct Message *)arg1;
+ (_Bool)isNetWorkOK;
+ (id)getImageNameWithIndex:(int)arg1 withTimeUInt:(long long)arg2;
+ (_Bool)addContent:(id)arg1 toComment:(struct CommentInfo *)arg2;
+ (id)getCommentContentString:(struct CommentInfo)arg1;
+ (struct JounalAttach)getCPPAttachesFromOCAttach:(id)arg1;
+ (id)getOCAttachesFromJournalEnty:(struct JournalEntry *)arg1;
+ (_Bool)isJournalEntyHasAttach:(const basic_string_a490aa4c *)arg1;
+ (id)journalCreatorHeadUrlFromClientDataString:(const basic_string_a490aa4c *)arg1;
+ (id)journalCreatorNameFromClientDataString:(const basic_string_a490aa4c *)arg1;
+ (struct SubmitJournalReq)convertJournalEntry2SubmitReq:(struct JournalEntry)arg1 opType:(int)arg2;

@end

