//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class QMUIButton;

@interface WWKWorkLogListToolbarView : UIView
{
    QMUIButton *_preButton;
    QMUIButton *_selectButton;
    QMUIButton *_nextButton;
}

@property(retain, nonatomic) QMUIButton *nextButton; // @synthesize nextButton=_nextButton;
@property(retain, nonatomic) QMUIButton *selectButton; // @synthesize selectButton=_selectButton;
@property(retain, nonatomic) QMUIButton *preButton; // @synthesize preButton=_preButton;
- (void).cxx_destruct;
- (id)creatButton:(id)arg1 normImageName:(id)arg2 highLightImageName:(id)arg3 titleFontSize:(double)arg4 iconPosition:(int)arg5;
- (void)initViews;
- (void)layoutSubviews;
- (void)updateView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

