//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QMUITableViewCell.h"

@class CALayer, WEWCloudCommentInfo, WWKAvatarButton, WWKInteractiveLabel;
@protocol WWKYunPanCommentCellDelegate;

@interface WWKYunPanCommentCell : QMUITableViewCell
{
    id <WWKYunPanCommentCellDelegate> _delegate;
    WWKAvatarButton *_avatarButton;
    WWKInteractiveLabel *_usernameLabel;
    WWKInteractiveLabel *_contentLabel;
    WWKInteractiveLabel *_timeAndDeleteLabel;
    CALayer *_separatorLayer;
    double _avatarButtonMarginRight;
    double _usernameLabelMarginTop;
    double _contentLabelMarginTop;
    double _timeAndDeleteLabelMarginTop;
    WEWCloudCommentInfo *_mInfo;
    struct UIEdgeInsets _padding;
}

@property(retain, nonatomic) WEWCloudCommentInfo *mInfo; // @synthesize mInfo=_mInfo;
@property(nonatomic) double timeAndDeleteLabelMarginTop; // @synthesize timeAndDeleteLabelMarginTop=_timeAndDeleteLabelMarginTop;
@property(nonatomic) double contentLabelMarginTop; // @synthesize contentLabelMarginTop=_contentLabelMarginTop;
@property(nonatomic) double usernameLabelMarginTop; // @synthesize usernameLabelMarginTop=_usernameLabelMarginTop;
@property(nonatomic) double avatarButtonMarginRight; // @synthesize avatarButtonMarginRight=_avatarButtonMarginRight;
@property(nonatomic) struct UIEdgeInsets padding; // @synthesize padding=_padding;
@property(retain, nonatomic) CALayer *separatorLayer; // @synthesize separatorLayer=_separatorLayer;
@property(readonly, nonatomic) WWKInteractiveLabel *timeAndDeleteLabel; // @synthesize timeAndDeleteLabel=_timeAndDeleteLabel;
@property(readonly, nonatomic) WWKInteractiveLabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(readonly, nonatomic) WWKInteractiveLabel *usernameLabel; // @synthesize usernameLabel=_usernameLabel;
@property(readonly, nonatomic) WWKAvatarButton *avatarButton; // @synthesize avatarButton=_avatarButton;
@property(nonatomic) __weak id <WWKYunPanCommentCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setNeedsHighlightAnim:(_Bool)arg1;
- (void)requestReloadCellForForumPostCommentIfCan:(unsigned long long)arg1;
- (void)renderCellSuffix;
- (void)renderCellContent;
- (void)renderCellAvatarAndNameWithUser:(const scoped_refptr_e1f85e48 *)arg1 authorName:(id)arg2 repliedName:(id)arg3;
- (_Bool)isUserNotInCache:(unsigned long long)arg1;
- (void)renderCellUserInfoWithComment:(id)arg1;
- (void)renderWithCommentInfo:(id)arg1;
- (void)updateCellAppearanceWithIndexPath:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

