//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class CALayer, UIImageView, UILabel;

@interface WWMarketAppIntroSuitEntryCell : UITableViewCell
{
    UIImageView *_suitIconView;
    UILabel *_suitProviderLbl;
    UILabel *_suitDetailLbl;
    CALayer *_topSepLineLayer;
}

@property(retain, nonatomic) CALayer *topSepLineLayer; // @synthesize topSepLineLayer=_topSepLineLayer;
@property(retain, nonatomic) UILabel *suitDetailLbl; // @synthesize suitDetailLbl=_suitDetailLbl;
@property(retain, nonatomic) UILabel *suitProviderLbl; // @synthesize suitProviderLbl=_suitProviderLbl;
@property(retain, nonatomic) UIImageView *suitIconView; // @synthesize suitIconView=_suitIconView;
- (void).cxx_destruct;
- (void)updateTitleText:(id)arg1 subtitleText:(id)arg2;
- (void)updateWithRecommendApp:(const struct RecommendApp *)arg1 relativeAppList:(const vector_c253e700 *)arg2;
- (double)p_layoutForHeightWithParentWidth:(double)arg1;
- (void)p_doInit;
- (double)cellHeightWithParentWidth:(double)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

