//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class CALayer, UILabel;

@interface WWMarketAppCommentOnlyContentTextCell : UITableViewCell
{
    UILabel *_cmtContentLbl;
    UILabel *_prvdrRespLbl;
    UILabel *_prvdrRespContentLbl;
    CALayer *_prvdrRespBgLayer;
}

@property(retain, nonatomic) CALayer *prvdrRespBgLayer; // @synthesize prvdrRespBgLayer=_prvdrRespBgLayer;
@property(retain, nonatomic) UILabel *prvdrRespContentLbl; // @synthesize prvdrRespContentLbl=_prvdrRespContentLbl;
@property(retain, nonatomic) UILabel *prvdrRespLbl; // @synthesize prvdrRespLbl=_prvdrRespLbl;
@property(retain, nonatomic) UILabel *cmtContentLbl; // @synthesize cmtContentLbl=_cmtContentLbl;
- (void).cxx_destruct;
- (void)updateWithCommentDetail:(const struct UserComment *)arg1;
- (double)p_layoutForHeightWithParentWidth:(double)arg1;
- (void)p_doInit;
- (double)cellHeightWithParentWidth:(double)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

