//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WWOnlineInfoListData : NSObject
{
    scoped_refptr_8148daa1 _onlineList;
    unsigned long long _onlineLimitCnt;
}

@property(nonatomic) unsigned long long onlineLimitCnt; // @synthesize onlineLimitCnt=_onlineLimitCnt;
@property(nonatomic) scoped_refptr_8148daa1 onlineList; // @synthesize onlineList=_onlineList;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

