//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "QMUITextFieldDelegate-Protocol.h"
#import "WWPstnBioassayVideoRecordDelegate-Protocol.h"

@class MBProgressHUD, NSString, QMUITextField, UIButton, UIImage, UIImagePickerController, UIImageView, UILabel, UIView, WWBioassayIDCardView, WWBioassayResultView, WWBioassayStepBarView, WWKTakePhotoOverlayView;

@interface WWPstnBioassayController : UIViewController <WWPstnBioassayVideoRecordDelegate, QMUITextFieldDelegate>
{
    id _observingView;
    UIView *_topBar;
    UIView *_bottomBar;
    _Bool _idHumanCheckOK;
    _Bool _idEmblemCheckOK;
    _Bool _idCardConfirmOK;
    _Bool _bioCheckCompleted;
    NSString *_inputName;
    WWBioassayStepBarView *_stepBarView;
    UIButton *_nextStepBtn;
    MBProgressHUD *_hud;
    WWBioassayIDCardView *_idcardViewHuman;
    WWBioassayIDCardView *_idcardViewEmblem;
    WWKTakePhotoOverlayView *_idcardCameraOverlayView;
    UIImagePickerController *_imgPicker;
    QMUITextField *_nameTxtField;
    QMUITextField *_idCardTxtField;
    UILabel *_idInfoConfirmLabel;
    UIImageView *_bioIntroImgView;
    UILabel *_bioIntroLabel;
    WWBioassayResultView *_bioResultView;
    NSString *_detectSequenceNumber;
    long long _checkStep;
    UIImage *_idHumanImg;
    UIImage *_idEmblemImg;
    NSString *_ocrIdResultName;
    NSString *_ocrIdResultNumber;
    NSString *_confirmIdName;
    NSString *_confirmIdNumber;
    NSString *_bioPinCode;
    long long _bioFailedErr;
}

@property(nonatomic) _Bool bioCheckCompleted; // @synthesize bioCheckCompleted=_bioCheckCompleted;
@property(nonatomic) long long bioFailedErr; // @synthesize bioFailedErr=_bioFailedErr;
@property(copy, nonatomic) NSString *bioPinCode; // @synthesize bioPinCode=_bioPinCode;
@property(copy, nonatomic) NSString *confirmIdNumber; // @synthesize confirmIdNumber=_confirmIdNumber;
@property(copy, nonatomic) NSString *confirmIdName; // @synthesize confirmIdName=_confirmIdName;
@property(nonatomic) _Bool idCardConfirmOK; // @synthesize idCardConfirmOK=_idCardConfirmOK;
@property(copy, nonatomic) NSString *ocrIdResultNumber; // @synthesize ocrIdResultNumber=_ocrIdResultNumber;
@property(copy, nonatomic) NSString *ocrIdResultName; // @synthesize ocrIdResultName=_ocrIdResultName;
@property(nonatomic) _Bool idEmblemCheckOK; // @synthesize idEmblemCheckOK=_idEmblemCheckOK;
@property(nonatomic) _Bool idHumanCheckOK; // @synthesize idHumanCheckOK=_idHumanCheckOK;
@property(retain, nonatomic) UIImage *idEmblemImg; // @synthesize idEmblemImg=_idEmblemImg;
@property(retain, nonatomic) UIImage *idHumanImg; // @synthesize idHumanImg=_idHumanImg;
@property(nonatomic) long long checkStep; // @synthesize checkStep=_checkStep;
@property(copy, nonatomic) NSString *detectSequenceNumber; // @synthesize detectSequenceNumber=_detectSequenceNumber;
@property(retain, nonatomic) WWBioassayResultView *bioResultView; // @synthesize bioResultView=_bioResultView;
@property(retain, nonatomic) UILabel *bioIntroLabel; // @synthesize bioIntroLabel=_bioIntroLabel;
@property(retain, nonatomic) UIImageView *bioIntroImgView; // @synthesize bioIntroImgView=_bioIntroImgView;
@property(retain, nonatomic) UILabel *idInfoConfirmLabel; // @synthesize idInfoConfirmLabel=_idInfoConfirmLabel;
@property(retain, nonatomic) QMUITextField *idCardTxtField; // @synthesize idCardTxtField=_idCardTxtField;
@property(retain, nonatomic) QMUITextField *nameTxtField; // @synthesize nameTxtField=_nameTxtField;
@property(retain, nonatomic) UIImagePickerController *imgPicker; // @synthesize imgPicker=_imgPicker;
@property(retain, nonatomic) WWKTakePhotoOverlayView *idcardCameraOverlayView; // @synthesize idcardCameraOverlayView=_idcardCameraOverlayView;
@property(retain, nonatomic) WWBioassayIDCardView *idcardViewEmblem; // @synthesize idcardViewEmblem=_idcardViewEmblem;
@property(retain, nonatomic) WWBioassayIDCardView *idcardViewHuman; // @synthesize idcardViewHuman=_idcardViewHuman;
@property(nonatomic) __weak MBProgressHUD *hud; // @synthesize hud=_hud;
@property(retain, nonatomic) UIButton *nextStepBtn; // @synthesize nextStepBtn=_nextStepBtn;
@property(retain, nonatomic) WWBioassayStepBarView *stepBarView; // @synthesize stepBarView=_stepBarView;
@property(copy, nonatomic) NSString *inputName; // @synthesize inputName=_inputName;
- (void).cxx_destruct;
- (id)get3ScreenShots:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)findBottomBar:(id)arg1;
- (id)findTopBar:(id)arg1;
- (id)findPreviewBottomBar:(id)arg1;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (id)imageFromImage:(id)arg1 inRect:(struct CGRect)arg2;
- (void)p_clearIdCardViewsImg;
- (void)p_finishBioassay;
- (void)p_resetBioassay;
- (void)p_resetBioVideoRecord;
- (void)p_updateResultViewWithFailedError:(long long)arg1 withErroStr:(id)arg2;
- (void)bioRecordCtrlr:(id)arg1 finishRecordVideo:(_Bool)arg2 withFilePath:(id)arg3;
- (void)p_showBioVideoController;
- (void)p_fetchBioPinCode;
- (void)p_confirmIDNameAndNumer;
- (void)p_fillIdCardNameAndNumberInfoToTextFields;
- (void)p_doCheckAfterAnyIDImageUploadFinish;
- (void)p_uploadIDImageAndProcessImg:(_Bool)arg1;
- (void)p_updateIDCardViewWithPhotoTakenImage:(id)arg1 isEmblem:(_Bool)arg2;
- (void)p_showImagePickerForEmblemView:(_Bool)arg1;
- (void)p_onIdCardViewClick:(id)arg1 viewState:(long long)arg2 isEmblemView:(_Bool)arg3;
- (void)viewDidLayoutSubviews;
- (void)p_onNextBtnClick;
- (void)p_updateNextBtnState:(long long)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (id)p_getErrorStringWithCode:(int)arg1 isVideoVerify:(_Bool)arg2;
- (void)p_showTipsToast:(id)arg1;
- (void)p_showErrorAlert:(id)arg1;
- (_Bool)p_checkAndShowSeqErrorAlertTips:(int)arg1;
- (void)p_showErrorWhenVerifyNameAndIdNum:(int)arg1;
- (void)p_hideBioCheckResultViews:(_Bool)arg1;
- (void)p_hideBioCheckIntroViews:(_Bool)arg1;
- (void)p_hideIDConfirmViews:(_Bool)arg1;
- (void)p_hideIDCheckViews:(_Bool)arg1;
- (id)p_createTextField;
- (void)p_textFiledChanged:(id)arg1;
- (void)p_tapg:(id)arg1;
- (void)p_clickClose:(id)arg1;
- (void)p_initUI;
- (void)p_applyForDetectSeq:(CDUnknownBlockType)arg1;
- (void)p_initLogic;
- (void)viewDidLoad;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

