//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIButton, UIImageView, UILabel, UIView, WWPstnAccountRemainController;

@interface WWPstnInteractRemainCell : UITableViewCell
{
    _Bool _hasGet1000Min;
    _Bool _shouldShowAlreadyFetch;
    _Bool _shouldForceHide1000MinBtn;
    _Bool _isUserQuota;
    _Bool _isSuperAdmin;
    _Bool _isCorpAuthed;
    WWPstnAccountRemainController *_parentCtrlr;
    UIImageView *_clockImgView;
    UILabel *_accRemainLbl;
    UILabel *_remainMinLbl;
    UILabel *_quotaLbl;
    UIButton *_fetch1000MinBtn;
    UILabel *_corpAuthHintLbl;
    UIButton *_corpAuthBtn;
    UIView *_giftMiniInfoSepLineView;
    UILabel *_giftMiniInfoLbl;
}

+ (int)p_remainInMinute;
+ (int)p_totalMinute;
+ (_Bool)p_isUserQuotaMode;
@property(nonatomic) _Bool isCorpAuthed; // @synthesize isCorpAuthed=_isCorpAuthed;
@property(nonatomic) _Bool isSuperAdmin; // @synthesize isSuperAdmin=_isSuperAdmin;
@property(nonatomic) _Bool isUserQuota; // @synthesize isUserQuota=_isUserQuota;
@property(retain, nonatomic) UILabel *giftMiniInfoLbl; // @synthesize giftMiniInfoLbl=_giftMiniInfoLbl;
@property(retain, nonatomic) UIView *giftMiniInfoSepLineView; // @synthesize giftMiniInfoSepLineView=_giftMiniInfoSepLineView;
@property(retain, nonatomic) UIButton *corpAuthBtn; // @synthesize corpAuthBtn=_corpAuthBtn;
@property(retain, nonatomic) UILabel *corpAuthHintLbl; // @synthesize corpAuthHintLbl=_corpAuthHintLbl;
@property(retain, nonatomic) UIButton *fetch1000MinBtn; // @synthesize fetch1000MinBtn=_fetch1000MinBtn;
@property(retain, nonatomic) UILabel *quotaLbl; // @synthesize quotaLbl=_quotaLbl;
@property(retain, nonatomic) UILabel *remainMinLbl; // @synthesize remainMinLbl=_remainMinLbl;
@property(retain, nonatomic) UILabel *accRemainLbl; // @synthesize accRemainLbl=_accRemainLbl;
@property(retain, nonatomic) UIImageView *clockImgView; // @synthesize clockImgView=_clockImgView;
@property(nonatomic) _Bool shouldForceHide1000MinBtn; // @synthesize shouldForceHide1000MinBtn=_shouldForceHide1000MinBtn;
@property(nonatomic) _Bool shouldShowAlreadyFetch; // @synthesize shouldShowAlreadyFetch=_shouldShowAlreadyFetch;
@property(nonatomic) _Bool hasGet1000Min; // @synthesize hasGet1000Min=_hasGet1000Min;
@property(nonatomic) __weak WWPstnAccountRemainController *parentCtrlr; // @synthesize parentCtrlr=_parentCtrlr;
- (void).cxx_destruct;
- (double)p_layoutwithWidth:(double)arg1;
- (double)curHeightWithWidth:(double)arg1;
- (void)layoutSubviews;
- (void)p_updateData;
- (_Bool)p_shouldHiddenCorpAuthUI;
- (_Bool)p_shouldShowGiftMinuteExpireInfo;
- (_Bool)p_shouldHidden1000MinBtn;
- (_Bool)isCorpAuthUIShowed;
- (_Bool)isFetch1000MinBtnCanClick;
- (void)updateData;
- (void)p_enableFetch1000MinBtn:(_Bool)arg1 isAuthed:(_Bool)arg2;
- (void)btn_onAuthCorpBtnClick;
- (void)btn_onFetch1000MinBtnClick;
- (void)p_init;
- (_Bool)p_corpAuthed;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

