//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKTableViewController.h"

@class NSArray;

@interface WWPstnAccountRemainController : WWKTableViewController
{
    _Bool _isSuperAdmin;
    _Bool _shouldShowAlreadyFetchedInCell;
    _Bool _shouldForceHide1000BtnInCell;
    _Bool _isFetch1000MinBtnCanClickHasReport;
    _Bool _isCorpAuthUIShowedHasReport;
    NSArray *_secArr;
}

@property(nonatomic) _Bool isCorpAuthUIShowedHasReport; // @synthesize isCorpAuthUIShowedHasReport=_isCorpAuthUIShowedHasReport;
@property(nonatomic) _Bool isFetch1000MinBtnCanClickHasReport; // @synthesize isFetch1000MinBtnCanClickHasReport=_isFetch1000MinBtnCanClickHasReport;
@property(nonatomic) _Bool shouldForceHide1000BtnInCell; // @synthesize shouldForceHide1000BtnInCell=_shouldForceHide1000BtnInCell;
@property(nonatomic) _Bool shouldShowAlreadyFetchedInCell; // @synthesize shouldShowAlreadyFetchedInCell=_shouldShowAlreadyFetchedInCell;
@property(nonatomic) _Bool isSuperAdmin; // @synthesize isSuperAdmin=_isSuperAdmin;
@property(retain, nonatomic) NSArray *secArr; // @synthesize secArr=_secArr;
- (void).cxx_destruct;
- (id)p_notificationSettingFooterViewWithText:(id)arg1 withTableView:(id)arg2;
- (double)p_notificationSettingHeaderHeightWithText:(id)arg1 withTableView:(id)arg2;
- (id)p_notificationSettingHeaderViewWithText:(id)arg1 withTableView:(id)arg2;
- (void)cell_onGet1000MinBtn;
- (void)cell_onAuthCorpBtn;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)p_corpAuthed;
- (void)noti_jsnativeNotify:(id)arg1;
- (void)p_removeNoti;
- (void)p_addNoti;
- (void)viewDidAppear:(_Bool)arg1;
- (id)backButtonTitle;
- (void)p_initUI;
- (void)p_initLogic;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

@end

