//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface WWRedCustomTopMenu : UIView
{
    UILabel *_mTitleLabel;
    UIImageView *_mImageView;
}

@property(retain, nonatomic) UIImageView *mImageView; // @synthesize mImageView=_mImageView;
@property(retain, nonatomic) UILabel *mTitleLabel; // @synthesize mTitleLabel=_mTitleLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)updateTextLabel:(id)arg1;
- (void)initUI:(id)arg1 image:(id)arg2;
- (id)initWithImage:(id)arg1 image:(id)arg2;

@end

