//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WXChooseInvoiceResp;

@protocol WXApiManagerDelegate <NSObject>

@optional
- (void)managerChooseInvoiceResp:(WXChooseInvoiceResp *)arg1;
- (void)managerPayRespResult:(int)arg1;
- (void)managerBindWxFinish;
- (void)managerLoginFinish:(vector_4c3fbd75)arg1;
- (void)managerLoginRequestNoPermission;
- (void)managerLoginRequestComplementPhoneNumber;
- (void)managerLoginRequestNeedPhoneNumber;
- (void)managerAbortLoginRequest;
- (void)managerEndLoginRequest;
- (void)managerBeginLoginRequest;
@end

