//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDate, NSDateFormatter, NSMutableString, NSString;

@interface WXCAutoDebugPerformanceInfo : NSObject
{
    NSDateFormatter *_formatter;
    NSMutableString *_infos;
    NSDate *_startDate;
    NSDate *_tmpDate;
    double _startMemeryUsed;
    double _tmpMemeryUsed;
    _Bool _enable;
    NSString *_itemName;
}

@property(nonatomic) _Bool enable; // @synthesize enable=_enable;
@property(retain, nonatomic) NSString *itemName; // @synthesize itemName=_itemName;
- (void).cxx_destruct;
- (void)end;
- (void)appendInfo:(id)arg1;
- (void)start;
- (id)init;
- (id)initWithName:(id)arg1;
- (double)usedMemory;
- (double)availableMemory;

@end

