//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSMutableArray;

@interface WXCContactShowMode : NSObject
{
    NSMutableArray *_sortedContact;
    NSMutableArray *_sortedGroupTitle;
    int _contactCount;
    NSArray *_allModeContacts;
}

+ (id)emptyShowMode;
- (void).cxx_destruct;
- (int)groupIndexForAZTitle:(id)arg1;
- (id)groupAZTitles;
- (id)groupTitle:(int)arg1;
- (id)contactInGroup:(int)arg1 atIndex:(int)arg2;
- (int)numberOfContactInGroup:(int)arg1;
- (int)numberOfGroups;
- (id)allModeContacts;
- (int)numberOfContacts;

@end

