//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSData, NSString, UIView, WXCDocSharePicsInfo, WXCPVMergeGroup;

@protocol WXCMultiTalkApiDelegate <NSObject>

@optional
- (void)OnScreenShareVideoChanged:(struct CGSize)arg1;
- (void)onScreenShareEnd;
- (void)onReceivedFirstScreenShareData;
- (void)onScreenShareStart:(NSString *)arg1 shareTopic:(NSString *)arg2;
- (void)onDocShareError:(int)arg1;
- (void)onDocShareOpDrawLineOnPage:(int)arg1 start:(struct CGPoint)arg2 endPoint:(struct CGPoint)arg3 drawCompleted:(_Bool)arg4 opUuid:(int)arg5;
- (void)onDocShareOpMoveToX:(int)arg1 yPos:(int)arg2 scale:(int)arg3;
- (void)onDocShareOpPage:(int)arg1;
- (void)onDocShareEnd;
- (void)onDocShareStart:(NSString *)arg1 shareTopic:(NSString *)arg2 picsInfo:(WXCDocSharePicsInfo *)arg3;
- (void)onPVSignalLevelChange:(int)arg1 isLocal:(_Bool)arg2;
- (void)onSysCallHoldEnd;
- (void)onSysCallHoldBegin;
- (void)onPVMergeCheckInvite:(NSData *)arg1 groupInfo:(WXCPVMergeGroup *)arg2;
- (void)onTalkingMemberPVMergeTalk:(WXCPVMergeGroup *)arg1;
- (void)onMemberChangePVMergeTalk:(WXCPVMergeGroup *)arg1;
- (void)onEnterPVMergeTalk:(NSData *)arg1;
- (void)onCreatePVMergeTalk:(NSData *)arg1 isHitSimultaneous:(_Bool)arg2;
- (void)onLiveHostMemberChange:(NSArray *)arg1;
- (UIView *)onMinimumModeChanged:(NSString *)arg1;
- (void)onFollowLiveSucc:(int)arg1;
- (void)onMemberCloseCamera:(NSString *)arg1;
- (UIView *)onMemberOpenCamera:(NSString *)arg1;
- (void)onTalkSignalLevelChange:(int)arg1;
- (void)onSingleMemberChange:(NSArray *)arg1;
- (void)onCheckInviteFromPhoneBookApp;
- (void)onCheckInvite:(NSData *)arg1;
- (void)onReleaseMultTalkMicSucc;
- (void)onSeizeMultTalkMicSucc;
- (void)onErr:(int)arg1;
- (void)onSpeakerStateChange:(_Bool)arg1;
- (void)onMuteStateChange:(_Bool)arg1;
- (void)onMultiTalkReady;
- (void)onTalkingMember:(NSArray *)arg1;
- (void)onMemberDetailChange:(NSArray *)arg1;
- (void)onMemberChange:(NSArray *)arg1;
- (void)onExitMultiTalk;
- (void)onEnterMultiTalk;
- (void)onAuthSucceed;
@end

