//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPPBGeneratedMessage.h"

@class NSString;

@interface WXCPbVoiceGroupUsrProfile : WXPPBGeneratedMessage
{
}

+ (void)initialize;
- (id)description;

// Remaining properties
@property(nonatomic) unsigned long long abilityFlags; // @dynamic abilityFlags;
@property(retain, nonatomic) NSString *avatarEquipInfo; // @dynamic avatarEquipInfo;
@property(retain, nonatomic) NSString *avatarFaceConfig; // @dynamic avatarFaceConfig;
@property(retain, nonatomic) NSString *headUrl; // @dynamic headUrl;
@property(retain, nonatomic) NSString *username; // @dynamic username;
@property(nonatomic) unsigned int uuid; // @dynamic uuid;

@end

