//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPPBGeneratedMessage.h"

@class NSString, WXCPbWxlUserInfo;

@interface WXCPbWxlComment : WXPPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned long long commentId; // @dynamic commentId;
@property(retain, nonatomic) NSString *content; // @dynamic content;
@property(nonatomic) unsigned long long seq; // @dynamic seq;
@property(nonatomic) unsigned int type; // @dynamic type;
@property(retain, nonatomic) WXCPbWxlUserInfo *userinfo; // @dynamic userinfo;

@end

