//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface WXCQcMsgEngine : NSObject
{
    NSMutableDictionary *_receiveMsgIdentityDic;
    NSMutableArray *_receiveMsgCache;
    NSObject<OS_dispatch_queue> *_asyncSerialQueue;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
- (id)mergeNewMsgs:(id)arg1;
- (void)mergeAndNotifyNewMsgs:(id)arg1 bDispatchAsync:(_Bool)arg2;
- (void)mergeAndNotifyNewMsgs:(id)arg1;
- (void)onNotifyUrgentMsg:(id)arg1;
- (void)onAccountChange;
- (void)doSync;
- (id)getQcMsgByMsgUniqueId:(long long)arg1 addressUuid:(int)arg2 isIncoming:(_Bool)arg3;
- (_Bool)sendMissCallQcMsgAsync:(int)arg1 type:(int)arg2 time:(long long)arg3 phone:(id)arg4 url:(id)arg5 voipId:(id)arg6 type:(int)arg7;
- (_Bool)sendQcMsgsAsync:(id)arg1;
- (_Bool)sendQcMsgAsync:(id)arg1;
- (_Bool)sendQcMsgsSerialAsync:(id)arg1;
- (_Bool)sendQcMsgSerialAsync:(id)arg1;
- (_Bool)sendQcMsgsSync:(id)arg1;
- (_Bool)sendQcMsgSync:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)autorelease;
- (oneway void)release;
- (unsigned long long)retainCount;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

