//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WXCSdkBgStateDetectMgr : NSObject
{
    _Bool _mIsInBackground;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool mIsInBackground; // @synthesize mIsInBackground=_mIsInBackground;
- (void)onApplicationDidEnterBackground:(id)arg1;
- (void)onApplicationWillResignActive:(id)arg1;
- (void)onApplicationDidBecomeActive:(id)arg1;
- (void)onApplicationWillEnterForeground:(id)arg1;
- (void)setInBackground:(_Bool)arg1;
- (_Bool)getIsInBackground;
- (void)dealloc;
- (id)init;

@end

