//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXCTableViewController.h"

#import "UITextFieldDelegate-Protocol.h"
#import "WWKSearchBarDelegate-Protocol.h"
#import "WXCBottomMemberBarDelegate-Protocol.h"

@class NSArray, NSString, QMUILabel, UISearchDisplayController, UITextField, UIView, WWKAlertAction, WWKAlertController, WWKSearchBar, WXCBottomMemberBar, WXCContactShowMode, WXCSysContactGuide, WXCSysContactSearchLogicController, WXCSysContactSelectViewModel;

@interface WXCSysContactViewController : WXCTableViewController <WWKSearchBarDelegate, WXCBottomMemberBarDelegate, UITextFieldDelegate>
{
    WXCContactShowMode *_sysShowMode;
    _Bool _doHaveRecentContacts;
    NSArray *_recentCallLogs;
    WWKSearchBar *_searchBar;
    UISearchDisplayController *_searchController;
    WXCSysContactSearchLogicController *_srchLogicController;
    _Bool _shouldReloadTableAfterFinishSearch;
    WXCSysContactSelectViewModel *_multiSelModel;
    scoped_refptr_e1f85e48 _me;
    WXCBottomMemberBar *_memberBar;
    WWKAlertController *_multiPstnPhoneInputAlert;
    WWKAlertAction *_multiPstnPhoneInputConfirmAction;
    UITextField *_multiPstnPhoneInputTextField;
    WXCSysContactGuide *_noAuthorGuideView;
    NSArray *_sec0arr;
    _Bool _isLastContact;
    _Bool _isSupportExternalContact;
    _Bool _isPstnCallRangeLimited;
    QMUILabel *_pstnCallRangeLimitedLabel;
    _Bool _showRecentContacts;
    _Bool _isForMultiSelect;
    NSArray *_excludedMemberArr;
    CDUnknownBlockType _actionAfterSelection;
    UIView *_headerCoverView;
}

@property(retain, nonatomic) UIView *headerCoverView; // @synthesize headerCoverView=_headerCoverView;
@property(copy, nonatomic) CDUnknownBlockType actionAfterSelection; // @synthesize actionAfterSelection=_actionAfterSelection;
@property(retain, nonatomic) NSArray *excludedMemberArr; // @synthesize excludedMemberArr=_excludedMemberArr;
@property(nonatomic) _Bool isForMultiSelect; // @synthesize isForMultiSelect=_isForMultiSelect;
@property(nonatomic) _Bool showRecentContacts; // @synthesize showRecentContacts=_showRecentContacts;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)recentContactsHeaderViewWithText:(id)arg1;
- (void)fontSizeChanged;
- (id)_top6FrequentCall:(id)arg1;
- (void)_printRecentMemberLog:(id)arg1;
- (void)_handleCallLogChange;
- (void)onCallLogChanged:(id)arg1;
- (void)organizationController:(id)arg1 didSelectUser:(scoped_refptr_e1f85e48)arg2;
- (void)actionButtonClickedForMemberBar:(id)arg1;
- (void)memberBar:(id)arg1 didClickedMember:(id)arg2 atSequenceNum:(int)arg3;
- (void)_initMemberBar;
- (id)_configTitleHeaderInSection:(int)arg1;
- (scoped_refptr_e1f85e48)_fetchWWUserAtIndexPath:(id)arg1;
- (id)_fetchContactAtIndexPath:(id)arg1;
- (long long)_calCellTypeAtIndexPath:(id)arg1;
- (long long)p_cellTypeAtSection0AtRow:(int)arg1;
- (_Bool)isTencentCorp;
- (_Bool)_needShowCorpServiceContactCell;
- (_Bool)_needShowExternalContactCell;
- (int)_totalRowsInSection:(int)arg1;
- (int)_totalSectionNum;
- (void)_configCellForStructContact:(id)arg1 wwkUser:(scoped_refptr_e1f85e48)arg2;
- (void)_configCellForCorpServiceContact:(id)arg1;
- (void)_configCellForExternalContact:(id)arg1;
- (void)_configCellForTecentOrDepartment:(id)arg1;
- (void)_configCellForDepartStruct:(id)arg1;
- (void)_configCellForHint:(id)arg1 hintType:(long long)arg2;
- (void)_configCellForContact:(id)arg1 contactAbstract:(id)arg2;
- (void)_configCellForManualInput:(id)arg1;
- (void)_configCell:(id)arg1 forCellType:(long long)arg2 contactAb:(id)arg3 wwkUser:(scoped_refptr_e1f85e48)arg4;
- (id)_getCellResuseString:(long long)arg1;
- (void)_cascadeSelect:(id)arg1 indexPath:(id)arg2;
- (void)back;
- (void)_didMultiSelectRowAtIndexPath:(id)arg1;
- (void)_didSingleSelectRowAtIndexPath:(id)arg1;
- (void)_loadRtxImgForVisibleCells;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)doAfterContactChangedNotify:(id)arg1;
- (void)searchBarDidClickBackButton:(id)arg1;
- (void)_updateSearchContents;
- (void)_initSearch;
- (void)p_addInputPhoneNumberToMultiPstnBar;
- (void)p_multiPstnTxtFiledChange;
- (void)onDialMulti;
- (void)onDialSingle;
- (void)onExit;
- (void)_initNaviBarButtonItem;
- (void)viewWillLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)scrollViewDidScroll:(id)arg1;
- (id)p_pstnLimitedWording;
- (void)ww_reLayoutCorpCapacityLabel;
- (id)p_createPstnRangeLabel;
- (void)dealloc;
- (void)_removeNoti;
- (void)_addNoti;
- (void)_initMultiSelect;
- (void)_initShowMode;
- (void)_initNoAuthorGuideView;
- (void)_initTableView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

