//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WXCShowModeFactory : NSObject
{
}

+ (id)_genSpecialContactAbstract:(long long)arg1;
+ (id)_genSpecialContactsWithSpecialTypeArray:(id)arg1;
+ (id)_genTopContactsForTopType:(long long)arg1 WithAbstractArr:(id)arg2;
+ (void)_eliminateRedundantHeadImg:(id)arg1;
+ (id)_splitByPhone:(id)arg1 onlyKeepCellPhone:(_Bool)arg2;
+ (id)_splitContactAbstractsWithOriginalArr:(id)arg1 ByType:(long long)arg2;
+ (id)_buildShowModeWithConfig:(id)arg1 AndFilteredContactArray:(id)arg2;
+ (id)_genOrignalContactArrayWithConfig:(id)arg1;
+ (id)_buildShowModeUnderNoFilterWithConfig:(id)arg1;
+ (id)genShowModeForAllContactsOnlyCellPhone:(_Bool)arg1 isSupportExternalContact:(_Bool)arg2 isMultiTalk:(_Bool)arg3;

@end

