//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXOMTAEvent.h"

#import "WXOMTAEventProtocol-Protocol.h"

@class NSArray, NSDictionary, NSString;

@interface WXOMTACustomEvent : WXOMTAEvent <WXOMTAEventProtocol>
{
    unsigned int _duration;
    NSString *_eventID;
    NSArray *_args;
    NSDictionary *_kvs;
}

@property unsigned int duration; // @synthesize duration=_duration;
@property(copy, nonatomic) NSDictionary *kvs; // @synthesize kvs=_kvs;
@property(copy, nonatomic) NSArray *args; // @synthesize args=_args;
@property(copy, nonatomic) NSString *eventID; // @synthesize eventID=_eventID;
- (void).cxx_destruct;
- (id)init;
- (void)encode:(id)arg1;
- (int)getType;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

