//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XADMemoryHandle.h"

@class XADHandle;

@interface XADLibXADIOHandle : XADMemoryHandle
{
    XADHandle *parent;
    _Bool unpacked;
    long long inlen;
    long long outlen;
    unsigned char inbuf[10240];
    unsigned char outbuf[10240];
    struct xadInOut iostruct;
}

- (int)unpackData;
- (struct xadInOut *)ioStructWithFlags:(unsigned int)arg1;
- (void)runUnpacker;
- (id)copyDataOfLengthAtMost:(int)arg1;
- (id)copyDataOfLength:(int)arg1;
- (id)readDataOfLengthAtMost:(int)arg1;
- (id)readDataOfLength:(int)arg1;
- (id)remainingFileContents;
- (id)fileContents;
- (void)writeBytes:(int)arg1 fromBuffer:(const void *)arg2;
- (int)readAtMost:(int)arg1 toBuffer:(void *)arg2;
- (void)seekToEndOfFile;
- (void)seekToFileOffset:(long long)arg1;
- (_Bool)atEndOfFile;
- (long long)offsetInFile;
- (long long)fileSize;
- (void)dealloc;
- (id)initWithHandle:(id)arg1 length:(long long)arg2;
- (id)initWithHandle:(id)arg1;

@end

