//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XADHandle.h"

@class NSArray;

@interface XADMultiHandle : XADHandle
{
    NSArray *handles;
    int currhandle;
}

+ (id)multiHandleWithHandles:(id)arg1;
+ (id)multiHandleWithHandleArray:(id)arg1;
- (void)_raiseSizeUnknownForSegment:(int)arg1;
- (int)readAtMost:(int)arg1 toBuffer:(void *)arg2;
- (void)seekToEndOfFile;
- (void)seekToFileOffset:(long long)arg1;
- (_Bool)atEndOfFile;
- (long long)offsetInFile;
- (long long)fileSize;
- (id)currentHandle;
- (id)handles;
- (void)dealloc;
- (id)initAsCopyOf:(id)arg1;
- (id)initWithHandles:(id)arg1;

@end

