//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XADArchiveParser.h"

@class NSData, NSMutableArray, NSMutableDictionary, XADHandle, XADPath;

@interface XADMacArchiveParser : XADArchiveParser
{
    XADPath *previousname;
    NSMutableArray *dittodirectorystack;
    NSMutableDictionary *queueddittoentry;
    NSData *queueddittodata;
    NSMutableDictionary *cachedentry;
    NSData *cacheddata;
    XADHandle *cachedhandle;
}

+ (int)macBinaryVersionForHeader:(id)arg1;
- (void)inspectEntryDictionary:(id)arg1;
- (id)rawHandleForEntryWithDictionary:(id)arg1 wantChecksum:(_Bool)arg2;
- (id)descriptionOfKey:(id)arg1;
- (id)descriptionOfValueInDictionary:(id)arg1 key:(id)arg2;
- (id)handleForEntryWithDictionary:(id)arg1 wantChecksum:(_Bool)arg2;
- (void)addEntryWithDictionary:(id)arg1 retainPosition:(_Bool)arg2 handle:(id)arg3;
- (void)addEntryWithDictionary:(id)arg1 retainPosition:(_Bool)arg2 data:(id)arg3;
- (_Bool)parseMacBinaryWithDictionary:(id)arg1 name:(id)arg2 retainPosition:(_Bool)arg3;
- (void)addQueuedDittoDictionaryWithName:(id)arg1 isDirectory:(_Bool)arg2 retainPosition:(_Bool)arg3;
- (void)addQueuedDittoDictionaryAndRetainPosition:(_Bool)arg1;
- (void)queueDittoDictionary:(id)arg1 data:(id)arg2;
- (void)popDittoDirectoryStackUntilCanonicalPrefixFor:(id)arg1;
- (void)pushDittoDirectory:(id)arg1;
- (id)topOfDittoDirectoryStack;
- (void)setPreviousFilename:(id)arg1;
- (_Bool)parseAppleDoubleWithDictionary:(id)arg1 name:(id)arg2 retainPosition:(_Bool)arg3;
- (void)addEntryWithDictionary:(id)arg1 retainPosition:(_Bool)arg2;
- (void)parseWithSeparateMacForks;
- (void)parse;
- (void)dealloc;
- (id)init;

@end

