//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSData, NSString;

@interface XADRegex : NSObject
{
    NSString *patternstring;
    struct {
        int re_magic;
        unsigned long long re_nsub;
        char *re_endp;
        struct re_guts *re_g;
    } preg;
    struct {
        long long _field1;
        long long _field2;
    } *matches;
    struct _NSRange matchrange;
    NSData *currdata;
}

+ (id)patternForGlob:(id)arg1;
+ (id)patternForLiteralString:(id)arg1;
+ (id)null;
+ (id)regexWithPattern:(id)arg1;
+ (id)regexWithPattern:(id)arg1 options:(int)arg2;
- (id)description;
- (id)pattern;
- (id)componentsOfSeparatedString:(id)arg1;
- (id)allCapturedSubstringsOfString:(id)arg1;
- (id)allMatchedSubstringsOfString:(id)arg1;
- (id)capturedSubstringsOfString:(id)arg1;
- (id)matchedSubstringOfString:(id)arg1;
- (_Bool)matchesString:(id)arg1;
- (id)allMatches;
- (id)stringForMatch:(int)arg1;
- (_Bool)matchNext;
- (void)finishMatching;
- (void)beginMatchingData:(id)arg1 range:(struct _NSRange)arg2;
- (void)beginMatchingData:(id)arg1;
- (void)beginMatchingString:(id)arg1;
- (void)dealloc;
- (id)initWithPattern:(id)arg1 options:(int)arg2;

@end

